### ISSUE TITLE
Panel bar plus button have non native style that somewhat feels wrong

### ISSUE THREAD

**Issue by mcorossigo** [MacPass/MacPass#1001]
**Describe the bug**
When using tabs in MacPass, there is a one pixel line between the tabs and the plus button, which color clearly stand out from the rest of the UI, and infact is not present in native applications.

**To Reproduce**
1. Open MacPass
2. Click on File > New
3. Look at the panel bar, near the plus button
4. Open Finder
5. Click on File > New panel
6. Look at the panel bar, near the plus button
7. Notice the difference

**Expected behavior**
The shouldn't be any one pixel line, and the color of the plus button should be coherent with the panels title text colors.

**Screenshots**

| App | Theme | Screen |
| -- | -- | -- |
| MacPass | Light | <img width="1280" alt="Schermata 2019-11-11 alle 18 50 55" src="https://user-images.githubusercontent.com/36412793/68609359-559a7900-04b5-11ea-91ed-5707078579b9.png"> |
|Finder|Light|<img width="1280" alt="Schermata 2019-11-11 alle 18 51 30" src="https://user-images.githubusercontent.com/36412793/68609363-56330f80-04b5-11ea-8ff5-3c808bb291d8.png">|
|MacPass|Dark|<img width="1280" alt="Schermata 2019-11-11 alle 18 51 10" src="https://user-images.githubusercontent.com/36412793/68609360-56330f80-04b5-11ea-876a-63de4fe8cdc3.png">|
|Finder|Dark|<img width="1280" alt="Schermata 2019-11-11 alle 18 51 21" src="https://user-images.githubusercontent.com/36412793/68609361-56330f80-04b5-11ea-9aaf-d8c0ce43dc19.png">|

**Desktop (please complete the following information):**
 - macOS: 10.14.6
 - Version 0.7.10

**Comment by mstarke** [comment]
I'm not sure what's wrong there, but MacPass doesn't do anything. The tab bar is rendered by the system frameworks. And on my system (10.14.6) i only see the MacPass style. I am not seeing your Finder style on my Finder…puzzling

**Comment by mstarke** [comment]
I just checked and Safari does look like your Finder screenshot. But all other apps (Terminal, Finder, TextEdit, …) just look like MacPass in your screenshots.

The windows are from top to bottom
- Safari
- Finder
- Terminal
- Fork (git client)
- MacPass

| Last Tab Inactive (Light) | Last Tab Active (Light) | Last Tab Inactive (Dark) | Last Tab Active (Dark) |
| -- | -- | -- | -- |
| ![Screenshot 2019-11-25 at 14 34 51](https://user-images.githubusercontent.com/58428/69544816-d155f480-0f90-11ea-87ba-516538710b7e.png) | ![Screenshot 2019-11-25 at 14 34 31](https://user-images.githubusercontent.com/58428/69544817-d155f480-0f90-11ea-9e4f-16700770e313.png) | ![Screenshot 2019-11-25 at 14 33 19](https://user-images.githubusercontent.com/58428/69544818-d155f480-0f90-11ea-8976-b18137bcd151.png) | ![Screenshot 2019-11-25 at 14 32 49](https://user-images.githubusercontent.com/58428/69544819-d1ee8b00-0f90-11ea-8f06-84bd53b260e8.png) |

**Comment by mcorossigo** [comment]
> I am not seeing your Finder style on my Finder…puzzling

Puzzling indeed. Thanks for checking!
