### ISSUE TITLE
Wiki in write access to everyone

### ISSUE THREAD

**Issue by ImplicitDeny** [MacPass/MacPass#1013]
Just figured out that the wiki of this repo is in full write access to basically anyone.

Just have a look : https://github.com/MacPass/MacPass/wiki/Database-Settings
This page was empty before I came in and just added a single line.

This is probably not the desired behaviour.

**Comment by mstarke** [comment]
Nope. That is by design. I did open it for anyone so contributions are easier. So far there has not been any misuse of this freedom.
