### ISSUE TITLE
MacPass 0.7.10 will not open - Mac OS X 10.15.1 (19B88)

### ISSUE THREAD

**Issue by rmverdi** [MacPass/MacPass#1014]
Generic error: The application “MacPass” can’t be opened.

Messages related to this event from System.log:

Dec  5 09:26:06 C02TW1D8HTDD MacPass[2215]: assertion failed: 19B88: libxpc.dylib + 86572 [99CC9436-D653-3762-ADBB-9054EBD1BA2B]: 0x89
Dec  5 09:26:06 C02TW1D8HTDD com.apple.xpc.launchd[1] (com.sophos.endpoint.uiserver.FinderScan.45370DB8-F421-42FE-B63F-3E6A4E80668C[2218]): Caller wanted oneshot behavior for pre-existing instance: caller = MacPass
Dec  5 09:52:39 C02TW1D8HTDD com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000000a.MacPass[2650]): Could not find and/or execute program specified by service: 13: Permission denied: /Applications/MacPass.app/Contents/MacOS/MacPass
Dec  5 09:52:39 C02TW1D8HTDD com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000000a.MacPass[2650]): Service exited with abnormal code: 78
Dec  5 09:53:08 C02TW1D8HTDD com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000000b.MacPass[2688]): Could not find and/or execute program specified by service: 13: Permission denied: /Applications/MacPass.app/Contents/MacOS/MacPass
Dec  5 09:53:08 C02TW1D8HTDD com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000000b.MacPass[2688]): Service exited with abnormal code: 78
Dec  5 09:54:56 C02TW1D8HTDD com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000000e.MacPass[2726]): Could not find and/or execute program specified by service: 13: Permission denied: /Applications/MacPass.app/Contents/MacOS/MacPass
Dec  5 09:54:56 C02TW1D8HTDD com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000000e.MacPass[2726]): Service exited with abnormal code: 78
Dec  5 10:02:21 C02TW1D8HTDD com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000010.MacPass[2775]): Could not find and/or execute program specified by service: 13: Permission denied: /Applications/MacPass.app/Contents/MacOS/MacPass
Dec  5 10:02:21 C02TW1D8HTDD com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000010.MacPass[2775]): Service exited with abnormal code: 78
Dec  5 10:15:44 C02TW1D8HTDD com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000004.MacPass[1530]): Could not find and/or execute program specified by service: 13: Permission denied: /Applications/MacPass.app/Contents/MacOS/MacPass
Dec  5 10:15:44 C02TW1D8HTDD com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000004.MacPass[1530]): Service exited with abnormal code: 78
Dec  5 10:18:08 C02TW1D8HTDD com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000005.MacPass[2185]): Could not find and/or execute program specified by service: 13: Permission denied: /Applications/MacPass.app/Contents/MacOS/MacPass
Dec  5 10:18:08 C02TW1D8HTDD com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000005.MacPass[2185]): Service exited with abnormal code: 78
Dec  5 10:18:46 C02TW1D8HTDD com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000006.MacPass[2216]): Could not find and/or execute program specified by service: 13: Permission denied: /Applications/MacPass.app/Contents/MacOS/MacPass
Dec  5 10:18:46 C02TW1D8HTDD com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000006.MacPass[2216]): Service exited with abnormal code: 78
Dec  5 10:19:03 C02TW1D8HTDD com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000007.MacPass[2220]): Could not find and/or execute program specified by service: 13: Permission denied: /Applications/MacPass.app/Contents/MacOS/MacPass
Dec  5 10:19:03 C02TW1D8HTDD com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000007.MacPass[2220]): Service exited with abnormal code: 78
Dec  5 10:19:18 C02TW1D8HTDD com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000008.MacPass[2230]): Could not find and/or execute program specified by service: 13: Permission denied: /Applications/MacPass.app/Contents/MacOS/MacPass
Dec  5 10:19:18 C02TW1D8HTDD com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000008.MacPass[2230]): Service exited with abnormal code: 78
Dec  5 10:20:53 C02TW1D8HTDD com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000000a.MacPass[2240]): Could not find and/or execute program specified by service: 13: Permission denied: /Applications/MacPass.app/Contents/MacOS/MacPass
Dec  5 10:20:53 C02TW1D8HTDD com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000000a.MacPass[2240]): Service exited with abnormal code: 78
Dec  5 10:23:06 C02TW1D8HTDD com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000000b.MacPass[2267]): Could not find and/or execute program specified by service: 13: Permission denied: /Applications/MacPass.app/Contents/MacOS/MacPass
Dec  5 10:23:06 C02TW1D8HTDD com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000000b.MacPass[2267]): Service exited with abnormal code: 78

**Comment by mstarke** [comment]
I am currently unable to reproduce this issue. Did MacPass ever start?

**Comment by rmverdi** [comment]
No, I am still unable to open. Tried rolling back, removed stuff from app support folder. Still no luck

On Dec 6, 2019, at 5:17 AM, Michael Starke <notifications@github.com> wrote:

﻿

I am currently unable to reproduce this issue. Did MacPass ever start?

**Comment by mstarke** [comment]
Do you have anything related MacPass configured as Autostart or login items?

**Comment by rmverdi** [comment]
Nothing in autostart or login items.

**Comment by mstarke** [comment]
Anything related to Sophos?

**Comment by rmverdi** [comment]
I have tried disabling Sophos, I do not see anything in the logs. The issue started after I upgraded from 0.7.09 to 0.7.10. I have tried downgrading back to 0.7.09, this did not work either.

**Comment by georgesnow** [comment]
I had this issue, but it was with the continuous build (which I expected). it requires control clicking and clicking open.

**Comment by nlippke** [comment]
I also had the same issue using the zip archive (latest release). The issue is that the executable is not an executable (missing flags).  If you supply those manually, e.g. `sudo chmod a+x Applications/MacPass.app/Contents/MacOS/MacPass` the application starts.

**Comment by mstarke** [comment]
@nlippke I found your observation strange and just re-checked MacPass-0.7.10.zip and the executable hast set all the correct permissions.

    -rwxr-xr-x@ 1 user  group  1226080 28 Okt 15:33 MacPass

Did you just download the version or did this get installed via an update?

**Comment by nlippke** [comment]
@mstarke: IMO it depends on the way you're extracting the archive. Some utilities don't preserve file flags. `unzip` as an example delivers proper results. So it doesn't really look like an issue.

**Comment by rmverdi** [comment]
I re-downloaded and re-installed MacPass today, and it is working now. I have no idea what is different this time around.
