### ISSUE TITLE
Autotype prints "a" the length of the password into Windows Remote Desktop connections 

### ISSUE THREAD

**Issue by packplusplus** [MacPass/MacPass#1020]
**Describe the bug**
Autotype prints "a" the length of the password into Windows Remote Desktop connections. 

**To Reproduce**
1. Go to an RDP window, bring up notepad
2. Click back to macpass
3. Change autotype sequence to `{PASSWORD}`
4. Run autotype
5. RDP window comes back to the forefront, and shows aaaaaaa (the length of the password)

**Expected behavior**
Autotype should have filled notepad with the correct password

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - macOS: 10.15.2 (19C57)
 - Version: 0.7.10

**Additional context**
Similar behaviors reported in keepassx for RDP, NxMachine, and VMWare. 
* https://github.com/keepassxreboot/keepassxc/issues/3080

**Why this bug matters**
The standard way to change a password on a windows server is to press ctl+alt+delete to bring up the change password dialogue. The copy / paste buffer is disabled while that dialogue is up, which means you have to manually type long complex passwords correctly multiple times (old, new, new password). 

You can go into computer management and change the administrator password manually, but it comes with scary dialogue boxes telling you to use ctl+alt+delete, and warns of lost information, death, destruction, pestilence, and the salting of your most fertile fields (or maybe just the first one in that list).

**Comment by georgesnow** [comment]
curious if you use KeePass for windows that would mean you can't copy from a local windows KeePass database either correct?

**Comment by mstarke** [comment]
This problem is rooted in the way Autotype generates keyboard events. The first system tried to find the appropriate key via a reverse lookup. This worked mostly for Latin based inputs but broke for other keyboard layouts. The current approach sends a keyboard event for the physical key 'a' but with the sting of the required character (the event structure supports this behavior). This seems to work in most cases except your scenario. Currently this is a better trade of than the loss of support for non-Latin keyboard layouts. I might try to fix it I come around to it.

**Comment by georgesnow** [comment]
@mstarke this could an application for #1017 
In that user could use the plugin when bundle id matches ie RDP to drive different auto type function.

**Comment by georgesnow** [comment]
@packplusplus  @mstarke so this appears to fix by Microsoft in the latest update for macOS RDP client v 10.3.8

if you switch to unicode mode it appears AutoType now works properly.

Keyboard shortcut to change to unicode mode:
CTRL+COMMAND+U

so this is awesome.

**Comment by cottington** [comment]
Yep @georgesnow thanks so much for the tip. Can confirm it works for me too. I was so sad about this for months!

**Comment by packplusplus** [comment]
Cleaning up my github history. This issue is indeed fixed by doing the unicode mode in RDP. I'm closing the issue. Thanks for the fix / workaround.

**Comment by adamrparsons** [comment]
Sorry to reboot an old issue but this same behavior happens in Macos Screen Sharing. All letter 'A'. I've tried to sync the keyboard language but otherwise I'm not sure how else to fix it
