### ISSUE TITLE
Clarify where search does take place

### ISSUE THREAD

**Issue by mstarke** [MacPass/MacPass#1026]
The search field in the toolbar shows only a "Search" string. It's unclear where the search is happening.

**Expected**
* a clear way of knowing where search is searching (e.g. search everywhere)

**Comment by mstarke** [comment]
Fixed in 8e52da7069cc009e894b5bd37593f605428dc2db

**Comment by michaelfresco** [comment]
I really love this build (8e52da7)! Much bigger search box, and obvious instructions for the user!! :blush:

Thanks for showing too where to define these specs in source too!
