### ISSUE TITLE
Not able to open keyfile

### ISSUE THREAD

**Issue by shreegurusewa** [MacPass/MacPass#1033]
**Describe the bug**
When I try to open the database, it opens the popup to select the keyfile. After selecting the key file, the open button stays disabled.

**To Reproduce**
1. close the database
2. Open the database
3. type in your password
4. click choose file
5. click the keyfile
<img width="800" alt="Screenshot 2020-01-29 at 11 43 04 AM" src="https://user-images.githubusercontent.com/60382423/73332396-a176e600-428c-11ea-8bc9-224d117a320c.png">

**Expected behavior**
After selecting the keyfile, the open button should enable and let me click it.

**Screenshots**

**Desktop (please complete the following information):**
 - macOS: [e.g. 10.15.2]
 - Version 0.7.10 (22740)

**Additional context**

**Comment by mstarke** [comment]
Duplicate #1005. This is a known issue that is already fixed. 0.7.11 including the fix will get released this week.
