### ISSUE TITLE
Feature request : Add option to hide the macpass symbol on the dock when not in use 

### ISSUE THREAD

**Issue by F3000** [MacPass/MacPass#1035]
Hi , 

i diidnt found any seeting for that .   At the moment , when a user close the main window, the app icon looks like the programm is open (white dot under the icon). 

![Bildschirmfoto 2020-02-02 um 22 08 14](https://user-images.githubusercontent.com/8161283/73615496-a0391680-4608-11ea-90eb-b48c6970555b.png)

Is it possible to create a setting option to hide the symbol when a user click on the red button in the main window (or delete the white dot when the user has pinned macpass to the dock)?

**Comment by georgesnow** [comment]
I am working on! I am testing it in my plugin currently. It’s 2nd part of the pull request for launch on login.

**Comment by mstarke** [comment]
@F3000 MacPass uses the default behaviour of a document based macOS application by not closing when the last window is closed. The white dot on the Dock shows up when the app is running. If you want MacPass to quit when the last window is closded (and this way remove the dot as you say) you can use a hidden preference that is not editable in the UI.

Enable closing with the last window by running the following in the terminal:

    defaults write com.hicknhacksoftware.MacPass QuitOnLastWindowClose -bool YES

@georgesnow I guess you are referring to completely hiding the icon from the Doch which I suspect is something different than what @F3000 is asking for.

**Comment by F3000** [comment]
@mstarke 

Thanks . All I want is that when no visible Macpass window is open , than a user shouldn’t see any (active) icon in the dock too . 

I hope this is more understandable . 


Otherwise I wil try it in German :)
