### ISSUE TITLE
Autotype does not work at all

### ISSUE THREAD

**Issue by tpluscode** [MacPass/MacPass#1038]
**Describe the bug**

Recently I've been unable to get it to work where is used to before.

**To Reproduce**
1. Go to a website whose title matches an entry
2. Press auto type key combination
4. `No Match for Item-0`

**Desktop (please complete the following information):**
 - macOS: 10.15.2
 - Version 0.7.11

**Comment by mstarke** [comment]
Can you elaborate "where it used to before" a bit more? Item-0 looks like MacPass is not able to get the correct window title. Sometime this is also a "Focus Proxy" window title, which happend a lot when using Autotype on the AppStore.

To narrow this down pleas supply a list of Apps where Autotype is broken now and where it still works.

**Comment by tpluscode** [comment]
Ah indeed. So it stopped working in Safari 13.0.4. Latest Chrome (80) and Firefox (72) are fine

**Comment by tpluscode** [comment]
I'm not sure which MacPass version it last worked with. May not have upgraded to each one

**Comment by mstarke** [comment]
This is not a direct solution but you could use the AutotypeURL plugin which will read the URL of safari (and chrome) windows and allow direct better URL extraction. You might want to give it a try. But the problem still needs fixing.

**Comment by tpluscode** [comment]
Oh, that plugin's awesome. I've been waiting for such a feature ever since I've been using MacPass. Thanks!

**Comment by mstarke** [comment]
You should thank @georgesnow for coming up with the idea and implementing it.

**Comment by aesyondu** [comment]
> I'm not sure which MacPass version it last worked with. May not have upgraded to each one

Reverted to 0.7.10 for now to fix the issue.

**Comment by mstarke** [comment]
@aesyondu what problem are you encountering? This seems unrelated to the original issue. Item-0 matching is something that comes up when safari displays a status icon and I'm currently testing some mitigations that will get published soon if I get to it considering the current circumstances.

**Comment by aesyondu** [comment]
Oh my bad, it is indeed unrelated. I don't use the title matching feature yet, didn't know there was one.

In 0.7.11, `Cmd + t (Perform Autotype)` stopped working, so I downloaded 0.7.10 and it worked again. Now that you mentioned it, I downloaded 0.7.11 again and `Perform Autotype` seems to work fine.

**Comment by mstarke** [comment]
The inital issue should be solved with 16ca18623e1333c0f7f129081163676eaed4e039

**Comment by mstarke** [comment]
@aesyondu Nice that Autotype works again. This might have been an issue with Permissions and MacPass not properly reporting that something is not correctly set up.
