### ISSUE TITLE
TOTP support, please!

### ISSUE THREAD

**Issue by IANatCAMBIO** [MacPass/MacPass#1044]
I just switched from KeepassXC. The native GUI here is much better in OSX. But, some of my accounts have TOTP, and I can't login. Is there any effort being made on that feature?

**Comment by georgesnow** [comment]
similar to #895 

it is something I would really like myself. not sure what needs to happen for it to be workable

**Comment by IANatCAMBIO** [comment]
I think that both Keepass and KeepassXC have it working, so there is support for it in the database schema. 

I'm using the same DB shared between my phone and laptop. TOTP works on my phone with KeepassDX, MacPass is just reading it as an extra custom field.

I do see that there's an objective-c library for it here:
https://github.com/mattrubin/onetimepassword. I've never used ObjC before, so I have no idea how much work it would be to leverage an existing library for this functionality.

**Comment by georgesnow** [comment]
interesting my understanding is. @mstarke has added tests for TOTP. so the pieces are there, but I was actually  referring to what needs to happen in MacPass's code from the work that has been complete to provide the functionality.

**Comment by dinigo** [comment]
Here https://github.com/MacPass/MacPass/issues/895#issuecomment-475900915 @mstarke says he already implemented it in the standard library. This feature will be very welcome by my 5000 workmates :)

**Comment by ThHirsch** [comment]
Oh YES - PLease!  Really want to have this integrated into MacPass.
I use FreeOTP on my mobile. but want tho have it integtated into my MacPass as well.
So count me in for +1 please.
Many many thanks for your great work!

**Comment by mstarke** [comment]
The current continous release has support for TOTP. The setup is currently not working but you can set custom fields manually and get a TOTP display in the inspector

**Comment by IANatCAMBIO** [comment]
Awesome! I just took a look at the custom fields in Inspector, and have no idea how to implement TOTP. Is there a wiki page or something that can walk me through it?

**Comment by mstarke** [comment]
the easiest way is to add a custom field with the name "otp" and the otpauthURL as value

**Comment by mstarke** [comment]
Implemented.
