### ISSUE TITLE
MacPass won't let me add new records 

### ISSUE THREAD

**Issue by psquared24** [MacPass/MacPass#1049]
I imported a Keypass database into MacPass.  I can see all the data.  I just can't add anything new.  The new entry button stays grey  Any insights on how to fix that?

**Comment by mstarke** [comment]
You can add entries if a group is selected. Look at the outline and if there is no selection you should be able to add entries by choosing a group.

**Comment by psquared24** [comment]
Oh. My. Stars.  I can’t believe I missed that.  THANK YOU!

**Comment by mstarke** [comment]
No problem.
