### ISSUE TITLE
Disable pre-generated passwords for new entries

### ISSUE THREAD

**Issue by djlongy** [MacPass/MacPass#1050]
Could there be a checkbox to disable the password generator for new entries?

The native original KeePass app allows for this.

Mainly when you do not want to use generated passwords, you don’t have to keep clearing the pre-filled data.

**Comment by mstarke** [comment]
I think this might be an easy addition.

**Comment by Luthien-in-edhil** [comment]
That would be very useful. I was just looking if this was possible and couldn't find it; I'm currently copying a huge list from a file into MacPass and have to take care to not forget to replace the autogenerated PW with the actual one. If it would not autofill it, it would be much easier to notice I had forgotten something.
