### ISSUE TITLE
Make MacPass fully offline - Please point to the change i need to make.

### ISSUE THREAD

**Issue by davidfrothin** [MacPass/MacPass#1053]
**Describe the solution you'd like**
I would like to know the exact lines of code to change to be sure that MacPass cannot talk to any server or process any calls or link to external sites. This will really help make sure that no information or password / contents of files leave the computer. 

This might be relatively straightforward, please point me to the code to comment or change to help make sure that MacPass is fully offline. I can then compile that version and use it on my devices.

Thanks for this app!

**Comment by mstarke** [comment]
MacPass has 3 places, where it communicates with a server:

1. Sparkle contacts the Update repository. 
2. MacPass reads a favicon.ico file upon user-request
3. MacPass reads macpassapp.org/plugins.json to update it's plugin definitions

### Disable Sparkle
Change the code in a way, that lines aren't executed to disable Sparkle. Alternatively you can define ```NO_SPARKLE``` to disable it upon build.
https://github.com/MacPass/MacPass/blob/0662a729a0dcc024d4d846ef6fc801b72b54e27c/MacPass/MPAppDelegate.m#L223

https://github.com/MacPass/MacPass/blob/0662a729a0dcc024d4d846ef6fc801b72b54e27c/MacPass/MPUpdatePreferencesController.m#L56-L58

### Disable Favicon download

Remove the body of the following method:
https://github.com/MacPass/MacPass/blob/0662a729a0dcc024d4d846ef6fc801b72b54e27c/MacPass/MPIconHelper.m#L174-L202

### Disable Plugins.json download

Remove the body of the following method:
https://github.com/MacPass/MacPass/blob/0662a729a0dcc024d4d846ef6fc801b72b54e27c/MacPass/MPPluginRepository.m#L106-L136
