### ISSUE TITLE
Cannot select existing key file when changing password

### ISSUE THREAD

**Issue by davidfrothin** [MacPass/MacPass#1056]
**Describe the bug**
Open db then go to File -> "Change master password". 
1. Users should be able to choose an existing key file. Currently it only allows users to generate a new key file and use. 
2. If there is an existing key file then that needs to allow users to just change the master password. Currently it will remove key file if only password is changed.

**Comment by mstarke** [comment]
That's a nasty UI bug that slipped thought!

**Comment by mstarke** [comment]
Fixed in 8b3cc34ab58dad595f485a1885107e5082b283e8

**Comment by davidfrothin** [comment]
Thanks, new update works well.
