### ISSUE TITLE
Autotype based on URL has stopped working

### ISSUE THREAD

**Issue by dkniffin** [MacPass/MacPass#1057]
**Describe the bug**
After updating to the latest version (currently 0.7.11), autotype based on URL has stopped working.

**To Reproduce**
1. Create an entry for a website, including a host/domain. For example, "google.com"
2. In preferences -> integration, check "Include Entry URL for matches" and "Include Entry Host for matches"
3. Install the AutotypeURL plugin and have the preference set to "Use host as window title" (not sure if this is necessary or not)
4. Go to the website and try to perform autotype

**Expected behavior**
Credentials should be autotyped

**Actual behavior**
Credentials are not autotyped and I see a message "No match for XXX"

**Desktop (please complete the following information):**
 - macOS: 10.15.3
 - Version 0.7.11

**Comment by georgesnow** [comment]
@dkniffin just as a first step can you confirm in privacy system settings macpass has permissions under Automation to control Safari? If so, in the mean time you can try quitting macpass and Safari. Uncheck and recheck the box and relaunch both apps and try again.

I will see if can reproduce this out after I update to 10.15.3.

**Comment by dkniffin** [comment]
@georgesnow Yep, looks like something there worked. I unchecked everything I could find for macpass in "Security & Privacy" and rechecked them, restarted chrome, restarted macpass, and now it's working. Thanks!

**Comment by dkniffin** [comment]
Just want to note that I just had this same issue again, with the same fix. Not sure if it was triggered by an update to Macpass or what.
