### ISSUE TITLE
Autotype broken after update to 0.7.12 on Catalina

### ISSUE THREAD

**Issue by luke52** [MacPass/MacPass#1062]
I just did the latest update to versio 0.7.12. After updating autotype is broken...

**To Reproduce**
1. Visit login page and switch to MacPass
2. Click password entry and hit command + t
2. As intended the login page gets focussed again
4. No insertion of username nor password

**Expected behavior**
Autotype of password

**Desktop (please complete the following information):**
 - macOS: Catalina
All permissions (control and screen recording) are granted and autotype doctor does not indicate any issue.

**Comment by mstarke** [comment]
Autotype did not change in this release so this seems strange. Can you remove and re-add MacPass in the Accessibility Settings?

**Comment by luke52** [comment]
Solved, Thanks.
