### ISSUE TITLE
Search in Notes field

### ISSUE THREAD

**Issue by uglygus** [MacPass/MacPass#1063]
**Is your feature request related to a problem? Please describe.**
The search bar does not search in the Notes field. 

**Describe the solution you'd like**
I would like the search bar to also search the Notes fields of all keys.

**Additional context**
 I use Notes to store all kinds of little bits of information that I don't want lying on my HD unencrypted being able to find them through search would be helpful. I'm coming from Passpack which I held on to for way too long and it would search Notes. I miss that feature.

Also just a general thanks for making MacPass. I am very happy with it!

**Comment by mstarke** [comment]
If you tick "search everywhere" notes get searched, only searching in notes is currently not possible.

**Comment by uglygus** [comment]
Fantastic thanks! I missed that line of search tags somehow.  Search Everywhere is all I need but..

> only searching in notes is currently not possible.

When I selected just the Notes tag and deselect the others it seemed to search Notes only.

**Comment by mstarke** [comment]
You are correct, I have just forgotten that that is possible. What might confuse you is that the buttons to select where to search fold into the drop-down menu if the space is too tight for them.
