### ISSUE TITLE
Support of Keeform browser extension

### ISSUE THREAD

**Issue by ericmoret** [MacPass/MacPass#1072]
[KeeForm](https://keeform.org/) is "A Simple Form Filler for Keepass" that automates the filing of credentials on websites. It includes a browser extension running on Chrome and a helper plugin for Keepass. I would be nice for MacPass to support KeeForm as a more hands off way to pre-fill websites credentials.

**Comment by georgesnow** [comment]
@ericmoret Are you using safari or chrome? You could try the AutotypeURL plugin. It extends global Auto type by getting the url from the browser.

**Comment by ericmoret** [comment]
Indeed, you can disregard this request.
