### ISSUE TITLE
Search Option: avoid backup folder

### ISSUE THREAD

**Issue by vivekFAGH** [MacPass/MacPass#1078]
**Is your feature request related to a problem? Please describe.**
Searching returns all entries where the search term is found, including the backups folder. This can result in a large amount of entries for certain keywords.

**Describe the solution you'd like**
A configuration setting as simple as a checkbox that can be used to avoid the backups folder

**Describe alternatives you've considered**
One option would be to just color code the backup entries

**Comment by mstarke** [comment]
The Keepass container enabled search exclusion. Just select your backup folder, and then in the folder settings (in the inspector) set search to disabled.

![Screenshot 2020-05-25 at 11 06 11](https://user-images.githubusercontent.com/58428/82797724-cd3f5c80-9e77-11ea-885b-c4ffae4adcd5.png)
