### ISSUE TITLE
No UI is displaying

### ISSUE THREAD

**Issue by mr-feek** [MacPass/MacPass#1080]
**Describe the bug**
No UI is displaying

**To Reproduce**
I'm not sure what has happened or how to help debug more -- but I am happy to try.
When i open my database, no UI displays. If I click on the `window` toolbar menu, all options are grayed out.

**Expected behavior**
The database UI should display

**Screenshots**
![image](https://user-images.githubusercontent.com/5747667/83075012-ff8fbc00-a027-11ea-891a-ecfe4cf83c08.png)

**Desktop (please complete the following information):**
 - macOS: 10.15.3
 - Version 0.7.12

**Comment by mstarke** [comment]
Can you see if you can find anything int the logs (Console.app) regarding MacPass?

**Comment by mr-feek** [comment]
Any tips for how to find a log file?

![image](https://user-images.githubusercontent.com/5747667/83078897-7f6d5480-a02f-11ea-80aa-27bce67d6bd1.png)

**Comment by mstarke** [comment]
Take a look at the system.log this might yield something. But I suspect there's nothing there. If you create a new database, does this also not show any windows?

**Comment by mr-feek** [comment]
Creating a new database does indeed show the windows

**Comment by mstarke** [comment]
well.

**Comment by mr-feek** [comment]
I made a new one, saved it, closed the application, then tried opening it again and no luck -- no windows displayed anywhere.

**Comment by mr-feek** [comment]
Huh -- I might have just noticed something. After a few times of opening / closing the application, I was presented with the password login page for my "new" database. I closed this window, then tried going to open my original database, and no windows displayed.

**Comment by mstarke** [comment]
Do you store the database on some special volume? I currently have no real clue how to debug your problem…

**Comment by mr-feek** [comment]
I'm going to close this as it is now working again 🤷
