### ISSUE TITLE
Feature Request: Increase space between password view & generate buttons

### ISSUE THREAD

**Issue by AmritRaj23** [MacPass/MacPass#1081]
**Description**
I have accidentally overwritten my passwords because of clicking the password generate button instead of password view button. 

**Describe the solution you'd like**

It would be nice if in the inspector: 
* There is more spacing between the password view and generate button or
* The generate button is made smaller in width

**Additional context**
<img width="488" alt="buttons" src="https://user-images.githubusercontent.com/14956443/83428665-22104380-a433-11ea-9d89-f9936bf98709.png">

**Comment by mstarke** [comment]
This should get solved by introducing a dedicated edit mode and display an entry in read only by default.

**Comment by mstarke** [comment]
Pressing the generate button does not change the password. This requires you to click "use password" in the pop-up as well. If you simply cancel the pop-up nothing gets changed. However, I did move the button to the side which still allows for "misses" but should reduce the amount of wrong hits

![Screenshot 2020-10-12 at 15 34 38](https://user-images.githubusercontent.com/58428/95752716-bcfe1180-0ca0-11eb-9b8e-da881f5a6aed.png)
