### ISSUE TITLE
MFA

### ISSUE THREAD

**Issue by dkhanal0** [MacPass/MacPass#1082]
**Is your feature request related to a problem? Please describe.**
This application doesn't have a forgot password option available. 
**Describe the solution you'd like**
It would be better if multi-factor authentication is developed for this application. 
**Describe alternatives you've considered**
It will be more secure for the user if they have multi-factor authentication. User needs to verify using the phone or email while accessing the KeePass.

**Comment by mstarke** [comment]
The KeePass database format has no mechanism to recover passwords. The only way for it to work with no technical changes is a via a third-party that stores your **full** credentials and can give them to you. This is obviously no viable solution. The whole point of the container is, that only the user has access to the database and or contents of it.
