### ISSUE TITLE
Place cursor in search field after unlock (like in Keepass)

### ISSUE THREAD

**Issue by ruedigerO** [MacPass/MacPass#1090]
It would be nice if the Search field is the default on unlock of a database.
(Same behavior as in Keepass)

From my point of view it's faster to search than selecting by the tree

**Comment by georgesnow** [comment]
I built a plugin that provides similar functionality with combination of a hotkey. when you trigger the hotkey unlocked will land focus in the search field. Locked database will do that same as long as you unlock the database within a few seconds.

**Comment by ruedigerO** [comment]
Puh, was a hard bit of work (I'm new to MacOS development :-()
It's working but..
I usually open two databases. With two or more the plugin didn't work (focus is not on Search.

**Comment by georgesnow** [comment]
@ruedigerO right so it only triggers based on the current document. At the time I used second database infrequently so I never tested in this scenario (or programmed for it). 

However, I agree and would personally want an option for the focus to be search for any database after unlock. That being said maybe I can incorporate this into the plugin or as pull request for the main code as a preference. This won't be soon though I have had little to no time for development on the plugin or the other pull request I have been working on for Touch ID support. Hopefully the current plugin will at least be marginally better for your workflow for now.

**Comment by fturcheti** [comment]
This would be indeed helpful. 99% of my MacPass launches are followed by a `cmd+f`.

**Comment by jschneid** [comment]
Evidently this will be implemented in the next release? https://twitter.com/MacPassApp/status/1457737420095598599

**Comment by mstarke** [comment]
Indeed it will get published with 0.8. It’s already present in the continuous built.
