### ISSUE TITLE
[Feature] Do not request Screen Recording Permission for Auto-Type

### ISSUE THREAD

**Issue by mstarke** [MacPass/MacPass#1091]
Global Autotype requires Screen recording permission on Catalina and above to read window titles.
Currently every invocation of Autotype checks for this as well but actually doesn't need this.

To reduce the permissions required to run MacPass it should be possible to use Autotype without Screen Recording Permissions.

Extracted from comment in #948

**Comment by mstarke** [comment]
This is false. Autotype also uses the window title of the last active application so both auto-type and global auto-type require screen recording permission.

**Comment by woalk** [comment]
But why does it use the window title at all when I manually `Cmd+T`? It should just input into whatever window is in focus, like any other KeePass client does.

At least this should be a setting.

**Comment by mstarke** [comment]
> But why does it use the window title at all when I manually `Cmd+T`? It should just input into whatever window is in focus, like any other KeePass client does.

It does input in whatever window was in focus. But MacPass has to determine what to input in that window, since the entry might have different keystrokes for different window titles via window associations. This is the same behaviour that Keepass has so my decision was to let MacPass do the same thing.

> ### Keyboard Context Menu: 'Perform Auto-Type' Command
> [...] The sequence which is auto-typed depends on the window's title. If you didn't specify any custom window/sequence associations, the default sequence is sent. If you created associations, KeePass uses the sequence of the first matching association. If none of the associations match, the default sequence is used.
https://keepass.info/help/base/autotype.html#autoctx
