### ISSUE TITLE
Correct password doesn't work, but keyfile of same password will work.

### ISSUE THREAD

**Issue by 13re** [MacPass/MacPass#1098]
When entering the correct password, an error shows "The password and/or keyfile is wrong (1017)". 
But if I use a keyfile generated from the same password, my MacPass then opens. 

I am new to using MacPass, but have used KeyPass before. 
I am using a 2015 Macbook Air on MacOS Catalina Version 10.15.5

**Comment by 13re** [comment]
Solved - the issue is fixed by reseting the password once - even if to the same password as before.

**Comment by mstarke** [comment]
I’m having trouble understanding the problem. It should not require to reset a password for it to work with MacPass. This seems rather strange. Could you try to reproduce the issue with a second database?

**Comment by idbrii** [comment]
@mstarke I'm having this issue too on MacPass 0.7.12.

I made two databases that use the same key file:

* BugTestFromMac.kdbx - created with MacPass 0.7.12 on macOS 10.14.6
* BugTestFromWin.kdbx - created with KeePass 2.47 (64-bit) on Windows 10.0.19042 Build 19042

I'm able to open/close/open the databases on the platform they were created on. However I cannot open them on the other platform.

 I tried to make them contain the same content and the Win version is 1K larger:

* 1.6K BugTestFromMac.kdbx
* 2.6K BugTestFromWin.kdbx

I'm using the same keyfile for both, so I can't see how that format could be wrong. And removing the keyfile also works, so it doesn't seem like the database format is wrong. It **seems like MacPass uses the keyfile to encode the file in a different way** than KeyPass.

## Open BugTestFromWin on macOS

I copypaste the password into macpass and select the key file and get:

> The password and/or keyfile is wrong (1017)


## Open BugTestFromMac on Win10

I copypaste the password into keypass and select the key file and get:

> Failed to load the specified file!

>The master key is invalid!

>Make sure that the master key is correct and try it again.

## Remove keys

If I open each kdbx and reset the master password to the same password, but don't use a key file, then **I can open the key files** on any platform.

## Repro

I've attached the files (with and without key) and password so you can try them out yourself and compare them: 
[macpass-bug.zip](https://github.com/MacPass/MacPass/files/7706823/macpass-bug.zip)

**Comment by idbrii** [comment]
Ah, I see from #1164 that the issue is that MacPass 0.7 doesn't support keyfile v2 and I see inside my keyx file that it's v2. Seems like I'll have to wait for MacPass 0.8 to use keyfiles.

**Comment by mstarke** [comment]
@idbrii did you re-check the issue with 0.8?

**Comment by idbrii** [comment]
I checked on 0.8.1 (I think) and was able to open my db with keyfile. Thanks for the new release!
