### ISSUE TITLE
Can't update entry titles

### ISSUE THREAD

**Issue by Ikuyu** [MacPass/MacPass#1102]
I can update the entry icon in the upper right part of the inspector window, but not its title. I'm running the latest version of macOS Catalina.

**Comment by mstarke** [comment]
The title field besided the icon is not editable. The title is displayed again as the first text field below.
![Screenshot 2020-08-18 at 14 41 33](https://user-images.githubusercontent.com/58428/90514141-0fb7c300-e161-11ea-94bc-a3dd588ded75.png)

**Comment by Ikuyu** [comment]
It wasn’t visible until i imported my database in KeepassX, saved it and loaded again in MaxPass. Now it’s fine.

--

**Comment by mstarke** [comment]
What do you mean by visible? Did the field not apear? But if the title is displayed so should the input field?

**Comment by Ikuyu** [comment]
Indeed, the input field did not appear.

With regards,

Edwin (Ikuyu)

**Comment by mstarke** [comment]
But others where there? Did you build MacPass from source?

**Comment by Ikuyu** [comment]
The other were there, yes. I did not build MacPass from source.

**Comment by mstarke** [comment]
The view is a scroll view, did you by accident have the title field "scrolled out the top" ?

**Comment by Ikuyu** [comment]
That is certainly possible. I wasn't aware it was a scroll view at all! Overlook it completely....

**Comment by mstarke** [comment]
This comes up frequently. I thought that adding the divider above and below when scrolled would allow users to notice the scrolled-under content but this seems to happen quite often nonetheless.

**Comment by Ikuyu** [comment]
You only see the scrollbar when you **scroll** inside the scroll view, not when you **move** the arrow on the screen over it with the mouse/trackpad. That's probably why my bell didn't ring the view could be scrolled.
