### ISSUE TITLE
I've uninstalled Macpass because of forgotten password  but every time I reinstall it, Macpass tell me to digit my password 

### ISSUE THREAD

**Issue by Ghittons** [MacPass/MacPass#1107]
basically I want to keep using macpass, I don't care about the password saved before, I know they have to be deleted, I just want to keep using macpass, please help me

**Comment by mstarke** [comment]
Can you elaborat a bit? Does MacPass re-open a database file? If so, simply close this one and use another one. All passwords are stored in database files so you can have more than one and use them. You are not pinned to one database.

**Comment by mstarke** [comment]
Any news? If not, I'll close this.
