### ISSUE TITLE
Database does not exist 

### ISSUE THREAD

**Issue by ElisaCadelli** [MacPass/MacPass#1109]
After a software update on my MacBook Air macOS 10.15.7, my MacPass data base does not open. It seems to have deleted the information, or at least I cannot access it. Does anybody know what to do?

It states "problem with opening the document. It could not be opened because the data base does not exist."

![Bildschirmfoto 2020-10-02 um 09 15 32](https://user-images.githubusercontent.com/60326266/94897422-de385400-048f-11eb-910c-415568fcae38.png)

Thank you for your help!

**Comment by mstarke** [comment]
Is your database really "Ohne Title.kdbx" or is this something else? MacPass has an internal store for the last known database that is used if the system does not report any previous files. However it should not try to open an unavailable file.

What you can do to fix this:
- Search you mac for any .kdbx files or even better the exact file you where using
- Do you use any cloud storage to save the file?
- If so, was the file not synched properly or missing at the moment of opening MacPass?

A system update should not delete any files saved on your mac.

**Comment by ElisaCadelli** [comment]
Thanks for your help. I could not find the file - perhaps I have deleted it accidentally, I don't know what's going on. But I have all by backups on a hard drive and will try to look for the file there. 
Thanks again for your answer!
