### ISSUE TITLE
how to move an entry from a group to another group

### ISSUE THREAD

**Issue by roazhon** [MacPass/MacPass#1111]
hello,
perhaps it's to simple but I din't find how organize my entries to split them in two groups from one...thanks for help
Macpass Version 0.6.2 (12420)

**Comment by mstarke** [comment]
Do you have a certain reason to still use 0.6.2? If not, I strongly encourage you to upgrade to the latest version 0.7.12.

To move entries around you have to drag them onto the desired new group they should be in. This is done by dragging them from the entry list onto the group in the sidebar.

**Comment by roazhon** [comment]
thank you, it's done
