### ISSUE TITLE
MacPass Security Questions

### ISSUE THREAD

**Issue by UnixCro** [MacPass/MacPass#1112]
Hello dear developers of the MacPass program.
I have two questions about MacPass that I would like to know. In addition, I am not really familiar with computers, so please do not be surprised if you have such questions.

The passwords as I got them are saved in a kdbx database. If someone pulls this kdbx database onto his computer or Mac, can he read out the passwords with this kdbx database by bruteforcing the program login window?

Isn't it a risk for the program to leave the source code open, since malicious code can be injected and the user transmits his passwords to the compromised program?

**Comment by mstarke** [comment]
> Hello dear developers of the MacPass program.
> I have two questions about MacPass that I would like to know. In addition, I am not really familiar with computers, so please do not be surprised if you have such questions.

As the saying goes: There are no stupid questions. Only stupid answers.

> The passwords as I got them are saved in a kdbx database. If someone pulls this kdbx database onto his computer or Mac, can he read out the passwords with this kdbx database by bruteforcing the program login window?

A bruteforce attack is always possible regardless of how secure the database is encrypted. This makes using a strong key for encrypting the database all the more important. MacPass currently only allows you to use a password and/or a key file but by combining them you get a pretty secure key which is very hard to guess. The original creator of KeePass has some good write-up on the security of the database (https://keepass.info/help/base/security.html). A lot of the points there are tied to the format and algorithms which apply to MacPass as well.

> Isn't it a risk for the program to leave the source code open, since malicious code can be injected and the user transmits his passwords to the compromised program?

There are two things you combine in your question. By opening the source of the application, an attacker can find weak points and use them but those weak points can also be identified by others and then fixes can be applied. MacPass is always signed and notarized. The included update mechanism only allows for new versions signed by the same developer to be used so no one should be able to distribute another compatible version of MacPass. The first download needs to be checked but the default gatekeeper checks on macOS should take care of this. Additionally you can use the hash when downloading a version via GitHub to see if you got the correct release and nothing is compromised.
