### ISSUE TITLE
Several bugs with MacOS 11.0.1 Big Sur

### ISSUE THREAD

**Issue by wrogner** [MacPass/MacPass#1113]
** Here is a list of observed bugs **
Please filter out individual issues:

1) Search field stops working
Launch MacPass
Enter Search field, enter search string -> OK
Select any other entry
Entering search field not possible

Expected: possibility to enter search string
Actual: no search possible
Workaround: Cmd-F

2) Action icons in menu bar not enabled (New entry, Delete, New Group, ...)

On launch, none of the menu icons are active

Expected (and worked before): Icons active and working
Actual: grayed out icons, none-operational
Workaround: Main Menu -> File -> New Entry (and so on)

3) minor cosmetic issues (icon colours blue, ...)
Not relevant for now.

**Desktop (please complete the following information):**
 - macOS: 11.0.1
 - Version 0.7.12

**Comment by mstarke** [comment]
Thanks for the info. All bugs are known and stem from a 10.10 deployment target of the application. The upcomming 0.8 release will raise the minimum macOS version to 10.13 and testing has shown that the severe issues have been resolved. An update to address any Big Sure specifics (e.g. UX) will be the next goal.

**Comment by wrogner** [comment]
If you are at it, don't let yourself be disturbed ;-)

If I can of any help, please let me know.

**Comment by xrisk** [comment]
thanks for the great work!

**Comment by sreese4u** [comment]
Thanks for MacPass, cool piece of software. Any ETA on a new release for the Big Sur fixes? The searching bug is extremely annoying.

**Comment by ArekMC** [comment]
> Thanks for MacPass, cool piece of software. Any ETA on a new release (I guess version 0.8) for the Big Sur fixes? The searching bug is extremely annoying.

If you hit cmd+F twice, you can "reactivate" the search input field.

**Comment by sreese4u** [comment]
> If you hit `cmd+F` you can "reactivate" the search input field and the buttons in the top bar
Thank for the workaround I appreciate it. Still, I think a new release would make things much easier (there are more issues with Big Sur).

**Comment by mstarke** [comment]
Could you check if the current continous build fixes the issues (sans the blue accent as this  is no issue but a new Big Sur feature)

**Comment by wrogner** [comment]
If we talk about Version 0.8-beta (20201231211202-continuous):

Search field works as expected
Icons to create new entries, groups and others work

Yep: Looks good on macOS Big Sur 11.1.

**Comment by AndreasLehmann** [comment]
I tested the app today (0.8-beta) at MacOS Big Sur 11.1, too. Works perfectly! Thanks!

**Comment by AndreasLehmann** [comment]
Work perfect. Thanks ! I wish you a great 2021.

BR
Andreas

**Comment by xrisk** [comment]
Search bug seems be fixed, although I must say I preferred the older design as it allowed me to use the search even with a small window width. Is there some way to workaround this?

**Comment by mstarke** [comment]
@xrisk what do you mean by old design? I did not change anything about the UI so this might be another Big Sur issue?

**Comment by mstarke** [comment]
I'm closing this since the bugs described are fixed and will get pushe in 0.8

**Comment by eriegz** [comment]
@mstarke Any ETA on version 0.8?

**Comment by mstarke** [comment]
@eriegz Yesterday
