### ISSUE TITLE
MacPass native Apple Silicon M1

### ISSUE THREAD

**Issue by tsr876** [MacPass/MacPass#1115]
Any plan to have MacPass running native on new MacOS Apple Silicon M1 11.x.x?
If yes, any time frame?

**Comment by mstarke** [comment]
Master does compile an Apple Silicon already. The Upcoming 0.8 release will have a native ARM binary. Plugins should follow shortly as they need to be re-compiled for Apple Silicon as well to be usable.

**Comment by tsr876** [comment]
Great!!!!

Thanks

**Comment by TMSantos** [comment]
Cool nice to know! I've been using it under emulation (Rosetta 2) and the issue I found is that "search box text" gets blocked sometimes, if a native binary comes would be great

**Comment by tschinz** [comment]
any new in that front? this is over a year old and still no 0.8 version available?
Thanks

**Comment by mstarke** [comment]
The continous build should run native on Apple Silicon.

**Comment by tschinz** [comment]
Thanks for the feedback, for an application that manages all my passwords and can potentially mess up the *.kbdx file the message of continuous build is too scary for me.

> The binary release of the current code. This build is not signed and might contain serious bugs. You've been warned!

**Comment by mstarke** [comment]
0.8.1 is out with native Apple
Silicone support.

**Comment by tschinz** [comment]
wow amazing, thank you so much 🙏🏼 . Tested on M1 Pro, performance has much improved and many small issues are resolved. 👍🏼
