### ISSUE TITLE
Various mistakes in German localisation

### ISSUE THREAD

**Issue by Andreas-Kromke** [MacPass/MacPass#1117]
At first glance I found several mistakes and typos, I just listed some as attached below. Typical or "popular" mistakes in Germany are:

- Wrong space in substantives („Deppen Leer Zeichen“)
- Missing commas
- Denglish
- Wrong uppercase
- Wrong conjugation or declination, like "verwerfe" or "bewerbe" (WRONG) instead of "verwirf" and "bewirb".

========================

"Alles Löschen" -> "Alles löschen"

"Um die Berechtigung zum Aufzeichnen des Bildschirminhaltes anzufordern wird ..." -> "Um die Berechtigung zum Aufzeichnen des Bildschirminhaltes anzufordern, wird ..."

"Fenster-Assoziationen" -> "Fensterzuordnungen" or "Fenster-Zuordnungen"

"Plugindaten" -> "Plugin-Daten"

"Nach ausloggen sperren" -> "Nach Abmelden sperren"

""Standardicon verwenden" -> "Standard-Icon verwenden"

"KDB Datenbank" -> "KDB-Datenbank"

"KDBX Datenbank" -> "KDBX-Datenbank"

"MacPass Plugin" -> "MacPass-Plugin"

"MacPass erlaubt Plugins AppleEvents zu nutzen." -> "MacPass erlaubt Plugins, AppleEvents zu nutzen."

".. Wechseldatenträge .." -> ".. Wechseldatenträger .."

".. um sicher zu stellen .. " -> ".. um sicherzustellen ..."

"KDB Datenbanken enthalten ..." -> "KDB-Datenbanken enthalten ..."

"Es werden KDB Datenbanken ..." -> ""Es werden KDB-Datenbanken ..."

".. Plugineinstellungen .." -> "Plugin-Einstellungen"

"Updates sind dekativiert." -> "Aktualisierungen sind deaktiviert."

"Autotype Einstellungen" -> "Autotype-Einstellungen"

"MacPass hat die Berechtigung den" -> "MacPass hat die Berechtigung, den"

"Später Ändern" -> "Später ändern"

"Autotype Löschen" -> "Autotype löschen"

"Kopiere Referenz Menü" -> "Kopiere Referenz-Menü"

"Standardbrowser" -> "Standard-Browser"

"Passwörter stimmen nicht überein oder die Schlüsseldatei ist ungültig!" -> "Passwörter stimmen nicht überein, oder die Schlüsseldatei ist ungültig!"

"Lade die andere Version und verwerfe meine Änderungen" -> "Lade die andere Version, und verwirf meine Änderungen"

"Behalte meine, verwerfe andere!" -> "Behalte meine, verwirf andere!";

"Behalte andere, verwerfe meine!"; -> "Behalte andere, verwirf meine!";

"Nicht Neustarten" -> "Nicht neustarten"

"Das Plugin konnten .." -> "Das Plugin konnte .."

"Arbeitsfluss" ->  "Arbeitsablauf"

"Nach Updates suchen …" -> "Nach Aktualisierungen suchen …"

"Autotype Doktor" -> "Autotype-Doktor"

"Willkommen zu MacPass" -> "Willkommen bei MacPass"

globally: "und/oder" is ugly und unnecessary and should be "oder"

**Comment by mstarke** [comment]
Thank you Andreas. It's a bit embarrassing for a native speaker to have such a long list of mistakes :).

If you feel up to it you can use the localisations files from the continuous build and update the mistakes by yourself and you an easily open a pull request.

**Comment by Andreas-Kromke** [comment]
This is called "merge request" in gitlab, isn't it? Getting confused with git-lab and -hub, but I will try.

**Comment by Andreas-Kromke** [comment]
OK, pull request created, was some work..

**Comment by mstarke** [comment]
Thank you for your input, Since you created PR #1119 I'm closing this.
