### ISSUE TITLE
Cant start MacPass on macOS Big Sur 11.0.1

### ISSUE THREAD

**Issue by patrickbussmann** [MacPass/MacPass#1120]
**Describe the bug**
Fresh installation of macOS with newly downloaded MacPass results in a "You don't have the permissions to open MacPass".

    User doesn't have permission to launch the app (managed networks)

**To Reproduce**
1. Download MacPass from releases
2. Click on the app
3. See error

**Expected behavior**
App is shown.

**Screenshots**
Only in German language.
<img width="338" alt="Bildschirmfoto 2020-12-16 um 19 14 31" src="https://user-images.githubusercontent.com/15617021/102389285-2bc65680-3fd3-11eb-90b9-96efdde6a9f4.png">

**Desktop (please complete the following information):**
 - macOS: 11.0.1
 - Version 0.7.12

**Additional context**

    % open -a MacPass
    The application /Applications/MacPass.app cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10826 "kLSNoLaunchPermissionErr: User doesn't have permission to launch the app (managed networks)" UserInfo={_LSFunction=_LSLaunchWithRunningboard, _LSLine=2508, NSUnderlyingError=0x7f7fba70e1e0 {Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x7f7fba70e180 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" UserInfo={NSLocalizedDescription=Launchd job spawn failed with error: 1}}}}}

I read this issue: https://github.com/MacPass/MacPass/issues/1087

    However, permission dialogs for Accessibility don't get triggered. I had to manually add MacPass, but that being said.

But even with the `Accessibility` permissions it doesn't work.

**Comment by mstarke** [comment]
I have no real clue why macOS does not allow you to start MacPass. Have you tried deleting and re-downloading the app?

**Comment by mlazowik** [comment]
@patrickbussmann is that a corporate computer enrolled into some kind of MDM? This error suggests so, and that you'd have to get MacPass allowlisted with your IT dept.

**Comment by mlazowik** [comment]
Ok, no, this seems more related: https://apple.stackexchange.com/questions/408752/the-message-you-do-not-have-permission-to-open-the-application-is-shown-when-t

**Comment by patrickbussmann** [comment]
no @mlazowik i only enabled iCloud.
Nothing else.
No MDM or something like that.

**Comment by georgesnow** [comment]
Is MacPass in the applications folder or you trying to open from somewhere else? Ie downloads or desktop folder

**Comment by patrickbussmann** [comment]
@georgesnow I tried different folders. Even documents, desktop, applications.

**Comment by DominusExult** [comment]
To also add my thoughts:

Download it again and make sure you use Finder to move MacPass into the Applications folder.
(I ran into similar problems when I used another file manager to do it).

**Comment by markokeeffe** [comment]
I was able to circumvent this issue by doing the following:
- Find MacPass.app in Finder
- Right click -> Show Package Contents
- Find `MacPass` executable file in Contents/MacOS and open it

A terminal window should open and run MacPass from the command line. I had to get past a couple of warnings from the OS, but was able to use the application as usual

**Comment by georgesnow** [comment]
It is also possible that there is quarantine  Flag set after download. 

You can check in terminal 
run:
`xattr /Applications/MacPass.app`

If it returns com.quarantine you just need to delete the flag and try relaunching macpass

**Comment by patrickbussmann** [comment]
With MacOS 11.2.3 and MacPass 0.7.12 (23610) it's working now.
