### ISSUE TITLE
Password Context Menu is Obscuring the Password Field

### ISSUE THREAD

**Issue by robbpriestley** [MacPass/MacPass#1121]
In the most recent version, this new Passwords... context menu keeps appearing over top of the Password field, obscuring it. I personally don't want to use this feature.

<img width="348" alt="Screen Shot 2020-12-20 at 11 03 18 AM" src="https://user-images.githubusercontent.com/16694050/102722053-65d57800-42b3-11eb-81a0-583db5c5efd2.png">

**Comment by georgesnow** [comment]
That’s macOS 11 built password API. This isn’t actually a MacPass feature. It is peculiar though that it presents over the text field like that though.

**Comment by robbpriestley** [comment]
Oh, interesting.

Perhaps I will get annoyed enough to try to figure out how to turn that feature off.

**Comment by mstarke** [comment]
macOS 11 introduced contentType on NSTextFields and secure inputs might automatically show this pop-up. I will try to investigate and find out if it's possible to programatically disable this for those fields since it should not be used in those instances.

**Comment by mcaserta** [comment]
#1125 should take care of this.

**Comment by mstarke** [comment]
Fixed with the ugly solution of setting the fields content type to one-time-password. this will then pop up the menu again, if a sms-auth code is sent and the field is in focus :-/
