### ISSUE TITLE
HELP: MacPass Error_Password_Or_Keyfile_Wrong (1015) & (1017)

### ISSUE THREAD

**Issue by ghost** [MacPass/MacPass#1122]
Hello, 

I have absolutely no idea what went wrong. I can't login into MacPass anymore. 
I really need access to a couple of passwords and I don't know what to do...

When I try to open it, it always shows:
"Error_Password_Or_Keyfile_Wrong (1015)"

after I downloaded the newest version it started to show
"Error_Password_Or_Keyfile_Wrong (1017)"

I use macOS Catalina and on the other Macbook I use macOS Big Sur 
but both Macbooks won't open the file even though the password is correct.

![Bildschirmfoto 2020-12-21 um 13 46 46](https://user-images.githubusercontent.com/76435639/102778516-0189e580-4393-11eb-80be-f641318451cb.png)
![Bildschirmfoto 2020-12-21 um 13 46 40](https://user-images.githubusercontent.com/76435639/102778520-02bb1280-4393-11eb-9ff7-dfb3dcf62aad.png)

**Comment by DominusExult** [comment]
Are you sure you don't have a keyfile (Schlüsseldatei) set up?
It's an extra file that you need to decrypt your password file (if you set that up)

**Comment by fckgthb** [comment]
Thank you for the reply. @DominusExult 
It just stopped working from one day to another... I've tried several Schlüsseldateien/Key files but nothing fits.

![Bildschirmfoto 2020-12-21 um 13 58 54](https://user-images.githubusercontent.com/76435639/102779552-ba045900-4394-11eb-95e8-ba1b06905f34.png)

**Comment by DominusExult** [comment]
This makes me pretty sure that a keyfile is involved. As that is consistent with one day not working anymore (so MacPass didn't automatically link with the keyfile anymore)

**Comment by fckgthb** [comment]
@DominusExult  Well... in that case I have no clue what the name of that file could be, because my ex did all the setup years ago 🤦‍♀️

Do you have any idea on how I can find it!? I already tried a couple of files but it still won't work.... damnit

**Comment by mstarke** [comment]
@fckgthb could you try to clear the Schlüsseldatei. You cannot use the database file (MacPass) as the key file since this will yield a corrupt database!

**Comment by fckgthb** [comment]
@mstarke  Thanks for your comment. How can I do that, when I don't know the name of the file (Schlüsseldatei)? 🙈

**Comment by mstarke** [comment]
Sorry, I did only look at the last screenshot which was using the database as key file. There is no way you can find out the name of the key file :-(

**Comment by fckgthb** [comment]
Ahh, alright. :(

**Comment by sreese4u** [comment]
So we are using issues now to solve relationship related problems for people who name themselves "fuck github"?

**Comment by mstarke** [comment]
I'm closing this since it's either resolved or a human error as far as I can tell.
