### ISSUE TITLE
Ability to Set Default Password Length and Characteristics

### ISSUE THREAD

**Issue by robbpriestley** [MacPass/MacPass#1123]
I'd like a feature in Preferences where I can set the **default length of new passwords**. 12 is not long enough for me and I always have to override the default.

In preferences, I would also like to control whether the **Use characters from every group** option is set by default or not (it currently isn't). This is a problem because most services these days require characters from every group, and I'd prefer not to have to visually inspect my passwords or keep remembering to turn this option on.

It would also potentially work if you made these choices "sticky" and then Preferences items wouldn't be needed.

<img width="350" alt="Screen Shot 2020-12-22 at 7 05 28 AM" src="https://user-images.githubusercontent.com/16694050/102903279-f54e6880-4424-11eb-83c1-affaac4857a5.png">

**Comment by mstarke** [comment]
The default password settings are set using the password edit view (either stand alone as the password generator or as the pop up when using the generate button on entries). If you change the settings from the defautl ones (which are the ones that the generator loads up with) the "Set Defaults" Button on the left gets enabled. If you want those settings to be global, leave the "Use default only for selected entry" Box unticked and click the Button. This then sets the current settings as default and all new generator calls will use them until you change them again.

**Comment by robbpriestley** [comment]
OK that works! Thanks for letting me know!
