### ISSUE TITLE
Search bar unclickable

### ISSUE THREAD

**Issue by JamsheedMistri** [MacPass/MacPass#1126]
**Describe the bug**
This may be related to #1124. When focused on something in MacPass (such as a password or an entry), you cannot click the search bar to focus, therefore not allowing you to search. The only way you can focus the bar is if you do Command + F and wait a few seconds (as described in #1124). This wasn't an issue before macOS 11 (Big Sur).

**To Reproduce**
1. Open MacPass
2. Enter password
3. Click on any password or entry to focus
4. Click on search bar

**Expected behavior**
Search bar should focus immediately

**Video**

https://user-images.githubusercontent.com/13024750/103056658-5de73380-4552-11eb-971d-7eafcf7c3e8f.mov

**Desktop (please complete the following information):**
 - macOS: 11.2 Beta (been happening since 11.0)
 - Version 0.7.12

**Comment by ArekMC** [comment]
See: #1113 
Workaround: Click `CMD+F`

**Comment by bunducafe** [comment]
Does not do the trick on my macbook. First yes, but if I continue to search it lags.

**Comment by mstarke** [comment]
Can you try the current continous release? The issue should be fixed there!

**Comment by JamsheedMistri** [comment]
This is fixed in the current continuous release. Thank you.
