### ISSUE TITLE
MacPass is not reliable anymore. It need to be communicated.

### ISSUE THREAD

**Issue by gagarine** [MacPass/MacPass#1128]
MacPass is not just any app. It's a security app. If it become unreliable it's become a security problem. Nobody want to be responsible of security problems.

Today MacPass is unusable on Big Sur. Advance users may find workaround, but other user may just start to take risk like stop using a password manager, copy password on post-it, lose some content, and more. Perhaps a co-worker or a family member recommended MacPass to a nontechy. Now this user end-up with a piece of not working software. Not cool.

It also gives a bad reputation, not only to a password manager, but to open-source.

I fully understand it's an open-source project, and it's made in free time, without warranty and so fort. Yet there is a website that advertises https://macpassapp.org/ how the app is great and "MacPass behaves just the way a macOS app should". It doesn't. MacOS app should at least work.

If this project is not reliable anymore, it's OK. But it should be clearly communicated so users can make better choices.

My complaint is MacPass is super accessible, easy to use. But all this breaks very bad if it’s become unstable regularly under automatic macOS update.

**Comment by mstarke** [comment]
I am very aware of the problems that occur under macOS 11.0 and most issues are fixed already. I’ve had the unfortunate luck of having to take care of my family because of well known reasons and this lead to me having  no time left to finish up a release for MacPass. I am still aiming for a release in 2020 to help all those users running Big Sur.

**Comment by gagarine** [comment]
I fully understand that the project may not have the necessary resources at the moment. I do not blame anyone for that and certainly not you. I'm not aware of your personal life but even if you just lose interest in this project that would be fine. Peoples should be free. Personally if I'm not happy with MacPass I can simply chose another client.

At the same time, this kind of situation have consequences. Especially on user without high technical skills.

If you want to continue this project, perhaps some safeguard could be put in place in term of release cycle? Having another admin?

**Comment by DominusExult** [comment]
I think this blown out of proportion. MacPass doesn't work right but the problems have been found. But for me there is no show stopper for now.

This is not uncommon when a new version of macOS lands and nothing can prevent this from happening.

It might have warranted a quick update on the homepage and the project but this push makes me scratch my head on what I'm missing here

**Comment by gagarine** [comment]
Let's close this. @mstarke could certainly come up with somethings when it got some time to avoid this kind of situation and more importantly reduce potential stress.
