### ISSUE TITLE
New Entry Doesn't Focus

### ISSUE THREAD

**Issue by JamsheedMistri** [MacPass/MacPass#1129]
**Describe the bug**
When doing Command + N or clicking the "New Entry" button, if you are currently focused on the left-hand sidebar, the new entry will be created, but will not be focused.

**To Reproduce**
1. Open MacPass and authenticate
2. Click on one of the categories on the left-hand sidebar
3. Command + N or "New Entry"

**Expected behavior**
New entry is created, and the right-hand sidebar is focused

**Actual behavior**
The left-hand sidebar remains focused, even though the new entry is created. You then must click on the new entry to focus it on the right-hand sidebar.

**Desktop (please complete the following information):**
 - macOS: 11.2 Beta
 - Version 0.8-beta (20201231211202-continuous)

**Comment by mstarke** [comment]
That's a know regression introduced by fixing another bug related to entry selection stealing focus when the group is selected in e03660b184d26b68190ed359f1f81d6a76ecd515

**Comment by mstarke** [comment]
Fixed in f25db6b4188d33ea7bcd91f048207b329387012b
