### ISSUE TITLE
Key shortcuts

### ISSUE THREAD

**Issue by noose** [MacPass/MacPass#114]
I need some keyboard workflow.
Open MacPass (cmd + space) -> open database (cmd + o) -> password -> find element (cmd + f) -> select element (mouse?! what about down arrow, or tab, or sth?) -> copy password....

Can You add some shortcut to select element? :) Another think - I need mouse to select group :(
Regards,
Pawel

**Comment by nwoolls** [comment]
Seems like this requires using the arrow keys too, at least when going from the Search field to Entries. You have to use the ⌘⌥E key combo followed by down-arrow.

**Comment by monkeydri** [comment]
There is no entry menu anymore to create an entity (⌘+⌥+E) so how to add it via OSX > System preferences > Keyboard > Shortcuts ?

**Comment by mstarke** [comment]
There is, the default ist Cmd+Shift+E

> On 14 Feb 2017, at 12:05, monkeydri <notifications@github.com> wrote:
> 
> There is no entry menu anymore to create an entity (⌘+⌥+E) so how to add it via OSX > System preferences > Keyboard > Shortcuts ?
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


___m i c h a e l   s t a r k e____ 
       geschäftsführer
       HicknHack Software GmbH
       www.hicknhack-software.com
       
___k o n t a k t____
       +49 (170) 3686136
       contact@hicknhack.com
       
___H i c k n H a c k   S o f t w a r e   G m b H____
       geschäftsführer - maik lathan | andreas reischuck | michael starke
       bayreuther straße 32
       01187 dresden
       amtsgericht dresden HRB 30351
       sitz - dresden

**Comment by monkeydri** [comment]
Yes sorry I've seen it just after I posted (I deleted the message). I successfully changed the keyboard shortcut with ⌘+N in System Preferences > Keyboard > Shortcuts with text "Add Entry".
