### ISSUE TITLE
View Passwords in Plaintext

### ISSUE THREAD

**Issue by Be8ung** [MacPass/MacPass#1143]
Hi! An option to "show all passwords" (no stars) in plaintext under the menu-point "view" would be really great!
Thanx in advance.
![Screenshot 2021-01-29 at 11 35 26](https://user-images.githubusercontent.com/37075435/106265229-04e07e80-6227-11eb-8a46-9d250e0863e2.png)

**Comment by mstarke** [comment]
Should be possible. Might I ask, what version of macOS you are running? The upcoming 0.8 release will raise the minimum version to 10.13 since supporting 10.12 and below has become quite cumbersome.

**Comment by Be8ung** [comment]
I am running macOS Mojave version 10.14.6

**Comment by earthsound** [comment]
@mstarke it may help to dup #347 and #532 against this since you've added this to the 0.8 milestone and the others are only labeled as Enhancements.

**Comment by mstarke** [comment]
@earthsound valid. Housekeeping is sometimes a bit cumbersome. Duplicate of #347

**Comment by andramar** [comment]
Hi @mstarke, 

Only one doubt, how to apply code update (https://github.com/MacPass/MacPass/commit/95184ed2ec629c1bd06f9cf0f45b65288233a9c1#) in order to enable the "view passwords list" as text in the panel?

Thanks

**Comment by mstarke** [comment]
You need to right click on the table header in the entry list and then enable the password column and check the “show passwords” option in the context menu.

**Comment by andramar** [comment]
Great! Thanks!

BTW, AWESOME product!

**Comment by mstarke** [comment]
A picture is worth a thousand words:
![Screenshot 2022-02-23 at 11 45 49](https://user-images.githubusercontent.com/58428/155304460-e3b0bf8b-b9c2-4131-8b7a-48e438d8b4a4.png)
