### ISSUE TITLE
NOt able to see passcode because of autofill pop-up

### ISSUE THREAD

**Issue by edwinnieuwenhuyse** [MacPass/MacPass#1147]
![image](https://user-images.githubusercontent.com/24915869/106796351-838c5000-665b-11eb-9f72-503fbb29acb7.png)

I love the app so much.
But I would like to see the password and then this annoying MacOS password prompt shows on top of this.
Anyway I can remove that?
Could be a MacOS issue, but for me it ruins the MacPass user experience....

**Comment by mstarke** [comment]
Duplicat of #1121
