### ISSUE TITLE
Toolbar is regularly greyed out for no obvious reason

### ISSUE THREAD

**Issue by tivolinick** [MacPass/MacPass#1148]
**Describe the bug**
All the options except 'Action' in the toolbar are greyed out so I cannot use them. The commands that I would use from the toolbar are still available in the Menus and in the action menu and can be used from there. I have to click around in the rest of the app to make the toolbar come back.

**To Reproduce**
1. open the application
2. click anywhere in the main list section

**Expected behavior**
All the options in the toolbar should still be available
**Screenshots**
<img width="772" alt="macpass1" src="https://user-images.githubusercontent.com/33629374/107123862-62687100-68a0-11eb-960f-19bc10655ec6.png">

**Desktop (please complete the following information):**
 - macOS: [e.g. 11.1]
 - Version 0.7.12 (23610)

**Additional context**

**Comment by mstarke** [comment]
Known issue under Big Sur. Will be fixed with 0.8. Curren developer Snapshot (continuous) will already work under Big Sur.
