### ISSUE TITLE
Plugins - can’t build on Apple silicon

### ISSUE THREAD

**Issue by georgesnow** [MacPass/MacPass#1149]
I can't seem to build MacPass plugins on an M1 Mac. I have tested MacPassHTTP as well as my plugin MacPassRevealer. I tried modifying some of the build settings. I haven't attempted the auto type url.

Has anyone had success building the plugins on Apple silicon?

**Comment by mstarke** [comment]
I‘ve not tested any of them but a detailed error log would help. I will try to check this in the next week on my DTK and see if I can get them to build and maybe even push out the releases.

**Comment by georgesnow** [comment]
Will do.

**Comment by georgesnow** [comment]
ok, AutotypeURL I was able to build successfully. I can't build MacPassHTTP and MacPassRevealer.

Output is below let me know if there is more info you need. I had tried changing the search paths cause it seemed (or seems) like it has to do with locating the frameworks, but I had no luck going down that path so far.


Output of MacPassHTTP (I get the same error for my plugin):
```
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/georgesnow/dev/MacPassHTTP/build/MacPassHTTP.build/Release/MacPassHTTP.build/Objects-normal/arm64/MPHRequestAccessWindowController.o /Users/georgesnow/dev/MacPassHTTP/MacPassHTTP/MPHRequestAccessWindowController.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```

**Comment by georgesnow** [comment]
on MacPassRevealer I get this:

```
../../MacPass/Carthage/Checkouts/KeePassKit/KeePassKit/KeePassKit.h:17:9: fatal error: 'KeePassKit/KPKPlatformIncludes.h'
      file not found
#import <KeePassKit/KPKPlatformIncludes.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by mstarke** [comment]
Looks like some changes to KeePassKit that aren’t reflected in your code. MacPass used a pre-release 3.0 KeePassKit version which breaks compatibility with 2.0 so this might be the cause. I also need to investigate whether it‘s possible to use Carthage for the dependency on MacPass itself or otherwise strip out a Plugins Framework that can be used by all instances to make dependency resolving automatic and easier.

**Comment by mstarke** [comment]
None of this has happened due to the fact that the MacPass Plugin Developer Community has a healthy count of two 😄. But this might also be there exact reason there are only two …

**Comment by georgesnow** [comment]
so I got it to build ...finally...oh boy was it frustrating....I don't think this was the correct way, but I figured out that in the headers <KeePassKit/...h> it can't locate the files. not sure what the fix is 🤷‍♂️ long term.

**I had to delete in the Checkouts for KeePassKit and HNHUi any where the headers had this:**
<KeePassKit/...
<HNHUi..>

and make it so it was just the filename. I also had to modify  

**in SecureTextField header I had to add NS:**

@interface HNHUISecureTextField : NSSecureTextField <NSTextViewDelegate>

**and MPDocument.h to this:**

 @param entryOrNil

from:
@param entry

**Comment by Pa1nstar** [comment]
Hi @georgesnow,

unfortunately I am not able to compile plugins myself, but I would be desperate to find a working MacPassHTTP plugin for Apple Silicion / M1 (MacPass Version 0.8+). :)

Could you send me your compiled version of the MacPassHTTP plugin?

I would be infinitely grateful. :-)

Many greetings,
#Bl4ckst4r

**Comment by georgesnow** [comment]
Sorry, I don't have signing certificate for distributing Mac apps. 

Have you tried building it and it failed? If so, did you try the steps I did above?

**Comment by georgesnow** [comment]
going to close this as I am not sure it is still applicable. this ticket exists if someone runs into this issue and can at least try what I did above.
