### ISSUE TITLE
/ key moves focus to search bar

### ISSUE THREAD

**Issue by HenryDev** [MacPass/MacPass#1153]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to mouse click on the search bar to focus on it.

**Describe the solution you'd like**
Like Gmail, keyboard shortcut of / moves focus onto search bar, so that the entire workflow can be done without the mouse.

**Describe alternatives you've considered**
The search icon on the keyboard touch bar, but that doesn't work right now

**Additional context**
On Big Sur, I have to click the tool bar a couple of times and tap the search icon a few times to get the search bar to light up.

**Comment by FlexIDK** [comment]
confirm on big sur. 
On catalina all work perfect.

**Comment by mstarke** [comment]
You can use `cmd + F` to move the focus to the search bar (disregarding the current bugs in Big Sur). I'm not keen on adding single key keyboard commands. Alternatively move the focus to the search field on unlock seems like a good compromise.

**Comment by mstarke** [comment]
Regarding the toolbar issues, this is a duplicate.
