### ISSUE TITLE
[Bug] After search the first highlighted entry can’t be copied

### ISSUE THREAD

**Issue by georgesnow** [MacPass/MacPass#1154]
The steps I take that make it occur reliably

Unhide macpass 
Command + f
Type search and results return
First entry is highlighted (but not blue like when you fully select)
Press  keyboard shortcut for copy username or password nothing happens (in previous versions and Catalina this worked)

if you arrow down and fully highlight it copy works.

the only reason I noticed is my other Mac runs Catalina and it works as expected.

Continuous build 
macOS Big Sur

**Comment by FlexIDK** [comment]
@georgesnow Need add permission on Settings -> Accessibility

**Comment by georgesnow** [comment]
So this only occurs on the continous build. The behavior is present on Big Sur and Catalina. 
I wonder if this is related to the changes for the search field. I will try and do screen capture demonstrating the difference.

**Comment by mstarke** [comment]
I've had this issue once but wasn't able to replicate it. Will have to take a look at what's causing this.

**Comment by georgesnow** [comment]
here is an example of the behavior:

![mp-entrycopy](https://user-images.githubusercontent.com/12751441/112079242-335b4580-8b56-11eb-9d5e-9f5fb2c17931.gif)

in previous versions once the search returns an entry. the first entry highlight changes the inspector, which in turns means when you copy a field it matches. even when its only gray highlighted.

**Comment by mstarke** [comment]
@georgesnow Nice find. There where changes to the selection behaviour to prevent unselection of groups. This might be a regression that should be addressed.

**Comment by mstarke** [comment]
Fixed in 05d4381045141c07456242382b2f2310076901d8
