### ISSUE TITLE
TOTP code displayed only if secret length is multiple of 8

### ISSUE THREAD

**Issue by yix** [MacPass/MacPass#1155]
TOTP field displays TOTP code only if secret length in the otp URL has length of multiples of 8. For example I have secret of length 26 for which code is not displayed, but if I remove 2 or add 6 characters to the secret in the URL code is displayed.

Steps to reproduce the behaviour:
1. Create new entry
2. Create new custom field called otp
3. Put following url into the field: otpauth://totp/MacPass:mac@pass.com?secret=MACPASSMACPASS123&issuer=MacPass
4. Move focus to another field to activate TOTP - it will be empty
5. Copy following string into otp field: otpauth://totp/MacPass:mac@pass.com?secret=MACPASSMACPASS12&issuer=MacPass
6. Move focus to another field and see TOTP code displayed

MacPass is expected to show TOTP code despite of the key length

Version information:
 - macOS: 11.2.1
 - Version Version 0.8-beta (20210115120112-continuous)

**Comment by mstarke** [comment]
The secret in the otp url is base32 encoded. If you supply an invalid coding this will not work. Base32 required multiples of 8 in the length which results in the observed behavior.

**Comment by mstarke** [comment]
Though padding seems to be not needed as specified in the key uri documentation. This might need some changes in KeePassKit to accept arbitrary length on encoded values.

**Comment by mstarke** [comment]
If you use the KeePass compatible field (```TimeOtp-Secret```, ```TimeOtp-Secret-Hex```, ```TimeOtp-Secret-Base32``` and ```TimeOtp-Secret-Base64```) you are able to input UTF8 secrets and any lenght is supported. If you do not want to change any default parameters (hash, length, time period, etc) you can simply use this single field. You can refer to the KeePass documentation for details on this (https://keepass.info/help/base/placeholders.html#otp)

**Comment by mstarke** [comment]
The standard allows for the omission of padding. I did change KeePassKit to account for that. But your example `MACPASSMACPASS12` is still using characters (1) outside the base32 range making it unusable.

**Comment by yix** [comment]
I used that key just to demonstrate problem with the key length. Thanks for sorting it out!

**Comment by mstarke** [comment]
The current master should handle non-padded secrets correctly.
