### ISSUE TITLE
Can not execute a second search

### ISSUE THREAD

**Issue by davidmpaz** [MacPass/MacPass#1156]
**Describe the bug**
Hi, thanks for this project.

After searching for an entry. Search box ist disabled and can not search anymore.

**To Reproduce**
1. Open MacPass new
2. Click on the search box and enter a search criteria
3. Copy found password
4. Search box is not usable anymore

**Expected behavior**
The search box remain enable in order to execute more searches without reinitiating the application

**Screenshots**

**Desktop (please complete the following information):**
 - macOS: BigSur 11.1 (20C69)
 - Version 0.7.12 (23610)

thanks in advance,
David

**Comment by CalumSemple** [comment]
Me too macOS: BigSur 11.2.2 , MacPass Version 0.7.12 (23610)
Despite setting up on a newly erased and clean installed OS

**Comment by underthecocotree** [comment]
Press `⌘+F` a few times more.  For me it seems to work after the 4th or 5th time.

**Comment by FlexIDK** [comment]
Need add permission on Settings -> Accessibility

**Comment by fenma** [comment]
Me  too. Only 1 search is possible. After that i must restart MacPass to make second search.

**Comment by fenma** [comment]
> Need add permission on Settings -> Accessibility

What doe you mean? Would you please be more specific.
In macOS "System Preferences > Accessibility" i don't see any permission for MacPass

**Comment by FlexIDK** [comment]
[screenshot](https://s.flipflip.ru/f/0I8B0_8_1570AABL_2021-03-13_21-21-06.png)

**Comment by mstarke** [comment]
As stated on macpassapp.org and in various issue on GitHub. 0.7.x does not behave well under Big Sur. If you can, use the lates development snapshot, which has fixed this issue. If TOTP is fully implemented I will release 0.8 to fix this for all users. Sorry for the long delay on the update but time currently is rather limited.

**Comment by mstarke** [comment]
Duplicate or #1113 3
