### ISSUE TITLE
Header locked after copying any field macOS Big Sur 11.2.3

### ISSUE THREAD

**Issue by mdtanrikulu** [MacPass/MacPass#1160]
**Describe the bug**
When I unlock my MacPass and copy any field by double clicking, the header of the application gets locked. I am then not able to write anything into "Search everywhere" input, not able to press "Lock Database" button, just "Action" button is enabled. The only way locking DB is then closing application and opening again to be sure if DB is locked.

**To Reproduce**
1. Open MacPass
2. Unlock the DB
3. Copy any field of any entry (password, username, url etc.) by double click.
4. Observe the header of the application. It must be locked as like it is locked when DB itself is locked.

**Expected behavior**
Header should remain unlocked until I lock the DB

**Screenshots**
Before copying any field;
<img width="1338" alt="112138653-12383a80-8bd2-11eb-9ae5-f4410eb24cc0" src="https://user-images.githubusercontent.com/2774845/112139192-c6d25c00-8bd2-11eb-86d8-20ff096373f1.png">

After copying;
<img width="1338" alt="112138718-24b27400-8bd2-11eb-8c23-3e9050386e88" src="https://user-images.githubusercontent.com/2774845/112139196-c89c1f80-8bd2-11eb-94aa-212a17fa516b.png">

**Desktop (please complete the following information):**
 - macOS: BigSur 11.2.3
 - Version 0.7.12

**Comment by ghmer** [comment]
as a workaround, you can actually press "command+F" to trigger the search. This will unlock the header again.

**Comment by david6983** [comment]
I Have the same issue with macpass 0.7.12 on Big Sur 11.2.3

**Comment by mdtanrikulu** [comment]
> as a workaround, you can actually press "command+F" to trigger the search. This will unlock the header again.

Thanks, I can confirm the header unlocks. It surely creates an opportunity to lock the db. :) However if I select an entry instead (without even copying), header gets locked again.

**Comment by ghmer** [comment]
> > as a workaround, you can actually press "command+F" to trigger the search. This will unlock the header again.
> 
> Thanks, I can confirm the header unlocks. It surely creates an opportunity to lock the db. :) However if I select an entry instead (without even copying), header gets locked again.

Yes, it is not a permanent solution, but rather a workaround that at least enables me to use MacPass at the moment without restarting it everytime after I copied a value :-)

**Comment by georgesnow** [comment]
This is a interesting bug, I haven't encountered this issue. Although I use my plug-in which  specifically forces the focus in search box. So it must be the equivalent of triggering the cmd+f twice.

**Comment by aliok** [comment]
I can tell the toolbar (which contains the search input) acts strange. Things look "disabled", can't click on anywhere. The focus gets on that input after 4-5 times of doing Cmd+F.

I am on Big Sur with Macpass 0.7.12.

**Comment by jamb-statue** [comment]
Same problem here. MacBook Air with M1 chip, Mac OS 11.2.3 (20D91), Macpass 0.7.12

**Comment by brightzheng100** [comment]
Same issue here with MacBook Pro + MacPass Version 0.7.12 (23610)

**Comment by LunaticoCR** [comment]
Same here. Copy/paste of username/password from keyboard is also disabled, unless I go to the actions menu or do the cmd+f workaround mentioned here. Major usability bug.

**Comment by georgesnow** [comment]
Just a note 0.7.12 isn’t recommended on Big Sur. The continuous build does work without this issue.

**Comment by mstarke** [comment]
Please use the continous build (https://github.com/MacPass/MacPass/releases/tag/continuous) until 0.8. will be release by the end of may.

**Comment by r3ggi** [comment]
BUMPing :-)

**Comment by error401de** [comment]
Is there any update regarding the release of 0.8?

**Comment by artbazil** [comment]
Same here after updating from Catalina to BigSur 11.4 (20F71) - MacPass version 0.7.12 (23610)

**Comment by thwentythree** [comment]
Any solution for this other than command+F? Thanks very much.

**Comment by nikduvall** [comment]
> Same here. Copy/paste of username/password from keyboard is also disabled, unless I go to the actions menu or do the cmd+f workaround mentioned here. Major usability bug.

WORKAROUND: Hot-keys and RIght-click menu on key still works.

**Comment by ghmer** [comment]
> Please use the continous build (https://github.com/MacPass/MacPass/releases/tag/continuous) until 0.8. will be release by the end of may.

Can't you just use one of your continuous builds and release that as 0.8? I got Macpass via brew, waiting for this update for months(!) and cannot see why it is taking so long to release the update?!?

**Comment by mstarke** [comment]
Fixed in current master. Will get pushed out with 0.8
