### ISSUE TITLE
Wide entries in single line fields jump/break on word boundaries instead of scrolling

### ISSUE THREAD

**Issue by timkite** [MacPass/MacPass#1161]
**Describe the bug**
When a field entry for a password item is too wide for the field, MacPass breaks on word boundaries rather than scrolling with the cursor.

**To Reproduce**
1. Create or edit a password item
2. Add text to a single line field like Title, Username, Password, or URL that is longer than the displayed field width
3. When the cursor hits the end of the field and you continue adding text (or, with an existing long entry, use the right arrow key to continue further along the entry), note how the entry's display "jumps", as if it's going to the next line in a document with line breaks added at word boundaries.

**Expected behavior**
Entry should "flow" or "scroll" with cursor continuously when it's too wide for the field to display it like any other single line field.

**Screenshots**
Attached a movie showing the behavior in MacPass.

https://user-images.githubusercontent.com/6933976/116742265-21768900-a9c5-11eb-9615-eeaba597d4ce.mov

Also attached a movie showing what I believe is the correct behavior (showing 1Password).

https://user-images.githubusercontent.com/6933976/116742284-28050080-a9c5-11eb-84b4-ccd14e5a8a97.mov

**Desktop (please complete the following information):**
 - macOS: 11.3 (20E232) on an M1 MacBook Air
 - Version 0.8-beta (20210115120112-continuous)
 - Also happens with a build from current source 2021-04-30 @ 14:47 EDT, though that version is missing the "key" glyph that's the default glyph for password items.

**Additional context**
I swear previous versions of MacPass scrolled single line fields like 1Password does and this word breaking behavior is new (hard to test this since I'm on an M1 Mac now), but if this behavior is intentional then I suppose this should be a feature request for a toggle to bring back the scrolling behavior.

**Comment by mstarke** [comment]
This is a regression in HNHUI that does not correctly restore the scrolling/wrapping behaviour on NSTextFields. This is fixed in 0.8 which uses a version of HNHUI that fixes the issue.
