### ISSUE TITLE
Master key file format 2.0 is not accepted. The error is: the password and/or keyfile is wrong (1017)

### ISSUE THREAD

**Issue by pinjaliina** [MacPass/MacPass#1164]
I have a KeePass database that I just moved from Windows to Mac. It uses both key file and password as its master key.

However, I could not open the DB with MacPass. I kept getting a message that said that ```The password and/or keyfile is wrong (1017)```. But both of them were correct.

When I changed the master key on Windows to use a key file in the older 1.0 format and moved the DB back to the Mac, I was able to open the DB again.

**Comment by mstarke** [comment]
The new key format is already supported by KeePassKit and will be working in 0.8
