### ISSUE TITLE
Top Bar

### ISSUE THREAD

**Issue by W1ndowsGuy** [MacPass/MacPass#1168]
On Mac OS catalina, once you click on an entry in database you can no longer use search menu or icons on the top bar, it just greys them out even if you click back on them.

**Comment by the-docta** [comment]
Use Cmd-F as workaround. (after pressing Cmd-F the toolbar becomes accessible again)

dublicate to #1160 and #1163

**Comment by mstarke** [comment]
@W1ndowsGuy Is this issue present on Catalina 10.15 or Big Sur (11.0)? 10.15 should work properly. What version of MacPass are you using?

**Comment by CaptainApollo** [comment]
@mstarke This issue present on Big Sur (11.4). MacPass version is 0.7.12 (23610).

**Comment by geyuqiu** [comment]
any updates? as it is working on catalina ...

**Comment by thwentythree** [comment]
Any solution for this other than the command-F combo? Thanks very much!

**Comment by mstarke** [comment]
Closing due to being a duplicate
