### ISSUE TITLE
Reopen last Database(s) after Launch

### ISSUE THREAD

**Issue by mbrucco** [MacPass/MacPass#1171]
At the moment it opens last one that was active previously.

I work using two databases, I'll love if it is possible to open both automatically on startup.

A quick (?!?!) solution may be to store list of open database when quit occurs, and open all of them when app starts again.

A more flexible, but I can't evaluate effort and beneficts, is to mark databases that user wants to open at startup; it may be available a list to fill with databases paths and  names.

Thanks in advance!!!

Maurizio

**Comment by mstarke** [comment]
If you enable state restoration (that is, disable close all windows when quitting) you get the re-opening for free with more than one database.

**Comment by mstarke** [comment]
I'm reluctant to implement something that is a subset of a system functionality. I know people use different settings (e.g. no state restoration) but keeping both ways working properly is not the easiest job.

**Comment by mbrucco** [comment]
You are right. I discovered the Mac OS functionality just now.

So, practically there is no reason to have it redundant, considering the effort required to implement it.

Thanks for your help
BR
Maurizio

**Comment by mstarke** [comment]
I'm closing this issue since the feature request is not being implemented. If the current implementation is broke in some way, a new issue should be created.
