### ISSUE TITLE
Cannot save to external volumes on macOS 11.5

### ISSUE THREAD

**Issue by G4nda1f** [MacPass/MacPass#1174]
**Describe the bug**
I just upgraded to macOS 11.5.  I've loaded the MacPass database save file (.kdbx) from a USB flash drive into MacPass for years and saving the database onto the flash drive has always worked in the past, as far back as I've been using Macs (macOS - Yosemite 10.10).  But today I received the following error when attempting to save:

![image](https://user-images.githubusercontent.com/25068692/126680605-50d75585-6ea9-43c3-8b3a-518f003188b0.png)

I have 2 Mac systems and this error just started occurring on both systems.  Both started exhibiting this error right after being upgraded to 11.5.

**To Reproduce**
1. Load database file from an external USB drive
2. Attempt to save the database in MacPass (cmd + s)
3. The error should pop up

**Desktop (please complete the following information):**
 - macOS: 11.5
 - MacPass version: 0.7.12 (23610)

**Additional Information**
Incidentally, MacPass shows as having access to removable volumes in System Preferences > Security & Privacy > Privacy:

![image](https://user-images.githubusercontent.com/25068692/126687404-109d6444-2cd5-4317-aba2-adf65a56ceca.png)

**UPDATE/RESOLUTION**
What resolved this issue for me was to recreate my MacPass database file by essentially exporting the records from the old file and importing them into the new file.

**Comment by lastsamurai26** [comment]
Can you try using a symlink? Maybe that will work. I don't store my database on a USB stick, but I do store it externally.

**Comment by G4nda1f** [comment]
> Can you try using a symlink? Maybe that will work. I don't store my database on a USB stick, but I do store it externally.

Was able to create the symbolic link.  But when attempting to open that symbolic link in MacPass, it opens the file as if it's opening the file on the USB drive.  So the saving effect is the same and the same error occurs.

**Comment by mstarke** [comment]
Does the issue also appear when using the continuous build? I did try to recreate this some time ago and had no issues. But since this comes up with 11.5 there might be some regressions. I have to investigate this. Sorry for the inconvenience.

**Comment by lastsamurai26** [comment]
My constellation
- Macpass database is on a USB stick 
- I have created a symlink from /vol/usbstick to /vol/Mac/user/name/stick.
- I opened the database from this folder (Symlink)

Strangely enough I do not get an error :(

**Comment by G4nda1f** [comment]
> Does the issue also appear when using the continuous build? I did try to recreate this some time ago and had no issues. But since this comes up with 11.5 there might be some regressions. I have to investigate this. Sorry for the inconvenience.

As yet, I have not tried the continuous build (though as part of troubleshooting, I'll try that and let you know).  I've only used the latest release build thus far (0.7.12).

This setup has worked without issue on 3 Macs since macOS 10.10 and all versions from then till now.  This issue has only appeared with 11.15.  To test that this isn't an issue with my specific machine/install and to rule out corruption of the MacPass database file, I put it on the local drive of my Mac and opened it from there.  This issue did not occur but was able to save normally without error.  So I would think that would rule out OS corruption as well as MacPass database file corruption.  Additionally, since this is occurring on multiple Macs I would think it unlikely to be a hardware issue with the Macs themselves.  I'll have to try this with a different USB stick to see if that might be an aspect of this issue (though I must say, that the USB sticks I have been using have worked fine this entire time since macOS 10.10).  I suppose it is possible that this USB stick has run out of writes it can sustain so trying a different one should answer that question (and I find it amazingly coincidental that this should happen exactly when I upgrade to macOS 11.5 and not a second before).  I do switch between a few USB sticks to help spread out the wear on the USB sticks but I suppose it is possible this current one has reached its limit.

**Comment by oehm-smith** [comment]
What about opening and saving a text file in TextEdit that is on the same (and then a different) USB stick?

**Comment by G4nda1f** [comment]
OK, so after further testing (with 0.7.12 only) here's the results:

I use 3 MacPass database files.  One I use all the time which contains current passwords, one archive of old passwords which I almost never open, and one other miscellaneous file which I almost never open either.  My current password database file is 263KB, the old archive file is 157KB, and the miscellaneous is 2KB.  Trying to save changes to the miscellaneous file works without any error.  But trying to save changes to the other two (current & archive) results in the same error.  Creating a new database file on the USB stick, works fine.  As does making new entries in this new file and saving them.  No errors occur.

Trying to save changes on another USB stick resulted in the same error (on the current database file).  Creating a new database file on this other USB stick also works fine as does creating new entries in that file and saving the changes.

So this seems to point to the files themselves.  But since I have almost never used the archive since it was initially created, I have a hard time believing it is due to any file corruption or fragmentation (at least for the archive file).  But in an effort to try to address these potential issues, I opened this in KeePass 2 on my Windows system.  Using the database tools in KeePass, this resulted in file size reductions as follows:  The current file went from 263KB to 124KB and the archive file went from 157KB to 70KB.  Unfortunately, this made no difference.  Attempting to save changes in both the current and archive files still results in an error.  But creating a new file for the current passwords and copying everything into the new file results in an additional size reduction from 124KB to 105KB.  Trying to save changes to this new file works fine with no errors.  Same basic effect for the archive file which reduced from 70KB to 60KB and saving changes works without errors.

So it appears this ultimately has something to do with the files.  But a file that is heavily used and has had many saves with perhaps some fragmentation does not seem to be the issue, since the archive file is almost completely unused.  And it seems strange that if file corruption or fragmentation or other file related issues were in play, why would the current file work just fine on a local drive?

Incidentally, I tried copying a mp3 file to my USB sticks and it copied just fine so it doesn't appear to be anything to do with reaching the write limit on the USB stick either.

Michael, this does appear to be me calling out a false alarm on effects that started happening coincidentally when upgrading to 11.5.  I've tried to do my best outlining everything and it all seems to point to something relating to my database file.  But if you have a better idea what this is than my guesses, hopefully this might be helpful information for you.

**Comment by G4nda1f** [comment]
> What about opening and saving a text file in TextEdit that is on the same (and then a different) USB stick?

I did try copying an mp3 file to the USB stick and it copied the file correctly.  So I don't think it is an issue of running out of writes on the USB stick.  Trying to create a new text file and putting in some text in that file, the saving it.  That works fine too.

**Comment by G4nda1f** [comment]
> My constellation
> 
> * Macpass database is on a USB stick
> * I have created a symlink from /vol/usbstick to /vol/Mac/user/name/stick.
> * I opened the database from this folder (Symlink)
> 
> Strangely enough I do not get an error :(

I have a feeling this is specific to my database files.  Given my very long response, I think this is the most likely issue.  Recreating the files and copying the contents of the old files into the new files seems to fix the issue.

**Comment by oehm-smith** [comment]
What about Exporting a new copy from MacPass and then importing - perhaps it is something funny going on in the current file(s).

**Comment by G4nda1f** [comment]
> What about Exporting a new copy from MacPass and then importing - perhaps it is something funny going on in the current file(s).

Yes.  That is essentially what I did.  This resolved the issue.

**Comment by G4nda1f** [comment]
Michael, this issue appears to be resolved for me.  I can close this as a case, but this might be an issue for other people who have older database files of reasonably significant size and who upgrade to 11.5.  But then again, perhaps this won't be much of an issue for others since perhaps not that many run their password database from USB sticks...

**Comment by mstarke** [comment]
@G4nda1f I would close the issue and hope we can point others with the same issue to this one. Glad it could be solved with a simple file copy. My suspicion is a long read/write because of the file being split into too many blocks but this is just an uneducated guess.

**Comment by G4nda1f** [comment]
> @G4nda1f I would close the issue and hope we can point others with the same issue to this one. Glad it could be solved with a simple file copy. My suspicion is a long read/write because of the file being split into too many blocks but this is just an uneducated guess.

OK.  I've updated the initial entry to include a short note on what fixed this issue for me.  As for what is actually going on, for most of us it's like a black box and we can only guess at what is going on under the sheets and how OS changes affect this.

**Comment by mstarke** [comment]
Thank you again for the detailed description and your work on elaborating the circumstances!
