### ISSUE TITLE
Keepass database with Key file version 2

### ISSUE THREAD

**Issue by lastsamurai26** [MacPass/MacPass#1175]
**Describe the bug**
Currently I don't know which Keepass version the key file version 2 came with, but at the moment it looks like Macpass can't handle a database that has an encryption stored with a key file version 2. 

You always get a message that the password or keyfile is wrong.
**To Reproduce**
1. create a new database 
2. use key file version 2 
3. save database 
4 Open in Macpass 

**Expected behavior**
-

**Screenshots**
-

**Desktop (please complete the following information):**
 - macOS: 11.5
 - Version 0.7.12

**Additional context**
-

**Comment by mstarke** [comment]
I’m updating KeePassKit to support XMLv2 keys as well as the changes with KDBX 4.1. support for the new keys is already done. Most of the changes for KDBX 4.1 are also far along the road. The upcoming 0.8 release will include all those new features of KeePassKit.

**Comment by mstarke** [comment]
Loading works. The UI needs some changes to allow for creating new XMLv2 key files

**Comment by lastsamurai26** [comment]
That sounds good :-) 
When will it officially come? Do you already have a plan?

**Comment by mstarke** [comment]
UI changes have been postponed. New issue is #1187 for this. MacPass will generate v2 XML keys for every KDBX 4.1 dabases and v1 XML keys for everything below KDBX 4.1. KDB files will yield a binary key file.
