### ISSUE TITLE
CMD-Z in notes reverts previous changes in other fields only -> invisible data "loss"

### ISSUE THREAD

**Issue by DominusExult** [MacPass/MacPass#1180]
When you edit an entry, for example username or password and then change a Notes field in this entry or any other entry, CMD-Z will not revert the Notes field but instead revert the other entries.

This had almost lost me a couple of passwords I had changed a moment before editing a Notes field :(

Possibly related to #724

1. Change the username in entry *foo*
2. go to entry *bar* and edit the Notes field
3. hit CMD-Z
4. You will remain on the Notes field of *bar* you edited but the username of *foo* gets reverted

**Expected behavior**
The Notes edit should be reverted on first CMD-Z, if you press it again the username of *foo* should be changed and the focus should switch to the entry *foo* and to the username field.

**Desktop (please complete the following information):**
 - macOS: 11.6
 - Version 0.8-beta (20210826080826-continuous)

**Additional context**
Attached is a very simple test database with the password test
[test.kdbx.zip](https://github.com/MacPass/MacPass/files/7176995/test.kdbx.zip)

**Comment by mstarke** [comment]
There where some changes in the undo-behaviour on notes field which might have lead to this regression.
