### ISSUE TITLE
MacPass Keyfile will not open: format is not valid

### ISSUE THREAD

**Issue by ScoobyDoobieDoo** [MacPass/MacPass#1181]
**Describe the bug**
When selecting the keyfile, a pop-up window says that the file is in the wrong format "impossible to open ....key for the moment - the format is not valid"

**Expected behavior**
You should be able to select the key file (.key format) to open the database.

**Screenshots**
![image](https://user-images.githubusercontent.com/90952621/133878377-390b3682-da4a-4b94-be78-48e06720887f.png)

**Desktop (please complete the following information):**
 - macOS Big Sur 
 - Version 11.5.1
MacPass Version 0.7.12 (23610)

**Additional context**
Worked fine in the beginning.

**Comment by mstarke** [comment]
The .key file is not your password database but a file based key. Your database should have the ending KDBX or KDB. If you double click the .key file macOS thinks it’s a keynote file and Keynote tells you the file is not keynote file.

**Comment by ScoobyDoobieDoo** [comment]
I do know it is not my database. I secured my password database by a password and a keyfile. So when you log in, you need to put in your password and then select the key file. When I select the key file it states that it is not a valid format.
The result is that I cannot open my password database. In the beginning it worked fine.

**Comment by mstarke** [comment]
Ok. Sorry for the wrong idea. But the screenshot lead me to think that way. This should only happen if you have changed anything on the keyfile. Can you take a look at it? It’s an XML

**Comment by ScoobyDoobieDoo** [comment]
Oké. It's on a friend's computer. I will take over the screen and have a look.

**Comment by ScoobyDoobieDoo** [comment]
My friend came over with her computer. 
Sorry to have wasted your time, because she tried to open the key-file outside of the opening window, instead of clicking on the two arrows to select it from the program. So off course she got this message saying that the format was not valid.
I did make her an extensive manual with screenshots, but still ....
Thanks again for replying to my question and sorry again !

**Comment by mstarke** [comment]
No problem at all. This happes and should actually be considered a "bug" in MacPass as it does not make the workflow clear.
