### ISSUE TITLE
AutoType button disabled after upgrade to Big Sur

### ISSUE THREAD

**Issue by alevine** [MacPass/MacPass#1183]
**Describe the bug**

It seems like my AutoType option has been permanently disabled after updating to Big Sur. MacPass still has accessibility permissions enabled, am I missing another set of permissions for AutoType to function?

**To Reproduce**
1. Open database
2. Try to autotype a login, but the button is disabled

**Expected behavior**
AutoType worked fine before updating, it would be great if the button could work again!

**Screenshots**

![Screen Shot 2021-09-22 at 1 05 19 PM](https://user-images.githubusercontent.com/25009683/134389639-8f846a1a-cbf6-4959-8958-c0d71f8bc6f7.png)

**Desktop (please complete the following information):**
 - macOS: 11.6
 - Version: 0.7.12

**Comment by nikduvall** [comment]
Found the following workarounds:

1.  Right-click the key and select **Perform Auto-Type**
2. Use the Hot-key for **Perform Auto-Type**

**Comment by alevine** [comment]
Thanks @nikduvall unfortunately neither seem to work for me. Would you mind telling me what permissions you have granted MacPass under Security & Privacy?

**Comment by mstarke** [comment]
The upcomming 0.8 release should fix this.

**Comment by mstarke** [comment]
Fixed in master
