### ISSUE TITLE
Can't get into database on new install on new laptop

### ISSUE THREAD

**Issue by san3000** [MacPass/MacPass#1184]
Hi, I used macpass on my previous laptop. I did a new install on my new laptop and everything seems to be fine, except I don't get the loging option when opening my existing database file.

**Comment by mstarke** [comment]
Hi, since you closed the issue already, could  you elaborate what you did to fix it?

**Comment by san3000** [comment]
I restarted my laptop a second time. Classic it helpdesk solution 🤣
