### ISSUE TITLE
Toolbar options are greyed out after selecting any entry or group name

### ISSUE THREAD

**Issue by manusharma9799** [MacPass/MacPass#1188]
**Describe the bug**
Toolbar options are greyed out after selecting any entry or group name and it does not come live again if we click on toolbar

**To Reproduce**
1. Login to Database
2. you will notice that toolbar is active and able to use the options on toolbar
3. click on any entry or group; 
4. the entry or group becomes active section of application now
5. the toolbar has become as inactive section of application now, options on toolbar are greyed-out
6. no matter how many times i try to click on search box it does not respond
7. next i use command + F shortcut to search and this is alive again.
8. also while it was inactive; I touched the search icon on touch-bar and although it did not go for searching but toolbar options became active.

The key is; toolbar does not become active again if we click on toolbar; however it becomes inactive if we click on any entry / group / inspector section of the application.

**Expected behavior**
1. It is expected to get the toolbar icons / buttons active and responsive once clicked
2. Touch-bar "Search" shortcut expected to take me to search box on toolbar  

**Screenshots**
Screenshot 1 : Toolbar active when application launched:
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/94051898/141107742-16b0e62a-1d3d-4b75-91ed-7163946279ea.png">

Screenshot 2 : toolbar inactive once selecting the group name.
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/94051898/141107867-3108a5ed-5a65-4269-8c79-f971304cc757.png">

**Desktop (please complete the following information):**
 - macOS: Monterey
 - Version 12.0.1
 - MacBook Pro 13"

**Additional context**

**Comment by mstarke** [comment]
This is already fixed in master and will get published with 0.8
