### ISSUE TITLE
MacPass won't open any files anymore

### ISSUE THREAD

**Issue by swisspete** [MacPass/MacPass#1191]
**Describe the bug**
I installed MacPass yesterday, and opened my password files with no issues. This morning, I accessed it again. Then, I updated the file on another machine, took the new file and tried to open it in macpass. It says password or keyfile is wrong (1017).

Then I saved my file on the other machine as a kdb (1.0 version) and tried again. Won't work. I can open it fine on the other machine, but not here. 

There is nothing wrong with the file, and the password is correct. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - macOS: [e.g. 10.12.1]
 - Version [e.g. 0.7.3]

**Additional context**

**Comment by mstarke** [comment]
Are you sure you use the KDB format? Did you have anything set as a custom encryption for the file? Do you use key files and password or both? If so, did you check if you use an empty password or no password at all?

**Comment by swisspete** [comment]
Hello, thank you for your reply. I meant to update the issue, because it
seems that somehow this file got corrupted. I could not open either on my
older computer. So something happened but I don't quite know what it is. So
I'm afraid I cannot provide more information. I found a backup of the file
and been using that since, with no issues. So my problem is resolved, and
if it happens again and I have more information as to what is going on,
I'll submit it.$

Have a great day,
Pete.

**Comment by inter-faced** [comment]
I had the same issue when i selected the database when selecting a kdbx keyfile opening the file. 

When i close Macpass and type my password without selecting "Keyfile Choose...", I can open the kdbx keyfile without issues.

**Comment by mstarke** [comment]
@inter-faced This is a known usage error which will now be prevented by MacPass displaying appropriate error messages.

**Comment by jhiems** [comment]
I'm having the same issue. I installed MacPass using brew install macpass (which installed version 0.7.12) and cannot open my database.kdbx with its corresponding database.keyx file. I verified that the file can be opened on other devices and that my password is being entered correctly. I tried @inter-faced's suggestion of force closing MacPass and not selecting "Keyfile Choose...", but this is still giving me the "The password and/or keyfile is wrong (1017)" error. What's the fix for this?

**Comment by mstarke** [comment]
Can you take a look inside the .keyx file and see what version the file uses? If it’s 2.0 you have to use the continuous build since 0.7.12 can only open version 1.0 of the key file format.

**Comment by jhiems** [comment]
It is version 2.0. Is support for newer key files planned in a future release?

**Comment by mstarke** [comment]
2.0 support ist working and will get released with 0.8
