### ISSUE TITLE
Duplicated "Duplicate Entry" Entry

### ISSUE THREAD

**Issue by ollyfg** [MacPass/MacPass#1193]
Dear me that's a terrible title...

**Describe the bug**
There are two "Duplicate Entry" items in the right-click menu

**To Reproduce**
1. Open MacPass and unlock a DB
2. Right click anywhere on the tree-style explorer or the list of entries
3. There are two "Duplicate Entry" items, one has an ellipsis

**Expected behavior**
There should just be one entry, unless this is an in-joke or something.

**Screenshots**
<img width="390" alt="Screen Shot 2021-11-24 at 2 43 29 PM" src="https://user-images.githubusercontent.com/8495389/143157085-36262c8b-0c5d-4d1d-bc6e-2e82fd3b2b2e.png">

**Desktop (please complete the following information):**
 - macOS: 12.0.1
 - Version 0.7.12

**Additional context**
It's taken me years to actually notice this, so definitely low priority.
Also this may have been fixed on more recent versions, looks like there might be a `0.8` build out that the update-checker hasn't told me about.

**Comment by mstarke** [comment]
That’s as intended. The first one is to duplicate with default options and the second one to specify what should be done with the copy.

**Comment by ollyfg** [comment]
Ah, I see! Slightly confusing but fair enough!
