### ISSUE TITLE
Top panel including search function greys out (locks) and is no longer available after SEARCH function is used once

### ISSUE THREAD

**Issue by Natedi** [MacPass/MacPass#1195]
**Describe the bug**
Main issues (UPDATED): 
1. The "Search" function gets locked after its use.
2. The top panel (including Search box) gets locked if any of the entry folders in the left panel are clicked on.

Details:
Installed MacPass today, opened my old .kdbx file (it is big) with pass and key file, can see and browse everything fine.
BUT, after I used the search function AND (!!!) clicked on one of the displayed entries to look at it, the entire top panel gets greyed out and all functions are no longer available (except "Action").
The top panel looks the same (greyed out) as when the database is locked and one needs to input credentials. This makes me think that there is some sort of partial locking going on after the "search" function is used.

UPDATE:
As I was playing around, I discovered that the same kind of locking happens even if I click on any of the folders (groups) in the left panel. I added a screenshot of how things look with the new test database.
<img width="972" alt="MacPassError2" src="https://user-images.githubusercontent.com/77253394/144728877-f9257868-513f-4e64-a7d8-062439338347.png">

Temporary Solution:
To overcome this, one needs to either quit and reload the app or "lock" the database from the top Mac menu and then reenter credentials to unlock.

**To Reproduce**

**Expected behavior**

The "search" function is expected to be available.
While some other functions which are locked (per this issue) are redundant and can be found in the top Mac menu or under "Action", the "search" function gets locked for the entire session.

**Screenshots**

**My Desktop :**
 - macOS Monterey
 - Version 12.0.1
 - MacBook Pro (Retina, 15-inch, Mid 2015)
 - Processor 2.8 GHz Quad-Core Intel Core i7
 - Memory 16 GB 1600 MHz DDR3
 - Graphics Intel Iris Pro 1536 MB

**Additional context**

1. I also tried to create a brand new database with a password and newly generated key file, but see ALL of the exact same issues as described above. So, the issue is not related to my old database file.

3. If it matters (or should create another issue report?), I also cannot run the software update. Getting the error: "...can't run the update from the location is was downloaded to, move to applications folder..." I did run the app from within the application folder!
<img width="272" alt="MacPassError" src="https://user-images.githubusercontent.com/77253394/144728515-7c8c767b-ff80-41a6-bd44-af39d5c54e26.png">

**Comment by artful88533** [comment]
The same issue, after update macOS to the Monterey

**Comment by Natedi** [comment]
> The same issue, after updating macOS to the Monterey
Seems like it makes the issue being an "official" bug.
How about updating? Can you update?

**Comment by socialmedialabs** [comment]
Grab the continuous release, this fixes the issue. However you won't be on the official update chanel anymore since it is a 0.8 beta: https://github.com/MacPass/MacPass/releases/tag/continuous

See the heads up box on https://macpassapp.org/ for reference.

**Comment by mstarke** [comment]
Issue is known and fixed in continous.
