### ISSUE TITLE
"Continuous" release is very old: Travis is broken

### ISSUE THREAD

**Issue by idbrii** [MacPass/MacPass#1196]
**Describe the bug**

The [continuous](https://github.com/MacPass/MacPass/releases/tag/continuous) release is marked as "Latest", but it's from 2019 (older than the latest numbered release).

I think everything is fine in this repo, but someone with authority needs to setup travis on https://travis-ci.com/github/MacPass. (Looks like several projects are setup there, but not MacPass.) Travis shutdown the travis-ci.org builds ([where MacPass was setup](https://www.travis-ci.org/github/MacPass/MacPass) before):

> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

I did the .org -> .com migration for my projects awhile back and I think I just needed to log into travis-ci.com with my github account, authorize, and then add all repositories to travis. It seemed flaky and unresponsive (couldn't tell if it was successful for hours). I eventually gave up and ported most of them to github actions.

**To Reproduce**
1. Go to [releases](https://github.com/MacPass/MacPass/releases/)
2. See "Continuous" is old

**Comment by gcruchon** [comment]
I'm not sure this repo is maintained... Watch the last PR #1144 ...

**Comment by mstarke** [comment]
Since GitHub actions seem to do everything that MacPass requires for releases I did start the migration but got stuck at the actual release step. Build works fine so this last part needs some work. I am about to release 0.8 so the continuous build is superseded and the official release will be up to date again.

**Comment by mstarke** [comment]
I‘ve updated the action and it now pushed to the continuous release. I‘m going to retire the travis setup.
