### ISSUE TITLE
[Question] Is there any new ETA for 0.8 stable release?

### ISSUE THREAD

**Issue by emikaadeo-git** [MacPass/MacPass#1198]
@mstarke 
firstly, Thank you for your great work!

Looking forward for a new stable release (v0.8) cause it will have a lot of fixes for Big Sur/Monterey.
Is there any new ETA for this release?
(PS. I'm aware that there's a continuous build which I'm using right now)

**Comment by omaksi** [comment]
Hi @mstarke, any updates on this? I've seen there's a new continuous build, but it's not marked as 8.0, is there anything missing?

**Comment by mstarke** [comment]
Yesterday 😆
