### ISSUE TITLE
Password field not scrollable

### ISSUE THREAD

**Issue by drawcard** [MacPass/MacPass#1210]
When trying to select text, the password field is not able to scroll to the right, to reveal the full password. Arrow keys don't work either. May be related to #1208 

Try to select or use arrow keys to view full contents of the password field:
https://user-images.githubusercontent.com/1435638/153802508-c25cf7a5-6f30-4d41-b13b-bbe0cbd04b1e.mp4

 - macOS: 10.12.1
 - Version 0.8.1

**Comment by yannbolliger** [comment]
Can confirm exactly this on:

- macOS 11.6.4
- 0.8.1 (26030)

**Comment by mstarke** [comment]
Duplicate of #1208
