### ISSUE TITLE
MacPassHTTP plugin is not compatible anymore

### ISSUE THREAD

**Issue by TomaszWr** [MacPass/MacPass#1212]
**Describe the bug**
After update to new macPass version the 0.3.2 version of macpasshttp plugin doesn't load, informing it is not compatible with this version.

**To Reproduce**
1. Go to general settings, tab Plugins, browse available plugins
2. Download MacPassHTTP plugin, restart app and go back to plugins
3. Error saying that "the bundle couln't be loaded because it doens't contain a version for the current architecture"

**Expected behavior**
Receive working connection to Firefox plugin keepass connector.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/35960132/153871385-70115b36-d6c9-451b-a48b-67dc211b6041.png)

**Desktop (please complete the following information):**
 - macOS: 12.1
 - Version 0.8.1

**Comment by mstarke** [comment]
MacPassHTTP isn’t currently supplied for apple silicone. You can force MacPass into Rosetta mode by opening the info panel in the Finder and checking the “run im rosettes” checkbox to re-enable the plug-in.

**Comment by TomaszWr** [comment]
Thanks, that helped. However I was using mypass+plugin on this macbook before update without issues.
