### ISSUE TITLE
Migrate kdbx 3.x to 4.x option

### ISSUE THREAD

**Issue by georgesnow** [MacPass/MacPass#1214]
Is there an option for converting/upgrading a database to a newer version? The wiki says macpass supports 4.x. But under database settings the keepass version is a fixed text field.

**Comment by mstarke** [comment]
There is no explicit method to upgrade the database. You have to change the database accordingly to trigger the upgrade. This is currently non-trivial but will change with an upcoming release. The easiest way currently is to switch to Argon2 as the key derivation method to store the database as KDBX4.

**Comment by georgesnow** [comment]
Ah thanks!
