### ISSUE TITLE
All kdbx files stopped opening, after updating to 0.8.1 - Unknown file format (1039)

### ISSUE THREAD

**Issue by svscorp** [MacPass/MacPass#1223]
That's a really scary result after upgrading to MacOS Monterey and MacPass 0.8.1

kdbx files that used to work, are now can't be opened - Unknown file format (1039).

**Desktop (please complete the following information):**
 - macOS: Monterey 12.3 (21E230)
 - Version 0.8.1 (26030)

**Comment by svscorp** [comment]
After using File > Open > ... it worked now. Previously I tried to just use "recent files".

**Comment by mstarke** [comment]
Uh, that's a nasty experience and I have no clue why this happens. Do you store the files on any cloud storage?

**Comment by DominusExult** [comment]
I suspect that this has something to do with macOS 12 and OneDrive.
There were some news lstely that Apple does some deprecation in *something* the services OneDrive, GoogleDrive, Dropbox, etc. use. And there was also some news that OneDrive already did some changes related to that, which is not unproblematic. 
I didn't follow that closely but maybe it was implemented around the same time that MacPass updated and it's *just* bad timing and not really MacPass' fault.

For the record, I use the latest MacPass, latest macOS 12 with my keepass database synced via Nextcloud and do not have this problem.

**Comment by AydinChavez** [comment]
I am having the same issue. Using MacPass 0.8.1 for the first time and am getting the 1039 error all the time when trying to open the kdbx-file.

**Comment by mstarke** [comment]
@AydinChavez do you use one drive?

**Comment by DominusExult** [comment]
This is the One drive issue caused by MS https://www.macrumors.com/2022/02/01/onedrive-mac-users-unhappy-files-on-demand/

**Comment by AydinChavez** [comment]
In my case error message was correct (see above), pls ignore. Thanks for your support.

**Comment by Guilhaudis** [comment]
J'utilise MacPass 0.8.1 sur un mac Os Monterey (V12.2.1) et j'obtiens l'erreur 1039 lorsque j'essaie d'ouvrir le fichier kdbx (format de fichier inconnu). Pouvez-vous me dire comment je peux faire pour régler le pb ? merci

**Comment by k3n** [comment]
Same issue (1039) also caused by the changes to OneDrive. I went into OneDrive, found my .kdbx, and chose "Always keep on this device", which I think caused it to re-sync since there was some OneDrive activity. Now MacPass works again.

**Comment by morihaya** [comment]
Thanks @ksn your info saved me from having the same problem.
MacPass v0.8.1, macOS Ventura 13.6.
