### ISSUE TITLE
Add 'Custom Field' feature

### ISSUE THREAD

**Issue by schusz** [MacPass/MacPass#1232]
KeePass has the possibility to add custom fields to an item.
In MacPass custom fields are not visible. I would highly appreciate it if this feature could be added.

**Comment by mstarke** [comment]
Custom Fields are supported and available. They are listed below the normal field in the General tab. You can add them via the Plus Button below the tags field.

**Comment by mstarke** [comment]
No worries. And thank you for sticking with MacPass through the rough times :)
