### ISSUE TITLE
TOTP Autotype

### ISSUE THREAD

**Issue by Bergruebe** [MacPass/MacPass#1238]
It would be great to enter the TOTP-code by using auto type.

In the moment you can only autotype the otplink with `{S:otp}` (otpauth://totp/....) or only the secret, which should be used to generate the 6 digits, with `{S:TimeOtp-Secret-Base32}`. So the workflow to log in into a two-factor secured account (nearly every) isn't great, because you always need do copy the 2FA-code manually from MacPass or another 2FA Application.

The best solution in my opinion would be to have the autotype command `{S:totp}`to enter the 6- (or 8-)digits.

**Comment by mstarke** [comment]
Might I suggest to try `{TOTP}`

**Comment by Bergruebe** [comment]
**YES!** Thank you so much!
I was so sure, that this must be possible, so I tried `{S:totp}`, `{S:TimeOtp-Code}`and so on...

Sometimes the solution is easier than I think. 🤦🏼‍♂️ 

Maybe I just overlooked the information in the wiki and in the app itself. But to make it clear to everybody (including people like me 😀), it would be great if you could add this command to the `Available commands`-screen.
<img width="400" alt="screenshot of available commands in the MacPass App" src="https://user-images.githubusercontent.com/68869895/189500944-11ec3e6c-1ed6-467f-bb89-5ee2f08350cb.png">
I always tried to find it in `S:custom`.

Thank you very much again @mstarke for your fast help and thank you everybody for this great app!
