### ISSUE TITLE
UI: uncomplete or wrong sentence / german localisation

### ISSUE THREAD

**Issue by rabenweiss** [MacPass/MacPass#1241]
**Describe the bug**
    Uncomplete or wrong sentence in preference window / german localisation

**Steps to reproduce the behavior:**
1. Open preferences
2. Navigate to "workflow / Arbeitsfluss/Arbeitsablauf"
3. Uncomplete or wrong sentence at setting: "clipboard / Zwischenablage"

**Expected behavior**
    Better readable text ;-)

**Screenshots / Desktop (please complete the following information):**

- macOS: 10.12.6
- Version 0.7.12 (23610)
![Bildschirmfoto 2022-10-05 um 21 28 36 min_min](https://user-images.githubusercontent.com/11645773/194148025-75cca4f0-87d8-4258-a452-e7e8b5dc5934.jpg)

and/or

- macOS: 10.14.6
- Version 08.1 (26030)
![Bildschirmfoto 2022-10-05 um 21 59 24 min_min](https://user-images.githubusercontent.com/11645773/194157604-11058afa-a3e2-4d26-a315-5f5bcd5392e9.jpg)

**Comment by mstarke** [comment]
Nice find. 0.7.x will not get patched to fix the clipping issue and the localization. 0.8.x should include a fix for this.
