### ISSUE TITLE
Keyfile selection disappears after locking database

### ISSUE THREAD

**Issue by IvanPizhenko** [MacPass/MacPass#1247]
**Describe the bug**
When database is locked, keyfile is no longer selected, you have to select it again.

**To Reproduce**
1. Create new Keepass database that uses both password and keyfile for its protection.
2. Open that database in MacPass. You will have to select keyfile to do this.
3. Lock database.
4. Find that keyfile is no longer selected, you have to select it again.

**Expected behavior**
Keyfile still selected, so you have to only enter password to unlock database again. At least, this is what original Keepass does.

**Screenshots**

**Desktop (please complete the following information):**
 - macOS: 12.6
 - Version 0.8.1

**Additional context**

**Comment by mstarke** [comment]
This is as designed. Otherwise your key file has no security benefit. You can however enable that MacPass remembers keyfiles. This the will result in your desired behavior.
