### ISSUE TITLE
Show 2FA in table view

### ISSUE THREAD

**Issue by thomassth** [MacPass/MacPass#1253]
**Describe the solution you'd like**
Currently, 2FAs are hidden in menus, unlike usernames and passwords that got a column

I want to use a .kdbx like a Google authenticator:
1. when I unlock the database, I can see all 2FA codes saved
2. clicking the 2FA field / icon will copy the 2FA code

**Describe alternatives you've considered**
KeeWeb requires extra clicks, similar to MacPass
On android, KeeWebDX shows all 2FAs alongside usernames by default, akin to Google Authenticator

**Comment by mstarke** [comment]
Done. 29756c00b36d3a1686ad7d8a1d3fe03eafefd5cb
