### ISSUE TITLE
Password Hint

### ISSUE THREAD

**Issue by TeeJayR** [MacPass/MacPass#1256]
As an addition to fields like "tags" and "notes" it would be nice to also be able to save a password hint. The password hint should be hidden/obscured by default, such that the hint can not be seen directly (similar to the password itself).

An alternative to the password hint would be to use the notes field, but this does not allow to hide the password hint per default.

Although not ideal, a possible solution would be to use the `CustomData` property for a password hint (which has been introduced by [KDBX 4](https://keepass.info/help/kb/kdbx_4.html)).

**Comment by mstarke** [comment]
Are you talking about  a password hint for entires or for the master password?

**Comment by TeeJayR** [comment]
Talking about entries. The purpose is to store hints how the password has been generated (if not using the auto-generator) for remembering the password by hard.

**Comment by mstarke** [comment]
Why not add a custom field name it password hint and hide it?

**Comment by TeeJayR** [comment]
Oh, indeed I did not see adding custom fields is already possible! Thank you for the (password) "hint" 😊
