### ISSUE TITLE
Typo in Preferences > Integration. Word "where" should be changed to "were"

### ISSUE THREAD

**Issue by oneofthedamons** [MacPass/MacPass#1262]
**Describe the bug**
Under "Autotype" the second sentence reads: "Some issues where found that prevent Autotype or Global Autotype to work."

**To Reproduce**
1. Go to 'Preferences…'
2. Select 'Integration'
3. Second sentence under "Autotype"

**Expected behavior**
This should read: "Some issues were found that prevent Autotype or Global Autotype to work."

**Desktop (please complete the following information):**
 - macOS 12.6.3
 - Version 0.8.1

**Comment by diepoe** [comment]
Issue can be closed
