### ISSUE TITLE
Only showing 3

### ISSUE THREAD

**Issue by amoss1970** [MacPass/MacPass#1266]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - macOS: [e.g. 10.12.1]
 - Version [e.g. 0.7.3]

**Additional context**

**Comment by amoss1970** [comment]
Macpass is only showing first 3 characters of my password, How do I get to see the whole password

**Comment by mstarke** [comment]
Duplicate of #1210. Fixed.
