### ISSUE TITLE
Use fixed-width numbers for TOTP countdown

### ISSUE THREAD

**Issue by katullo11** [MacPass/MacPass#1269]
The TOTP_REMAINING_TIME_XX_SECONDS string should use fixed-width numbers so it doesn't constantly shift the preview column of an entry back and forth.
If I didn't explain myself clearly enough, select an entry you know has TOTP set up and just watch, you'll see the preview column slightly move to readjust for the countdown numbers changing.
Thanks.

**Comment by mstarke** [comment]
It did not bother me that the counter makes the UI move a bit. I might move to a fixed size for the field to prevent this or re-use the badge style for the outline to make this look better
