### ISSUE TITLE
Search needs more options

### ISSUE THREAD

**Issue by DominusExult** [MacPass/MacPass#127]
I just noticed that search does not search all possible fields.
It should be possible to search notes and attachements, also possibility to select _ALL_ to search everything at once :)

**Comment by derhansen** [comment]
+1 for including the Groups field in the search criteria

**Comment by mstarke** [comment]
All is added and working.

**Comment by mstarke** [comment]
I'm closing this. If any mentioned search filters are still missing, new issues should be created.
