### ISSUE TITLE
Usability would be much improved if after opening the application focus is on search field.

### ISSUE THREAD

**Issue by trancephorm** [MacPass/MacPass#1282]
There's really no need to be otherwise....

**Comment by mstarke** [comment]
If you tick the box in the workflow settings this should work out like expected.

**Comment by trancephorm** [comment]
Thank you, haven't noticed it! Still, that should be default. More, such setting is not really needed if it's default.

**Comment by mstarke** [comment]
If the default is ok for you then I agree. I however do not need this. Others might too so having this behavior being configurable is fine for me. Defaulting to true might be a good idea though.
