### ISSUE TITLE
tooltip to explain why stop sign alert icon is present

### ISSUE THREAD

**Issue by freefly42** [MacPass/MacPass#1285]
**Is your feature request related to a problem? Please describe.**
My file has a red stop sign with an exclamation mark for an icon at the root level, and so does one of the entry.  But there is no explanation anywhere *WHY* this entry has been flagged.  It's like yelling really loudly "SOMETHINGS WRONG" without giving the faintest hint what is wrong.

**Describe the solution you'd like**
Disable the alert icon or at least put a tool tip or message somewhere to indicate *WHY* this is getting flagged with some kind of emergency alert

**Describe alternatives you've considered**
Got nothing.  Wasted a bunch of time searching.

**Additional context**
<img width="44" alt="image" src="https://github.com/MacPass/MacPass/assets/53059711/67653d72-97c9-4243-a1db-6c7f7f2699d9">

**Comment by mstarke** [comment]
Sorry @freefly42 for the lack of documentation. This surely is a sore point. The icon is displayed for entries or groups that have expired. You can set an expiration date on groups and entries and if this is reached, MacPass will show the the red icon you mentioned. Hope this clears things up.
