### ISSUE TITLE
tried to change master password- lost access to whole db. wtf

### ISSUE THREAD

**Issue by AndreiMotinga** [MacPass/MacPass#1298]
tried to change master password and created new password -> couldn't access db with new password - but worked with old. 

then tried again, created a key -> now cant open the db file. 

now I have kdbx file that cant be opened and .key file that appears to be doing nothing.

what do I do? how do I rescue my data?

**Comment by mstarke** [comment]
The UI of MacPass tries to mimic the one established with KeePass and KeePassXC. If you change the master key you can either set a password and/or a key-file. You need to save your database after you changed the credentials, otherwise no change is made since the credentials are used to derive the encryption keys for the file.

Can you point out what you did step by step?

**Comment by AndreiMotinga** [comment]
I'm not sure what step by step of it was. 

I went file -> change master password and entered new password. but also saved some key file that I called vault.key. 

so no I have passwords.kdbx and vault.key  files..  and I cant open it. 

I wasn't paying attention.

**Comment by mstarke** [comment]
Then you have set a password and key file. You should be able to load the database `passwords.kdbx` with the password and the `vault.key` file loaded. If not the only way to recover is to use a backup (which you hopefully have!)

**Comment by AndreiMotinga** [comment]
Thank you @mstarke for cool response to my full on panic request. 

I Appreciate it great deal. 

I thought it's one or the other -> 
<img width="503" alt="Screen Shot 2024-07-01 at 11 28 22 AM" src="https://github.com/MacPass/MacPass/assets/6856852/b0789780-cb34-486c-9c26-a62512502d52">

but  using both pass and key file works!

**Comment by mstarke** [comment]
Awesome that you were able to get back into your database. I was a bit worried that you‘ve locked yourself out. Glad I‘ve been able to point you to the solution.
