### ISSUE TITLE
Missing fields in Inspector

### ISSUE THREAD

**Issue by headcase0570** [MacPass/MacPass#1299]
**Describe the bug**
I cannot see the username field in the 'Inspector' (resizing inspector window makes no change). Even when creating new entries, no username field is presented.
Additionally, no title can be entered, previously existing entries cannot be renamed.

When opening _any_ entry in my Keepass2 database, I am seeing a very limited number of entries;
- Password
- URL
- Expiration date
- Tags
- Notes

**To Reproduce**
1. open database.kdbx
2. open any entry, or create new entry
3. Look at Inspector

**Expected behavior**
The ability to see all data currently included in entry
Entering basic information (title, username) in new entries

**Screenshots**
Screenshot added
<img width="1199" alt="Screenshot 2024-08-08 at 13 03 02" src="https://github.com/user-attachments/assets/f0722363-623b-478b-8a62-dc0a4a5931d5">
<img width="1196" alt="Screenshot 2024-08-08 at 13 03 27" src="https://github.com/user-attachments/assets/915044e9-d0a4-4bfd-9aeb-54c404994283">

**Desktop (please complete the following information):**
 - macOS: Big Sur 11.7.10

**Additional context**
On my Windows PC I manage the same database with the official keepass software, the database is saved to my Google Drive, where Macpass can access it.

**Comment by mstarke** [comment]
The Inspector view is scrollable. Try scrolling up and you should see the missing fields. The line on top indicates that the view is clipped.

**Comment by headcase0570** [comment]
> The Inspector view is scrollable. Try scrolling up and you should see the missing fields. The line on top indicates that the view is clipped.

Thank you! I feel a bit silly now, I've gone through all the display options and found nothing to reset the view, or select the information to display.

**Comment by headcase0570** [comment]
#1299 can be closed.

**Comment by mstarke** [comment]
> > The Inspector view is scrollable. Try scrolling up and you should see the missing fields. The line on top indicates that the view is clipped.
> 
> Thank you! I feel a bit silly now, I've gone through all the display options and found nothing to reset the view, or select the information to display.

No need to feel silly. This has happened a couple of times and I'm the one to blame to make it not obvious the view can be scrolled.
