### ISSUE TITLE
Keyfile persistence

### ISSUE THREAD

**Issue by txVLN** [MacPass/MacPass#135]
Might it be possible to have the keyfile remembered across lock / restart? It's only a few seconds to navigate to it every single time, but it seems like a waste of effort. 
Thanks!

**Comment by pavan-shipmnts** [comment]
0.7 is here and I still don't see it remembering my keyfile location

**Comment by mstarke** [comment]
It is present but only if you have set a password as well. MacPass currently does not store the file if the database can be unlocked solely by the file.
