### ISSUE TITLE
Issue: "Enable KeePassHttp" server option grayed out in binary release.

### ISSUE THREAD

**Issue by tkb** [MacPass/MacPass#138]
Hi - great project! Just wanted to check - is the KeePassHttp support enabled in the latest binary release? It's grayed out for me running 10.9.1.

**Comment by mariosangiorgio** [comment]
I'm running Version 0.5.1 (2556) and that option is still greyed out. Does it contain the feature or shall I update to a newer version?

**Comment by mstarke** [comment]
It's not integrated into the master but you can use @jameshurst fork with he keeps in synch.
