### ISSUE TITLE
Provide easier hotkeys

### ISSUE THREAD

**Issue by zirkler** [MacPass/MacPass#171]
Hello,

`Shift + Command + C` / `Alt + Command + C` is a little bit inconvenient compared to KeePassX where it is only `C` / `B` for copying the password / username. I would love to see an entry in the preferences where I can map custom hotkeys.

**Comment by Floppy** [comment]
Thanks for the pointer to this, setting up manually solved the issue for me. Updated instructions for Yosemite: https://support.apple.com/kb/PH18418?locale=en_US; enter "Copy Password" as the command name and restart MacPass. Bingo.

(It would still be easier for new users to use cmd-C natively though ;) )

**Comment by mstarke** [comment]
````Cmd + C``` was the default but text inputs with focus did consume the copy so I changed it.
