### ISSUE TITLE
Implement support for KeePassHTTP

### ISSUE THREAD

**Issue by dereulenspiegel** [MacPass/MacPass#172]
As a recent MacOS user I really would like to see support for KeePassHTTP since this enables direct integration with Firefox and Chrome and makes life much more easier for the user.

**Comment by neeklamy** [comment]
I’ve read about developers setting up Amazon Wish Lists – _I would link to some examples here, but of course I can’t find any right now_. And supposedly, because it’s a lot easier for them, large companies will have gift buying budgets for this purpose.
