### ISSUE TITLE
Paid beta program for MacPass?

### ISSUE THREAD

**Issue by Govinda-Fichtner** [MacPass/MacPass#181]
After heartbleed (http://heartbleed.com/) password managers seem to be all the rage again.

I think this would be a very good time to get a paid beta program going... 

My hope would be that this might make it possible to direct more resources into the development of MacPass.

I think people are willing to pay for a beta product if there is a strong commitment visible to finish the product. Minecraft is one of the more popular examples where this worked out really well. 

Why not start a crowdfunding campain? And then evolve MacPass step by step like the Elite Dangerous (http://elite.frontier.co.uk/) guys are doing? 

I would definitely pay for a evolving MacPass if it would ensure a faster development into a 1.0 version...

**Comment by mstarke** [comment]
Closing this since it's not gonna happen.
