### ISSUE TITLE
The document "Untitled" could not be saved as "Untitled"

### ISSUE THREAD

**Issue by abhinavsingh** [MacPass/MacPass#205]
Hi, Love MacPass, Trying to set it up, leads into this while trying to save.

![screen shot 2014-07-30 at 6 22 06 pm](https://cloud.githubusercontent.com/assets/126065/3758845/5f0efd72-1851-11e4-891d-c35ad9b67fe5.png)
![screen shot 2014-07-30 at 6 22 24 pm](https://cloud.githubusercontent.com/assets/126065/3758846/5f1ef542-1851-11e4-98f1-2fd6c7c6e9ae.png)
![screen shot 2014-07-30 at 6 22 37 pm](https://cloud.githubusercontent.com/assets/126065/3758847/5f28c93c-1851-11e4-85a2-5c9ffda653ea.png)

**Comment by akcasoy** [comment]
I have the exact same issue with the latest release.

**Comment by mstarke** [comment]
Can you elaborate? What version are you running?

**Comment by akcasoy** [comment]
As written, latest release: MacPass-0.6.2-alpha.zip
But i have found out that, if you try to save the file first time through the menu "File->Save As", it works. But if you try to close the app with a change in DB, after you get the dialog whether you want to save or not, there it does not work to save the file first time.
