### ISSUE TITLE
Multithread support for transformations

### ISSUE THREAD

**Issue by Jellyfrog** [MacPass/MacPass#211]
If you have a database with a high number of transformations rounds it really benefits from multithread support.

> KeePass uses multithreading to compute the transformations (the master key is split up to two parts of 128 bits, which is the AES block size). On dual/multi core processors, the computation can be twice as fast as on a single core processor.
> http://keepass.info/help/base/security.html

**Comment by mstarke** [comment]
This has been moved to KeePassKit https://github.com/MacPass/KeePassKit/issues/55
