### ISSUE TITLE
Keyfile generator

### ISSUE THREAD

**Issue by mstarke** [MacPass/MacPass#25]
Add the ability to generate a Keyfile

**Comment by dmaciej** [comment]
@mstarke I can't find this feature. Could you point it out?

**Comment by mstarke** [comment]
File -> Change Master Password -> "Generate Keyfile"
![screen shot 2016-07-11 at 09 40 25](https://cloud.githubusercontent.com/assets/58428/16723251/2a80d914-474c-11e6-88a3-3cb8f74aa8ba.png)
