### ISSUE TITLE
GPL Violation Safe Password

### ISSUE THREAD

**Issue by mstarke** [MacPass/MacPass#275]
And another one. At least there's iCloud document support :)

**Comment by yusf** [comment]
That sucks. Out of curiosity, what would happen if MacPass stole Safe Password's graphics in return?

**Comment by mstarke** [comment]
Legal consequences if the copyright holder would press for compensation. And since I'm not really fond of pissing people of and try to respect the work of others it's out of the question to "borrow graphics" ;-)

And then there's the not so slim change the graphics aren't correctly used in the first place. Panic's Transmit Truck comes to mind.

**Comment by tflo** [comment]
https://panic.com/extras/ripoff/

**Comment by mstarke** [comment]
@tflo :+1:

**Comment by yusf** [comment]
Just a trollish way to lure them out. Not necessarily a great idea. :smile:
