### ISSUE TITLE
[Feature Request] Multiple entry selection

### ISSUE THREAD

**Issue by akmalk** [MacPass/MacPass#285]
I was about to drag the entries around the groups and had to do it one by one. It would be great to have multiple entries selection and operate on them.

thanks.

**Comment by mstarke** [comment]
With the exception of drag&drop it should work since c47c24e3ca96b3ee125e05f9e819771e237f9de6

**Comment by mstarke** [comment]
I'm closing this and leaving drag and drop support as a separate issue.

**Comment by mstarke** [comment]
Drag and Drop tracked here #515
