### ISSUE TITLE
Settings option: default length for generated passwords

### ISSUE THREAD

**Issue by seeholza** [MacPass/MacPass#286]
I would love to be able to set a default length for generated passwords setting.
Or, alternatively, store and reuse the last length that was chosen for generation.

Its a common hassle for me in Macpass to have to adjust the slider/field every time I add a new entry.

**Comment by schauder** [comment]
I thought this would reset to factory defaults ...

**Comment by mstarke** [comment]
It's called "Set Defaults" so it should set them, not reset them. What would you label the button if it is used to set the current settings as defaults?

**Comment by schauder** [comment]
> It's called "Set Defaults" so it should set them, not reset them.
I agree it is kind of correct. I think the real problem for me was that I didn't expect to set the default in the dialog/screen where you set the specific values. So I chalked that up as a bad labeling.

Maybe "Use these settings as default" Of course that is rather long ... 🤷‍♂️

**Comment by mstarke** [comment]
This dialog is the only place where you edit any password settings, so this was more or less a logical place to but it. Additionally you can set defaults for entries, and if you did that you can press ```Alt``` to remove the entry-specific settings.
