### ISSUE TITLE
Remember last-opened database and reopen it on start (maybe a setting)

### ISSUE THREAD

**Issue by mstarke** [MacPass/MacPass#29]

**Comment by vonbarnekowa** [comment]
Feature isn't completely working. I think the app is only remembering the last database but not the key file and if you ticked the password checkbox or not.

**Comment by mstarke** [comment]
The feature is re-open the last database.

You're referring to two more things:
1. remember, if a database has a password or not
1. remember, if a database has a key file and if so, what file it was.

Feature 1 is not implemented and I would not encourage it since it's a security compromise.
Feature 2 is implemented, you need to check *Remember Keyfile for Databases* in the *General Preferences*.

<img width="512" alt="screenshot 2019-01-08 at 07 57 09" src="https://user-images.githubusercontent.com/58428/50814793-278b5c00-131b-11e9-835d-6648882a5ac3.png">
