### ISSUE TITLE
[Feature Request] Hide Entries in Trash from Search Results

### ISSUE THREAD

**Issue by BlackSwiftSoftware** [MacPass/MacPass#296]
It's probably best to have an option. It's probably best to default to showing the results. This is probably of minor importance, so I'd focus on implementing other features first. I do believe that KeePass has this option though.

**Comment by soliva** [comment]
+1

**Comment by larssb** [comment]
+1

**Comment by mstarke** [comment]
Search does respect the "search" settings for groups, MacPass did not set the "do not search" on Trashes  but does so now if it generates the trash. If the trash was then again set to be included in search, it's included again.

**Comment by mstarke** [comment]
I'm considering this as fixed since KeePassKit correctly disables search for the trash so those items get excluded from the search results
