### ISSUE TITLE
[Feature Request] Allow deleting individual items from trash

### ISSUE THREAD

**Issue by BlackSwiftSoftware** [MacPass/MacPass#297]
This may be one that you don't want to fix. Coming more from the windows world, I'm used to this behavior (at least in the file browser.) I realize Macs don't work this way with files in the trash, so maybe you want to be consistent with records in the KeePass Recycle Bin. Still, I think it increases usability to allow for the permanent deletion of an item in the Recycle Bin. I would warn users first before proceeding. Feel free to remove this request if you don't want to implement it.

**Comment by mstarke** [comment]
The current implementation has nothing to do with Mac OS behaviour. I just haven't had time to add it. Will be done eventually.

**Comment by mstarke** [comment]
This is present in 0.7.x
