### ISSUE TITLE
Light gray / white "Empty Trash" button on Yosemite

### ISSUE THREAD

**Issue by gbernady** [MacPass/MacPass#305]
I haven't seen it already reported, so here it is. See the screenshot:

![empty_trash_white](https://cloud.githubusercontent.com/assets/4059358/5807697/fd2bc93e-a025-11e4-9806-1c06154e062e.png)

I'm using the latest master.

**Comment by DominusExult** [comment]
hmm, I might be wrong about the actual issue, but isn't any group or entry you select inverted?

**Comment by mstarke** [comment]
@DominusExult  I think you might be off. @gbernady refers to the white text on a light grey button.

**Comment by mstarke** [comment]
This was fixed ages ago :-)
