### ISSUE TITLE
[FEATURE REQUEST] search also in custom fields, be able to show custom fields in table

### ISSUE THREAD

**Issue by rburgst** [MacPass/MacPass#316]
I have 2 feature requests regarding custom fields.

It would be nice to 
- be able to find entries through search where the match is in a custom field, imagine that I have a custom field called "hostname", I would like to find entries by searching (also) in their hostname field
- be able to view a custom field in the table grid, e.g. previously mentioned hostname field

**Comment by mbonaci** [comment]
IMHO this is the only feature that is missing in this great product. So often I wish I can search all fields, especially the `Notes` field.

**Comment by mstarke** [comment]
Custom field search can be achieved by searching in "everything" this is however not particularly useful since this might result in massive false hits

**Comment by mstarke** [comment]
I'm splitting this since it's two things at once. See #1136 and #1137
