### ISSUE TITLE
[feature] search field auto focus on app start

### ISSUE THREAD

**Issue by wujekbogdan** [MacPass/MacPass#319]
It would be nice to autofocus on the search field once the app is opened. search is usually the first feature we use.

**Comment by mstarke** [comment]
Since search involves typing, why not add a ⌘+F before and you are inside the search field?

**Comment by wujekbogdan** [comment]
⌘+F would be a nice feature too, but this is how the official keepass for Windows works and i got used to it (and I believe i'm not the only one).

If for a some reason you don't want to implement it as default maybe you could add it as an option in the app settings?

PS.
Tx for this app - Even alpha version Is much better than KyPass Companion (which cost $7.99 in app store...)

**Comment by mstarke** [comment]
Just try it, it works already ;-)

**Comment by nwoolls** [comment]
+1 - to me it seems like a lot of key-presses involved in unlocking, finding a password, highlighting the password, and copying.

* Type password <return>
* ⌘F <enter text> <return>
* ⌘ ⌥E
* <down arrow>
* ⌘ ⌥C

**Comment by mstarke** [comment]
I know the keyboard navigation isn't pristine. Just a side note - using the mouse might be quite quick. You can double-click on columns to copy them to the pasteboard

**Comment by wujekbogdan** [comment]
> Just try ⌘+F, it works already.
@mstarke 

yeah, it works and it's OK, but it's one more step to get things done. When the application starts first we need to focus on the search field, then choose a result from the list (which requires an additional click, because pressing `tab` key doesn't move focus to the first search result: https://github.com/mstarke/MacPass/issues/414)

IMO implementing this 2 little features could improve the usability a lot.

**Comment by jeffmcneill** [comment]
@mstarke is this issue dealt with by the #443 implementation? Seems similar, or perhaps the fix is similar.

**Comment by mattbk** [comment]
I don't think #443 fixes it. As of 0.7.12, I still have to press command-F to search.

**Comment by georgesnow** [comment]
You could try my plugin MacPassRevealer, which provides this. It might suit your needs.

**Comment by mstarke** [comment]
Done. Included in 0.8.
