### ISSUE TITLE
[Feature Request] - Save with extension other than .kdbx

### ISSUE THREAD

**Issue by zdover** [MacPass/MacPass#322]
Hi,
Thanks for adding the ability to open kdbx files that do not have the .kdbx extension. It would be great if, when saving, the original extensions of the file (say *.docx or whatever) was retained.
Zach

**Comment by mstarke** [comment]
Never would have thought about that but a very valid point.

**Comment by l3ender** [comment]
I'm running into this issue now and it's kind of strange. I open a database file with a non standard file extension. I'm not exactly which scenarios trigger it, but sometimes I notice that the database file has been renamed. Not just a new copy with new extension...the original database no longer exists.

Thanks!

**Comment by kyranjamie** [comment]
Came to report same issue.  Big +1 for this issue.

I've read of malware before that searches the 1password / lastpass default database directories (and uploads it somewhere).  
Keepass/Macpass doesn't have a default save directory, but on a compromised machine it'd be trivial to `find ~ -name "*.kdbx"`.  As suggested by @zdover, a inconspicuous `.docx` would circumvent this.

I'm sure a more sophisticated search could detect a keepass database file, but this would be a slower operation and require more work.  This feature would remove a small, but not insignificant, attack vector.

**Comment by ninjasiat** [comment]
You can do a workarround by building an APP with Automator wich calls

open -a MacPass filename.unknown

Where "filename.unknown" is your Databasename

regards...

**Comment by ninjasiat** [comment]
Hi,

i was wrong...
while opening a file with another extension, macpass allways tries to "autosave" the file. but here it tries to save the filename.kdbx!
so it's not functional.

regards...

**Comment by vvojciech** [comment]
+1 

Just started using MacPass and all in all is a great software, but this feature is missing for me.

**Comment by mstarke** [comment]
This should now work as expected. Custom file extensions will get preserved when opening the file.
