### ISSUE TITLE
[feature request] support for **TOTP**

### ISSUE THREAD

**Issue by rathisarov** [MacPass/MacPass#337]
nicely working so far as much I need it especially using **_jameshurst fork for http support**_
would be very happy and feel complete when the much used **TOTP support** in any form (plugins or inbuilt)
looking forward,
Thank you for the great efforts.
Sarov.

**Comment by boky8** [comment]
I agree. Use it every day.

This is the original plugin that most other apps seem to support:
https://bitbucket.org/devinmartin/keeotp/wiki/Home

**Comment by rathisarov** [comment]
Nice to see the project developing with great prospects, especially with Jameshurst http fork. 
Also the  discussion on plugin system is a great hope.
Let's hope someone would develop a plugin for TOTP support.

**Comment by mstarke** [comment]
Keepass has native support for HOTP and I just took a look at the requirements for TOTP. I'm currently pondering over how the plugin API should be extended to make it easy to add those kinds of pluings.

There is the need for:
- Autotype command resolving
- Autotype command announcement
- Help to enter special keys for attribute (this should actually be something MacPass does natively)
- Arbitrary actions for entries (via menu items)

**Comment by jsphpl** [comment]
Hey guys, is there any progress on this?

**Comment by mstarke** [comment]
There's been some progress on KeePassKit to support HMACOTP as well as TOTP. Both aren't finalized and working but it's a list on the item. The rough roadmap is to include them in 0.8.

**Comment by jsphpl** [comment]
Cool, thanks for the update!

**Comment by aairey** [comment]
Any update?

**Comment by mstarke** [comment]
Yup. Feature is done. Will get pushed out with 0.8
