### ISSUE TITLE
Custom sort

### ISSUE THREAD

**Issue by enterfornone** [MacPass/MacPass#366]
I seem not to be able to use custom sorting on the lists (neither to reorder them) - both of groups and entries.
In KeePass, you can have three possibilities after hitting column title - sort ascending, sort descending and custom sort.
Here custom sort is not possible.
After initial installation the entries were indeed sorted by my custom order, however after the first clicking on column header, they got sorted alphabetically and there was no going back.
As I see there is no option for reordering in the menus, I'd say this is not a bug, but a feature request.

**Comment by sdellenb** [comment]
I found this workaround for now (accidentally clicked on the column header and inadvertently sorted by name):
1. Quit MacPass
2. Delete (or move) `~/Library/Preferences/com.hicknhacksoftware.MacPass.plist`
3. Start MacPass

Now the default (custom) sorting will be applied again.
__Attention: This also resets the default password settings (length, extra characters etc.).__

**Comment by enterfornone** [comment]
It does work :)
Many thanks!

**Comment by mstarke** [comment]
A solution might be to add a new column at the beginning that "sorts by custom order"

**Comment by mstarke** [comment]
@sdellenb you can selectively delete the sort descriptor for the table.

if you take a look at the settings, you should find a key ""NSTableView Sort Ordering v2 EntryTable".
If you run on 10.11 or below this key might be a bit different but it should at least contain something about sort ordering of EntryTable.

```bash
defaults read com.hicknhacksoftware.MacPass
{
    "NSTableView Sort Ordering v2 EntryTable" = <62706c69 73743030 d4010203 0405062f 30582476 65727369 6f6e5824 6f626a65 63747359 24617263 68697665 72542474 6f701200 0186a0ab 07080f18 191a1b1c 222a2b55 246e756c 6cd2090a 0b0e5a4e 532e6f62 6a656374 73562463 6c617373 a20c0d80 02800880 0ad31009 0a111417 574e532e 6b657973 a2121380 038004a2 15168005 80068007 5a496465 6e746966 69657259 41736365 6e64696e 675f1017 4d505469 746c6543 6f6c756d 6e496465 6e746966 69657208 d21d1e1f 205a2463 6c617373 6e616d65 5824636c 61737365 735c4e53 44696374 696f6e61 7279a21f 21584e53 4f626a65 6374d310 090a2326 17a21213 80038004 a2271680 09800680 075f101a 4d505573 65724e61 6d65436f 6c756d6e 4964656e 74696669 6572d21d 1e2c2d5e 4e534d75 7461626c 65417272 6179a32c 2e21574e 53417272 61795f10 0f4e534b 65796564 41726368 69766572 d1313255 41727261 79800100 08001100 1a002300 2d003200 37004300 49004e00 59006000 63006500 67006900 70007800 7b007d00 7f008200 84008600 88009300 9d00b700 b800bd00 c800d100 de00e100 ea00f100 f400f600 f800fb00 fd00ff01 01011e01 23013201 36013e01 50015301 59000000 00000002 01000000 00000000 33000000 00000000 00000000 00000001 5b>;
    "NSTableView Supports v2 EntryTable" = 1;
}
```

You can just kill this setting via the following command (use another key if you found a different one in your settings)

```bash
defaults delete com.hicknhacksoftware.MacPass "NSTableView Sort Ordering v2 EntryTable"
```

A side note: Deleting the preferences file does not always have the desired effect. For a long time now (I would guess since 10.7 or 10.8) the defaults system uses a database an other "magic" stuff not the files. The files are just a mere snapshot but not a source. If you really want to modify anything you should always use the ```defaults```command. Sometimes deleting the files works, sometimes it doesn't.

**Comment by sdellenb** [comment]
Thanks, Michael, I've bookmarked your solution for the next time. 👍

**Comment by mstarke** [comment]
Since 1ae41df2cebd1cf0b7f8df25e69cd9454540f535 there's a "custom sort" column. It allows to sort ascending and descending in the order the entries are stored internally. It's rough but works as expected. Reordering entries though isn't supported yet.

**Comment by enterfornone** [comment]
Sorry to resurrect a very old thread, but as I managed to click on the column head again, I'm now stuck one more time with alphabetical sorting.
But this time neither deleting the preferences key, neither the whole preferences file worked.
Also there is no custom sort column. I'm running 0.7.3 (17830), as the updates started again and I went out of the nightly builds.
How can I get back the custom sorting from KeePass (I sync the file from KeePass on Win)

**Comment by mstarke** [comment]
There is a custom sort column, it only has no name. By default the first column has no title. This is the custom sort column. You can even move it around but there is no way to hide it via the context menu.

So you should be able to click on this column and have your custom ordering back. You can change it by clicking to order ascending or descending.

**Comment by mstarke** [comment]
Related to #823.

Also, easier re-ordering should be enabled.
