### ISSUE TITLE
Tab from search box should move to search results

### ISSUE THREAD

**Issue by Floppy** [MacPass/MacPass#369]
Using cmd-F to search for keys, it would be lovely if hitting tab from the search field went to the list box and highlighted the first entry in the list. Then I could get everything I need without using the mouse.

At the moment, hitting tab in search seems to change focus to the folder view rather than the search results.

I did search for issues on this (including closed), and found a number of things around tab ordering, but not this specific issue that I could see. Sorry if it's a dupe :)

**Comment by wujekbogdan** [comment]
+1
and this one is a bit related: https://github.com/mstarke/MacPass/issues/369

**Comment by mstarke** [comment]
See #66 #414 #603 #707 #749 for further discussions
