### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by schrej** [MacPass/MacPass#375]
The only thing that kept me from using KeePass was the absence of a good looking and working OSX Client. Now my that seems to be resolved as this App looks great and seems to work well. And it is still under development as well.

The only thing i don't really like about this app is the icon. It looks quite outdated on Yosemite/El Capitan. Even though my Graphics skills are not that great i made a new one. Its quite simple, yet it matches the style of all the other new icons (e.g. Atom, Sourcetree).
It uses the original KeePass Lock to make it recognizable. And i used blue as it is in the original icon as well. The Gray background is just to make the white border visible.
![macpass-icon](https://cloud.githubusercontent.com/assets/1710904/10117863/799846b4-6466-11e5-9ad1-0ae4a8c40764.png)

**Comment by mstarke** [comment]
You're right considering the outdated look on 10.10 and 10.11. We might even have luck and can get Iiro Jäppinen to post his opinion on a new version, but his Github account seems to have been removed :(

**Comment by schr3j** [comment]
If that is the same person i guess he would have some things to improve here.
https://dribbble.com/shots/1756852-Yosemite-style-app-icon

**Comment by mstarke** [comment]
Icon is still the same. Might need smaller work-over. Closing for now.
