### ISSUE TITLE
Autotype matching + Window Associations

### ISSUE THREAD

**Issue by darnel** [MacPass/MacPass#388]
I tried last release and returned to KeepassX, but with building 'master' MacPass looks great!

This is not complain, I just want to find out, how it works and I'm not experienced in Objective C.

So I open DB made in KeepassX in MacPass and Autotype works well for most items, but two webpages (wihich are important to me) says "No match!"

https://idp.fit.cvut.cz/idp/Authn/UserPassword
https://idp2.civ.cvut.cz/idp/Authn/UserPassword

I have filled in login, password, URL and "Auto-Type-Window:" note (this is how it is done in "patched" KeePassX for Mac)

When I add "Window Association" in MacPass it start work for both webpages. For other items in DB this is not needed. ~~However these "Window Assocations" is not persisted and cannot be loaded again.~~ (sorry, works in .kdbx)

Is the "Auto-Type-Window" note ignored and match is done only by URL? Why does it work for some pages and doesn't for others? Can you point me?

Thanks

**Comment by mstarke** [comment]
The lost Window associations is a bug in KeePassKit. See [KeePassKit Issue 5](https://github.com/mstarke/KeePassKit/issues/5)

**Comment by mstarke** [comment]
KDB Autotype-style notes aren't supported at the moment. This should be moved to KeePassKit since it's responsible for supporting any KBD/KDBX features.
