### ISSUE TITLE
Yubikey support with the new plugin-system?

### ISSUE THREAD

**Issue by EugenMayer** [MacPass/MacPass#457]
Hello,

MacPass is a filling a gap which is yet not done by anyone. 

Any person who wants to use (Kee)Pass under OSX with Yubukey is yet blocked (thinking about OTP) since plugins do not work at all.

MacPass now has plugin support and MacPassHTTP already works great with chromelPass or passfox.

Now, it would be great, if we somehow could port http://keepass.info/plugins.html#otpkeyprov

Which would make MacPass the one and only solution. Neither KeePassX ( no plugin system ), Keepass portable with Mono ( broken, plugin does not work) do offer any plugins. 

Beside all that, MacPass and its UI is _great_.

Thank you for all your work and effort

**Comment by darnel** [comment]
I think this can be closed, duplicates #90.

**Comment by EugenMayer** [comment]
i do not think it is the same, the other requests a own implementation, i ask to rather port the plugin, similar as the web-plugin
