### ISSUE TITLE
carthage bootstrap failed in Sparkle

### ISSUE THREAD

**Issue by jirisrba** [MacPass/MacPass#472]
carthage bootstrap failed

---

A shell task (/usr/bin/xcrun xcodebuild -project /Users/Srba/Scratch/MacPass/Carthage/Checkouts/Sparkle/Sparkle.xcodeproj -scheme Sparkle -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
*\* BUILD FAILED **

e: explicitly redeclare 'trashItemAtURL:resultingItemURL:error:' to silence this warning
        success = [_fileManager trashItemAtURL:tempItemURL resultingItemURL:NULL error:&trashError];
/Users/Srba/Scratch/MacPass/Carthage/Checkouts/Sparkle/Sparkle/SUHost.m:82:21: warning: 'objectAtIndexedSubscript:' is partial: introduced in OS X 10.8 [-Wpartial-availability]
The following build commands failed:
    PhaseScriptExecution Run\ Script:\ Link\ fr_CA\ to\ fr /Users/Srba/Library/Developer/Xcode/DerivedData/Sparkle-bflqoqpznlkcikcsvwntyoijtcuh/Build/Intermediates/Sparkle.build/Release/Sparkle.build/Script-6195D4B40E40505A00D41A50.sh
(1 failure)

**Comment by mstarke** [comment]
Closing due to it being quite old and most likely not relevant anymore
