### ISSUE TITLE
Database unable to be read by KeeWeb or KeePassX

### ISSUE THREAD

**Issue by arkag** [MacPass/MacPass#477]
I've converted my 1password database to XML and imported it using MacPass. I see all entries with Macpass. Attempting to open this new database in KeeWeb or KeePassX results in only showing 1 entry. Is this something wrong with their management of the database or something wrong with how MacPass imports XML? KeeWeb failed to import the XML completely, so I'm leaning towards that.

**Comment by cwre** [comment]
Database seems to be working on KeePassDroid. I'll leave this open for now.

**Comment by yowidin** [comment]
I had a similar issue. After opening an existing KeePassX database, adding an entry and saving the database KeePassX is no longer able to open the database.

**Comment by shaharck** [comment]
Any work around for this issue? (getting the same on lastpass migration too)

**Comment by mstarke** [comment]
I need a bit of clarification on the xml format. How did you generate it? Is this a 1password built in xml exporter?

**Comment by mstarke** [comment]
@shaharck Any updates with the current version of MacPass?
What type of XML file did you generate?

**Comment by mstarke** [comment]
I'm closing this since I have not enough information to fix this issue
