### ISSUE TITLE
[Feature Request] Drag and Drop of Multiple Entries

### ISSUE THREAD

**Issue by ghost** [MacPass/MacPass#515]
I recently tried to select hundreds of entries and wanted to move them in a new group. Couldn't figure out how to do it.

Selecting and moving multiple entries at once would be helpful.

**Comment by mstarke** [comment]
Multiselect is working in master is there but drag and drop support for it is still missing.

**Comment by tflo** [comment]
Yep, support for dragging multiple items to a different folder would be great!

**Comment by magebarf** [comment]
Joining the choir here!
Will possibly have a look at it myself if I find the time.

**Comment by NikolausDemmel** [comment]
+1 for drag-and-drop with multiple items. In particular in combination with #721 this can make things tedious.

**Comment by mstarke** [comment]
Duplicate of #285

**Comment by mstarke** [comment]
Released in 0.7.4
