### ISSUE TITLE
New generator based on english words

### ISSUE THREAD

**Issue by bkolada** [MacPass/MacPass#518]
Hey, 
it could be nice to have generator of passwords from list of english words. To have something like:
BananaJob12tree it could be easier to write and read.

**Comment by 9point6** [comment]
Or a step further - plugin support for password generation algorithms!

**Comment by bkolada** [comment]
Actually it could be better, my idea was a bit narrow.

**Comment by woyczek** [comment]
Such a plugin exists in KP for windows. Is it possible to reuse the code, or are the plugin framework totally differents ?

**Comment by mstarke** [comment]
KeePass code is incompatible with MacPass. It requires a custom MacPass plugin.

**Comment by cipnt** [comment]
Personally I prefer mnemonic passwords, but agree it would be nice to have multiple options (random characters, random dictionary words, mnemonic,, etc)

**Comment by michaelblyons** [comment]
Duplicate of #458?

**Comment by qjinni** [comment]
@michaelblyons looks like it is

**Comment by mstarke** [comment]
Yup. Duplicate of #458
