### ISSUE TITLE
Focus on search bar after unlock database

### ISSUE THREAD

**Issue by SpecialAgentX** [MacPass/MacPass#519]
Hi,

just like KeePass 2.x for Windows, please put the keyboard focus on the search bar after a database has been unlocked. This would improve my daily work a lot. I usually unlock my database and type some letters into the search bar and then press enter. So I have a very quick access to my entries.

Thank you.

**Comment by madmatt** [comment]
This feature is an opt-in on Keepass for Windows (and is off by default), so ideally would be the same for MacPass. I use it heavily, so might try and contribute it.

**Comment by leighmcculloch** [comment]
Another option is to have any typing in the application window that isn't focused on a text field to take focus on the search box and start typing in it.

**Comment by georgesnow** [comment]
that's interesting concept, but if you are lookin for interim solution you can look #980 I have built a plugin that provides the option if/when it gets incorporated into the main part of MacPass

**Comment by mstarke** [comment]
This was a nasty one. I was pounding my head against the wall for quite some time to figure out why the quite simple solution did not work…

Feature is fully added with dc4cbc6777896b47628b5b1edc4e2223ba7a8462

**Comment by georgesnow** [comment]
@mstarke very cool...so I guess this means I really should make another attempt to incorporate the other relevant features in pull request to macpass 😬
