### ISSUE TITLE
Having Auto-Type to completely send keystrokes, not pasting from clipboard

### ISSUE THREAD

**Issue by mnggh** [MacPass/MacPass#541]
Hi,
currently Auto-Type is pasting the credentials from clipboard.
Is there a way to have Auto-Type sending the complete credentials just with keystrokes instead of pasting??

I know obfuscation is using a mix of both, but this is not what i'm looking for.
Just asking because some sites are not allowing to paste the password.
Thank you very much!

**Comment by mstarke** [comment]
There currently is no way to force this behaviour. I will try to upgrade the system to use as much key strokes as possible.

**Comment by mnggh** [comment]
Very good. I'm looking forward for this feature. Maybe it is possible to be able to change the desired behavior as a setting, too. :)

Thank you very much!

**Comment by mstarke** [comment]
Just an update. MacPass is now able to simulate a lot more characters via key strokes. Currently this only makes obfuscated auto-type a lot better but I am on to adding this support to the normal auto-type system as well.

**Comment by mnggh** [comment]
Wow! Awesome!
Thanks for the update. Can't await the final version.

**Comment by mnggh** [comment]
Anything i can help you with? Maybe try it and give feedback or anything?

**Comment by mstarke** [comment]
0.7.4 was released with auto-type not using the clipboard anymore. The only place where it should be used is when obfuscation is enabled since clipboard usage is part of the idea to prevent key-logging.

**Comment by mnggh** [comment]
Thank you very much!
