### ISSUE TITLE
[Feature] Add configureable delay for Autotype

### ISSUE THREAD

**Issue by iuui24** [MacPass/MacPass#551]
The other issue on my MBP (2007 Core2Duo running Mavericks) is, that the autotype works to fast for the browsers. 
When starting the autotype the first field (usually username) is typed still correctly but the next field (Password) seems to missing some of the first characters.

I do a workaround by adding the {DELAY 150} after the {TAB} for each used entry, which is a little annoying to do this for all other entries in advance. 

Is there eventually a feature to give the tab generally a delay? 
(may the MBP is just simply to slow)

Regards,
Ingo

**Comment by thor84no** [comment]
I've only come across this looking to see if there was a way to speed up the autotype because it's so slow, so I'd appreciate it if it was configurable as a global setting or something. There's certainly no need for a delay on my machine.

**Comment by mstarke** [comment]
I've reduced the delay a bit since it was problematic in certain edge cases (namely copy paste) and since it wasn't using the set buffer but the old pasteboard content.

I'll try to reduce the delay so there's not speed impact but this might break stuff so we need to keep on the lookout.

**Comment by mstarke** [comment]
The current continous release has no delay and types way faster. It seems to work for now but I haven't tested this extensively. Added an option to set the delay is a nice idea but auto type actually supports this via {DELAY=} but it requires a custom string for every sequence. A global setting has the benefit of being transparent but also offers yet another preferences entry which should be omitted whenever possible.

**Comment by bensh** [comment]
A 2018 macbook pro 10.14.5, I'm also finding that the latest version 0.7.9 has a too fast autotype. 
Another macbook running 10.14.4, using macpass 0.6.2 is fine.

Is there a global delay setting on the way? I don't really want to manually adjust all 300 or so of my entries.

**Comment by mstarke** [comment]
@bensh  The Autotype system has changed drastically from 0.7.3 to 0.7.4. Until 0.7.3 it used copy paste instead of actual keystrokes. Can you describe me what type of "too fast" you are experiencing?

Adding a global delay settings seems to be a reasonable solutions since I do not want to slow the system down too much and thus degrade the experience on faster machines.

**Comment by bensh** [comment]
Ok thanks for that, I'll try on 0.7.3 and see what results I get.
Too fast as in, it types the username, but it doesn't seem to correctly register the {TAB} before it starts typing again, meaning both the username and password end up in the username box.

**Comment by mstarke** [comment]
Steam seems to be a particular bad candidate. I can recreate the situation on my machine as well so I'll have a test setup to see if the delay can fix it.

**Comment by mstarke** [comment]
Keepass has built in functionality to handle this sort of thing by using the ```{DELAY=<delay in ms>}``` command and setting a delay in milliseconds that is used for all following keystrokes. MacPass did not support his only a ```{DELAY <delay in ms>}``` was supported and the other delay was mapped the same way. I just updated the parser to allow for the two different versions and it is now possible to customize the sequence via the ```{DELAY=}``` command.

You can use this as the default sequence on the root group and add the delay in front of the key strokes to use it accross all inherited key stroke sequences. I just tried it with a custom sequence for steam ```{DELAY=50}{USERNAME}{TAB}{PASSWORD}{ENTER}```and it worked as intended
