### ISSUE TITLE
"Welcome to MacPass" window should not be shown if started from Finder

### ISSUE THREAD

**Issue by fnkr** [MacPass/MacPass#564]
When I start MacPass by double-clicking on a KeePass database file in Finder the "Welcome to MacPass" window should not be shown.

![](https://cloud.githubusercontent.com/assets/616991/24095373/32106d2a-0d5d-11e7-827f-7e203ca7ecd8.png)

**Comment by m0yP** [comment]
That's weird, because in my case it does not show when opening a file directly.

**Comment by mstarke** [comment]
Can both of you tell me what window restoration settings you're running?

**Comment by mstarke** [comment]
What's even weirder. The MacPass icon is missing from the window.

**Comment by fnkr** [comment]
> Can both of you tell me what window restoration settings you're running?

"Reopen last Database after launch" is disabled.
![](https://cloud.githubusercontent.com/assets/616991/24161395/9587891c-0e64-11e7-8879-149eb9c1997a.png)

**Comment by m0yP** [comment]
Mine's enabled, so it's doing its work correctly. I'm afraid it does not in @fnkr 's case.

![screen shot 2017-03-21 at 6 00 58 pm](https://cloud.githubusercontent.com/assets/22119314/24176281/9f6530e6-0e60-11e7-8669-507f5d52aa23.png)

**Comment by mstarke** [comment]
I wasn't refering to the MacPass setting but those Finder Settings:
![screen shot 2017-03-22 at 10 12 37](https://cloud.githubusercontent.com/assets/58428/24190230/4b60200e-0ee8-11e7-99a9-4e343dcafd85.png)

**Comment by fnkr** [comment]
Here are my settings:

![](https://cloud.githubusercontent.com/assets/616991/24191585/8950b906-0eec-11e7-9a8f-9d0dca5fd3ba.png)

**Comment by fnkr** [comment]
I've tried it out and it seems like the "Close windows when quitting an app" setting causes this behaviour. If I disable it, it works and the "Welcome to MacPass" screen is not shown anymore (after closing and reopening MacPass through the Finder).

**Comment by mstarke** [comment]
What version of MacPass are you running? 0.6.2 binary or a custom build from source?

**Comment by fnkr** [comment]
I'm running the precompiled MacPass 0.6.2 binary.

**Comment by mstarke** [comment]
I'll check the current version if this behaviour is still broken.

**Comment by fnkr** [comment]
@mstarke Had you time to look into this further?

**Comment by mstarke** [comment]
Sadly no.

**Comment by mstarke** [comment]
The missing icon in the window is fixed. The test is something I have to look at.

**Comment by mstarke** [comment]
Issue is also discussed in #908 which is fixed with 0.7.10
