### ISSUE TITLE
Plugins API current status

### ISSUE THREAD

**Issue by weslly** [MacPass/MacPass#582]
Hi, I'm new to obj-c and I would like to teach myself by creating a plugin to add [TOTP](https://en.wikipedia.org/wiki/Time-based_One-time_Password_Algorithm) support to MacPass. 

As the plugin system seems to be quite new, would it be possible to do stuff like adding itens to the entry context menu, new fields to the entry inspector or creating new autotype tags with the current plugin API? If not, would it be better to add it right into the main project and propose a PR with the feature?

**Comment by mstarke** [comment]
Are you sure you want to learn a dying language like Objective-C? Kidding aside. The Plugin-API is very unfinished, actually it's only there to load arbitrary code and that code then can do it's thing all hands off. No hooks for menus, custom UI (apart form the settings view) or anything else.

Since you would need to extend KeePassKit as well I'm more in favour of adding it to the base source so you should extend KeePassKit to support TOTP and then extend MacPass to be able to display correct UI for all of this.

**Comment by mstarke** [comment]
And a very warm "Thank you" for the effort!

**Comment by weslly** [comment]
>Are you sure you want to learn a dying language like Objective-C?

Actually I would rather go with Swift but since MacPass code base is obj-c and I really want this feature, I guess I'll have to learn both 😁  

By the way, I did the same thing with C++ and got this merged into KeepassXC, so here's how it would work: http://github.com/keepassxreboot/keepassxc/pull/519

(It won't look exactly the same since I want everything to fit seamlessly in the current interface)

**Comment by martinl** [comment]
+1 for TOTP support. I'm currently investigating options for developing x509 certificates based master key provider which has a bit more moving parts. I think extending MacPass/KeePassKit to support TOTP would be a good example and starting point for more complex x509 implementation.

**Comment by martinl** [comment]
Also, I think that rumours about Objective-C being dead soon are greatly exaggerated :)
I took this Stanford course a few years ago and it got me started really quickly (had previous C# and Java experience) https://itunes.apple.com/us/course/developing-ios-7-apps-for-iphone-and-ipad/id733644550

**Comment by mstarke** [comment]
@weslly I hope the codebase of MacPass/KeePassKit isn't to confusing to extend. If you have any general suggestions or something you think should be done differently: shoot. I'm happy to get some feedback on the actual architecture since there's certainly a lot to improve!

**Comment by mstarke** [comment]
I'm closing this. The plugin API is evolving but not used by many.

**Comment by georgesnow** [comment]
is it just me?...hehe.

**Comment by mstarke** [comment]
Might be. But at least I am not alone :)
