### ISSUE TITLE
[Feature Request] A few keyboard improvements

### ISSUE THREAD

**Issue by warpkanal** [MacPass/MacPass#603]
I mainly use Cmd+F to find the respective entry I'm looking for, then I copy username and password.
Two improvements would save some keystrokes:

1. Cmd+F works e.g. when the password list is focused, but not when e.g. the notes panel is focused (becaused I just copied some notes from some entry) => would be could if Cmd+F would focus the search field in any case.
2. Having searched for something in the search field, just hitting return should focus the password list / result list again so that I can immediately start copying a username or password. Currently hitting return just selects the text I entered in the search field.

Otherwise thanks for the nice software!

**Comment by chrisrueger** [comment]
Both points are valid, but the 2. is my favourite. In KeepassX you could do Cmd+F and then just use the arrow keys (keyup, keydown) do instantly scroll to the item in the search results. 
In Macpass you need to Cmd+F, then grab the mouse and click into the search result. That is too many steps. An all keyboard solution as described above would be great.

**Comment by toxzic** [comment]
It would be also great if search via title will be automatically done while typing in the main window with the focus moving to the relevant item. Like in KeePass for Windows, for instance.

**Comment by mstarke** [comment]
This is working in Continuous.

Enter/Return in search moves to entries
Down-Arrow in search moves to entries
Keyboard Shortcuts to copy username, password, etc. all work directly on the first hit in searches when results populate the list
