### ISSUE TITLE
Crash on screen unlock

### ISSUE THREAD

**Issue by Sec42** [MacPass/MacPass#616]
I just installed the current continous build and MacPass crashed shortly after I unlocked my screen

Process:               MacPass [20128]
Path:                  /private/var/folders/*/MacPass.app/Contents/MacOS/MacPass
Identifier:            com.hicknhacksoftware.MacPass
Version:               0.6.2 (20170702070756-continuous)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           MacPass [20128]
User ID:               501

Date/Time:             2017-07-25 16:48:59.149 +0200
OS Version:            Mac OS X 10.12.5 (16F73)
Report Version:        12
Anonymous UUID:        117E2CB2-FE77-9C4E-89F3-3AD56660362A

Sleep/Wake UUID:       EDC84501-2575-42EA-BFCC-4C2138736CE0

Time Awake Since Boot: 980000 seconds
Time Since Wake:       27000 seconds

System Integrity Protection: enabled

Crashed Thread:        Unknown

Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       0x000000000000000a, 0x000000010c4e90c2
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Bus error: 10
Termination Reason:    Namespace SIGNAL, Code 0xa
Terminating Process:   exc handler [0]

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000600000a598c0  rbx: 0x0000618000244200  rcx: 0x0000618000076080  rdx: 0x0000600000a598c0
  rdi: 0x0000618000076080  rsi: 0x000000010c516d71  rbp: 0x00007fff53751920  rsp: 0x00007fff53751918
   r8: 0x0000000000000000   r9: 0x0000000000000008  r10: 0x000000010c54cd98  r11: 0x00007f8e7d138510
  r12: 0x0000000000000000  r13: 0x00006180000762c0  r14: 0x0000600000a598c0  r15: 0x0000000000000000
  rip: 0x000000010c4e90c2  rfl: 0x0000000000010246  cr2: 0x000000010c4e90c2
  
Logical CPU:     1
Error Code:      0x00000014
Trap Number:     14

If there is any other debugging I can do, let me know.

**Comment by mstarke** [comment]
That seems like a strange crash since there is no real backtrace. A debug build would help. I'll try to add a debug build to the continuous release if I get to it.

**Comment by mstarke** [comment]
There were problems with locking and file changes discussed in #619 
Please try to use the current continuous build and see if the problem still arises.

**Comment by Sec42** [comment]
I can't really use the continous build since it lacks MacPassHTTP. A quick lock/unlock test at least didn't crash.

**Comment by mstarke** [comment]
MacPassHTTP continuous is supported by MacPass continuous so could you please re-check if the crash still occurs for you?

**Comment by mstarke** [comment]
@Sec42 any news?

**Comment by Sec42** [comment]
No crashes on unlock occurred for me since then (and I have since upgraded to the new/current version), so I guess it should be closed.
