### ISSUE TITLE
Open Keepass 0.4.3 .kdp File with Macpass Error

### ISSUE THREAD

**Issue by Luxas85** [MacPass/MacPass#632]
I have a problem with open my Keepass .kpd File with Macpass. I only get the Error message in german "unknown datafield, password wrong? (1033)"

I sure my password is right.
I am using Keepass for MAC Version 0.4.3

The Error message help has not listed ERROR 1033.

thank you in advance if someone could help me.

**Comment by mstarke** [comment]
Can you try it with the continuous build?

**Comment by Luxas85** [comment]
Problem solved by import to a new Windows Version auf Keepass and than open this file with Macpass.

Thank you very much!

kind regards

FromTHEnewMACPASSuser 👍

**Comment by mstarke** [comment]
MacPass should be able to open a KDB file as well. What kind of encryption did you use for the file?

**Comment by mstarke** [comment]
Had you had any change to look into this?

**Comment by mstarke** [comment]
Sorry to bother you again, I am very interested int the original KDB so it would be super nice if you could try to find out if it had anything special (e.g. was saved with a third party tool, had a special compression or encryption algorithm, had custom icons or anything out of the ordinary)

**Comment by koenpunt** [comment]
I have something similar;

![image](https://user-images.githubusercontent.com/351038/39407562-ecb2cf34-4bc7-11e8-9171-84de92138dd9.png)

But the same database I can open with KeePassX

**Comment by mstarke** [comment]
You seem to have deleted your comment. Did you solve the issue? On your screenshots I see you use the password file as a key file which is a common error users tend to fall for. Remove the file as key file. Key file does not mean password storage it's meant to be a different form of security which can be combined with a password or used solely as the key to a database file. 

___m i c h a e l  s t a r k e____
geschäftsführer
HicknHack Software GmbH
www.hicknhack-software.com

___k o n t a k t____
+49 (170) 36 86 1 36
contact@hicknhack.com

___H i c k n H a c k S o f t w a r e G m b H____
geschäftsführer - maik lathan | andreas reischuck | michael starke
bayreuther straße 32
01187 dresden
amtsgericht dresden HRB 30351
sitz - dresden

**Comment by koenpunt** [comment]
@mstarke I did indeed, because I realised I made the mistake of selecting the database for "keyfile", which obviously was incorrect.

**Comment by DominusExult** [comment]
@mstarke, maybe you need to code an error check there, or rather a confirm dialog when an obvious password file is used in the key file space (obvious being the two file extensions).
"You are using a password file as a key file. Key files are used for extra security and are normally not saved with the extension .... Do you want to continue? Y/N"
It's a bit ugly but as you wrote, it's not uncommon to happen.

**Comment by mstarke** [comment]
@DominusExult this is added. The current version displays this warning in the unlock screen. The set password screen does not check but will be updated ASAP. Created issue for missing feature #1142
