### ISSUE TITLE
[Feature request] Allow groups (with entries) to be renamed

### ISSUE THREAD

**Issue by daften** [MacPass/MacPass#697]
Now when a group has at least one entry, it's impossible to update the group name. Double clicking the group or using enter does not give the group to edit, but the first entry in the group. Right clicking also doesn't give an edit option.

**Comment by mstarke** [comment]
That's an UI bug resulting from selecting the last entry in a group after it was selected. Just select any entry in the group and then the group. I should enable double clicking on the group or fix this in some other way.

**Comment by daften** [comment]
To confirm: you're completely right. That works fine for me. Small bug in comparison to having to use parallels every time otherwise. :)

**Comment by mstarke** [comment]
It's interesting to see that suche seemingly small UI bugs cause so much trouble.

**Comment by daften** [comment]
Yes, but it's partly the user too. I'm expecting a lot from software nowadays and sometimes forget to look further for some patterns. So let's call this at least partially PEBCAK :P

**Comment by mindeffects** [comment]
Was this fixed or did I just find a workaround?
1. Click on the group you want to rename
2. Deselect the first item inside the group by clicking into the empty space below the last item
3. Again, click on the group you want to rename
4. And now you get the group panel to edit the group.
5. Smile.

**Comment by mstarke** [comment]
@mindeffects This is not fixed and the described workaround was mentioned by me in the fist answer (https://github.com/MacPass/MacPass/issues/697#issuecomment-346658310)

**Comment by mindeffects** [comment]
Sorry, @mstarke I must have overlooked that.
Great tool, by the way! Thx!

**Comment by mstarke** [comment]
No need to feel sorry. And thank you!

**Comment by mstarke** [comment]
The current build has changes that do not cause the selected entry inside a group to be visible in the inspector when clicking on a group. Now the group stays in the inspector and you have to explicitly click on the entry to select it.
