### ISSUE TITLE
Downloading MacPass is very confusing for non-devloper

### ISSUE THREAD

**Issue by gagarine** [MacPass/MacPass#700]
If you go on https://mstarke.github.io/MacPass/ it's not super clear how to download the app.

![screen shot 2017-11-25 at 18 39 19](https://user-images.githubusercontent.com/164074/33233031-526d79d2-d210-11e7-9972-7d3dcb58241d.png)

You need to know what is github, what is a pre-build, zip, tar.gz and what is a source code. Most of my friend that need a password manager don't know those stuff. This is very confusing.

It would be better to have one big "download (Free)" button on the top and with a small link "sources  code" that point on github.

**Comment by mstarke** [comment]
The GitHub page for the project is neglected and I started creating a new one under the [MacPass GitHub organization](https://macpass.github.io). There even is a URL (macpassapp.org) but I had to disable it since https wasn't working so I couldn't serve updates.

**Comment by thy1985** [comment]
@mstarke do you need a hand setting up proper ssl for macpassapp.org?

**Comment by mstarke** [comment]
Proper setups isn't the problem. GitHub pages with custom urls and https is. The only solution I've found so far is to use Cloudfare since I want to keep the page in GitHub.

**Comment by thy1985** [comment]
So proper setup actually IS a problem but not on your end ;-)
I am not entirely convinced that cloudfare in the middle would make it more secure..
If you are willing to sacrifice github'cdn capability for the custom domain over ssl you could still use nginx as a proxy, right?

Anyways keep up the good work with macpass - I really appreciate all the effort you put into this! Thus I just chimed in because I saw a chance to maybe contribute a little (as a non-developer) as we had a discussion about donations some time back (#399).

**Comment by mstarke** [comment]
Sorry if the answer came over as rude. There is an issue, yes and I do not want to host the website on a personal server for convenience. I just got the name registered so I can only setup DNS records that do not allow me to use anything in between. YOu're right with your suggestion to use some method of forwarding but that is not possible with the current setup. I see the need to address this issue (hence the new website and the domain) but haven't come around to fix this in a satisfactory way.

**Comment by thy1985** [comment]
No worries! I (discontinued) running a (semi-)professional hosting business. However I've some spare servers left that I use mainly for personal projects. If you want I can offer to set up a proxy (for free) for your macpass project. If you are interested just drop me a mail (see profile, pgp key available).

**Comment by gagarine** [comment]
Oh great, didn't see https://macpass.github.io for the moment google seem to prioritize the old one. But this new website is great, well done.

One things is about the download button that redirect to github, their is a solution to have a direct link to the latest build (without updating the link each releases): https://stackoverflow.com/questions/24987542/is-there-a-link-to-github-for-downloading-a-file-in-the-latest-release-of-a-repo

I got the same issues with github page and SSL. Perhaps you can serve update from a different url and keep the website without SSL until GitHub finally propose let's encrypt for custom domain.

**Comment by mstarke** [comment]
The link to the latest release is not ideal since continuous is the latest release very often but not the version a normal user should download.

**Comment by gagarine** [comment]
Ok, I keep that in mind for when I want to do a very small pet project: "github-release-link.com" that redirect to the last release or last tag...

**Comment by mstarke** [comment]
Fixed with the introduction of https://macpass.githup.io
