### ISSUE TITLE
Small and crucial search hotkey improvements

### ISSUE THREAD

**Issue by restyler** [MacPass/MacPass#707]
I'm amazed how beautiful the interface of MacPass is, but after trying to move from KeePassX (Macbook High Sierra) I quickly realized that search hotkeys support is not working well.

In KeePassX, after doing cmd+F, and typing "github" in search, I can copy password of first result right away by pressing cmd+c, because first result is focused in keepassx by default. And if I want second search result, I can push "down" arrow button and than cmd+c. I don't need to touch mouse and that is very important because I do copypasting of passwords from search a lot every day.
In MacPass, after searching, you cannot copy password of first result by pushing cmd+c, and you even can't use TAB to switch to first result! You need to use mouse to select first result and then you can use hotkeys. 

Keep up the good work, and thank you!

**Comment by lucaceccarini** [comment]
@restyler exact same experience for me. I'm also coming from KeePassX where I was being able to find and quickly copy-paste or just select another record by pressing cursor keys whilst the list maintains focus. I'm not using any integration utilities, so this enhancement would be nice for a happy use of MacPass.

**Comment by mstarke** [comment]
I tested this behavior but it didn't pan out to work as simple as expected. With a bit more time this should be trivial and is indeed a major UX improvement.

**Comment by mstarke** [comment]
The current continuous release incorporates some changes that allow to use the down/up keys to navigate the results after a search. Addionally a "Item" menu item was added and the shortcuts to copy entry information are now available globally and this also for the search results without having to focus the entry table.
