### ISSUE TITLE
Search function doesn't allow to find UUID

### ISSUE THREAD

**Issue by mbrucco** [MacPass/MacPass#708]
I have an entry that refer to an another entry with UUID, I don't remember witch one it is so I tried to get ID and put into search box... it doesn't lookup for UUID field matching.

**Comment by mstarke** [comment]
The Search needs some rework, this is one addition that has to be considered. Others are "search everywhere" to kill all birds with one stone.

**Comment by zipzit** [comment]
All of a sudden I'm seeing search weirdness in the MacPass tool.  In the past, I could search on any portion of an entry, and now the same search I've always used results in null.. 

I've used the search term "thinko" to discover the entry for TD Ameritrade.. (my entry includes the URL `https://www.thinkorswim.com/t/innovation.html` and the words `thinkorswim` contained in the notes for the entry.  It looks like the recent update to MacPass restricts the search function somehow?  Am I doing this right? 

This is not a [UUID (Universally Unique Identifier)(https://en.wikipedia.org/wiki/Universally_unique_identifier) specific search issue, but a general comment on search function as currently released...

**Comment by mstarke** [comment]
Have you selected all the fields in the search bar?

**Comment by mstarke** [comment]
@zipzit any news on the bug?

**Comment by zipzit** [comment]
@mstarke You totally nailed it.. Somehow my default search tool was only using one obtuse data field.  All fixed. Apologies for delay in followup.

**Comment by mstarke** [comment]
The current continuous release has a "Everywhere" option to search in every field. That is:

* title
* username
* URL
* password
* values of custom attributes
* tags
* UUID

**Comment by mstarke** [comment]
I'm closing this since it's captures by the "Everywhere" parameter. The UI and some other aspects of the search should be reworked however.
