### ISSUE TITLE
Custom field for 2FA recovery codes

### ISSUE THREAD

**Issue by Floppy** [MacPass/MacPass#717]
I find myself storing 2FA recovery codes quite a bit now, and while it's quite possible to add a custom field for them each time, it might be a helpful feature to add a custom field for them by default, and show a text area rather than a single line input (as often there are 10 or so codes to store).

**Comment by philiplb** [comment]
I just use the notes field for this. Is this an option?

**Comment by Floppy** [comment]
Oh, that's what I do now, it's just becoming a more common thing.

**Comment by mstarke** [comment]
Do you know you can create a folder with entry templates inside your database, set this as the template folder and just use those templates to create new entries?

Create a group with templates
<img width="909" alt="screenshot 2018-12-06 at 08 41 06" src="https://user-images.githubusercontent.com/58428/49568944-c98de200-f932-11e8-9a1a-b53238f370d7.png">

Set the group as template group in ```Database Settings > Advanced```
<img width="909" alt="screenshot 2018-12-06 at 08 42 28" src="https://user-images.githubusercontent.com/58428/49568982-e9250a80-f932-11e8-8a83-e4bbc350636e.png">

Create entries from templates by pressing the arrow not the add entry button.
<img width="331" alt="screenshot 2018-12-06 at 08 41 36" src="https://user-images.githubusercontent.com/58428/49568943-c98de200-f932-11e8-9475-4764eca1e55c.png">

This will carry over to all KeePass clients. Using a MacPass application setting to add custom fields might be another idea but I do like to use KeePass built-in features. Sometimes they are a bit more cumbersome but the tend to work and are compatible with other clients.

**Comment by Floppy** [comment]
Oooh, no, I didn't know that. That would work. I'll give it a go!

**Comment by Floppy** [comment]
It would be worth pasting that explanation above into the documentation wiki, I'm sure I'm not the only one who didn't know that was a thing :)

**Comment by mstarke** [comment]
I started MacPass as a port of Keepass so I always thought of it as a tool for people that already know keepass and know it's features and the documentation. Over the years MacPass has been picked up by novice users that seem to have no clue about Keepass. Documentation on MacPass thus need to reflect that change in the user base. The wiki is editable by everyone so contributions are welcomed. I'll try to put this in the docs!

**Comment by mstarke** [comment]
Added. https://github.com/MacPass/MacPass/wiki/Templates
