### ISSUE TITLE
Moving / Deleting item in search result list goes back to displaying all items

### ISSUE THREAD

**Issue by NikolausDemmel** [MacPass/MacPass#721]
First of all: Thanks for creating MacPass. It's a very nice KeePass client!

May I suggest a smaller enhancement: I am just manually curating some password entries that I have imported to Keepass from Firefox. Unfortunately, when move or delete an item in a search result list, it goes back to displaying the whole group. Only after hitting enter in the search bar once more does it go back to the search result list. In combination with #515, this makes going through the imported items in a systematic way quite tedious.

**Comment by mstarke** [comment]
Deleting an entry in the search should simply remove to from the search list. If this isn't the case this is a regression. 

By moving you mean via drag an drop? This I need to look into. 

Thanks for the reports since those bugs are as you correctly point out quite annoying.

**Comment by NikolausDemmel** [comment]
Thanks for the quick response.

> Deleting an entry in the search should simply remove to from the search list. If this isn't the case this is a regression.

I delete with cmd+backspace in the search list. Sometimes the search list remains, with the item remaining and now being shown in "Recycle bin" in the "group" column. But sometimes even when for one item this just was the case, for the next the item list jumps back to showing all items.

So it seems it is a regression.

> By moving you mean via drag an drop? This I need to look into.

Yes, I drag and drop 1 item into a different group. For this one it is similar to the deleting. Sometimes the search results stay and only the "group" column for that one item changes, but most times I end up with a view of all items again.

P.S.: The quickest way I found to get back to the selection is cmd+f.
