### ISSUE TITLE
Add a button for "Perform Autotype"

### ISSUE THREAD

**Issue by gagarine** [MacPass/MacPass#722]
You can access "Perform Autotype" from the context menu. Right-click is hard for most user or for lazy person like me... :D. 

Some ideas to perform autotype:
- a button "autotype" button on the list (that will greatly improve the discoverability of the features, if someone don't like the extra colon it can easily hide it). 
- a button on the side panel. I think it should be before the tabs on the right of the entry title.
- double clicking on the entry title in the list

**Comment by mstarke** [comment]
Autotype should already be in the gear menu at the top. Double clicking the entry title is good addition and can easily be added to the existing workflow settings. A separate button inside the table is nothing I would add as this is UI I myself consider as bad.

The only place for a button IMHO is in the toolbar which might be helpful as well for discovering the feature.

**Comment by mstarke** [comment]
The current continuous build has an auto-type button added to the toolbar. It's added as a default button so it should show up automatically.
