### ISSUE TITLE
[Feature Request] Ensure that the password contains characters from every group in password generator

### ISSUE THREAD

**Issue by clobber** [MacPass/MacPass#731]
Both KeePassX and KeePassXC have a handy feature enabled by default (another is noted in #622) that makes their password generator ensure that characters are included from every group, so that upper and lowercase letters, numbers and special characters are guaranteed. In MacPass, too many times have I generated a password that didn't include any uppercase letters or were missing numbers, or no special characters. Perhaps instead of an option checkbox, it could just always happen by default.

<img width="480" alt="screen shot 2018-01-22 at 1 19 26 pm" src="https://user-images.githubusercontent.com/1303132/35239723-eae17c98-ff76-11e7-8674-b2aaaa6226a7.png">

**Comment by FerretDave** [comment]
Yes please, the character types defined should be considered a minimum, rather than optional.

**Comment by mstarke** [comment]
Done in a7469975aded00b32b9a1fde9ad3aa16d998b25c. This is included in todays continuous build.

<img width="463" alt="screenshot 2019-01-31 at 16 10 04" src="https://user-images.githubusercontent.com/58428/52063324-b2562400-2572-11e9-8e88-92cccd88cef7.png">

**Comment by clobber** [comment]
Thank you!
