### ISSUE TITLE
problems with autotype

### ISSUE THREAD

**Issue by ghost** [MacPass/MacPass#733]
Autotype does not work correctly, if I use Russian keyboard layout. In English - all good. This same problem was in old versions of keepass, but later fixed it.

**Comment by mstarke** [comment]
MacPass tries uses the keyboard layout you set to perform Autotype. I think the current solution fails with Russian layout since it might not find the appropriate keys. Thank so for the report, I'll look into it.

**Comment by mstarke** [comment]
The current continuous build includes the fix. I ran tests with Russian keyboard layout and the system seems to work like it should.
