### ISSUE TITLE
Autotype entries trigger for every window in some cases.

### ISSUE THREAD

**Issue by ahouse101** [MacPass/MacPass#736]
If your "Window Title" in the Autotype section contains a pipe character (`|`), that entry will be considered an Autotype option regardless of what window currently has focus. I noticed when an older entry from my database (which was created in KeePass, the .NET version) contained a pipe but triggered even when I was not on the relevant website.

**Comment by mstarke** [comment]
Thanks for the find. This might be due to converting the match to a regular expression and thus making the pip an operator. I'll try to update my tests for matching and find the culprit!

**Comment by mstarke** [comment]
Indeed a pipe will be interpreted as "or" so this does lead to a lot of false positives. Needs to be fixed ASAP.

**Comment by ahouse101** [comment]
Ah, that makes sense. Is difficult to fix? I could look into opening a pull request if there are higher priority issues.

**Comment by mstarke** [comment]
Moved to KeePassKit https://github.com/MacPass/KeePassKit/issues/34

**Comment by mstarke** [comment]
I do not think it's hard to fix. It's a bit more complicated than right now but nothing serious. But it needs to be fixed since this is quite anoying

**Comment by mstarke** [comment]
And if you want to dig into it and open a PR I'd love that! :)

**Comment by ahouse101** [comment]
I'll check it out tonight and take a look, I'm curious anyway. If I can fix it I'll open a PR.

**Comment by mstarke** [comment]
This is fixed now and will be included in 0.7.4
