### ISSUE TITLE
[FeatureRequest] Drag and Drop Items from one to another database

### ISSUE THREAD

**Issue by utatata** [MacPass/MacPass#737]
I need to reduce my database from orphan accounts and would like to restructure my folders as well. I though to do so by creating a new database and drag and drop the still needed account one another.

Running two databases works well (menu -> new database) but drag and drop items does not work. I do not know how complicated this is, because of all of the additional infos (added fields, attached files) but i would appreciate to copy full single items to another database and not to have import/export the full database.

**Comment by dpisano** [comment]
I have been able to do this for some time. It is just not that intuitive. It only works if you drop the item on the folder.

**Comment by mstarke** [comment]
Drag and drop of entries is limited and this is a manifestation of those limits. Currently only the outline accepts entries as dropped items. I have to rework the whole drag and drop system so also support multiple items but haven't come around to it. If this is done dragging across databases will get better as well.

**Comment by georgesnow** [comment]
THANK YOU @mstarke for adding this in 0.7.4! this is life changing. i can now move items easily between folders and databases!

**Comment by mstarke** [comment]
Currently icons will not be moved across databases so beware!

**Comment by georgesnow** [comment]
oh yes, i noticed that. i can live with that since I have folder with all my saved icons

**Comment by mstarke** [comment]
And keep backups. There where some nasty bugs with drag and drop in 0.7.3 which should be fixed in 0.7.4.
