### ISSUE TITLE
Jump in list by pressing letter key

### ISSUE THREAD

**Issue by btxtiger** [MacPass/MacPass#740]
**Maybe a bug:**
In an earlier version of MacPass (I think _0.6.2_ or _0.7.1_) it was possible to jump in the list by just pressing the letter on the keyboard. For me this was a very important feature, because this way I had the same workflow as in Keepass 2.x that I'm using on Windows and Linux.

**Comment by mstarke** [comment]
Nice. I never did investigate what "Type Selection" stands for and disabled is some while back and you found the culprit. It's for selecting by typing D'oh.

I'll try to re-enable this ASAP.

Thanks for the dig-up!

**Comment by mstarke** [comment]
The current continuous build has the fix included.
