### ISSUE TITLE
[Feature request] Support different languages

### ISSUE THREAD

**Issue by loru** [MacPass/MacPass#741]
Hello,

While I love this software, it's kind of difficult to use it when you do not speak english, or simply when english is not your first language and you need to make a big effort to use the software. (lot of people)

Is there a way to support different languages? Based on the os language.

Thanks.

duplicata of https://github.com/MacPass/MacPass/issues/732 ? oops

**Comment by mstarke** [comment]
MacPass is localized in many languages so if your language is supported it will be displayed. 

Currently there is support for English, German, Chinese, Russian, Spanish, Italian and Dutch.

**Comment by mstarke** [comment]
@loru did you get MacPass to use a different language? What system language are you using?

**Comment by loru** [comment]
Hello,
I am very for this issue. It seems that it depends on the system's language, you cannot change the language inside the software.

Thank you a lot.

**Comment by mstarke** [comment]
That is the way how macOS apps work. There is no dedicated language selection inside the app. The language is chosen like you stated based on the system language

**Comment by mstarke** [comment]
> 



> Hello, I am very for this issue. It seems that it depends on the system's language, you cannot change the language inside the software.
> 
> Thank you a lot.

Since macOS 10.15 you can set a different language for each application in the system language preferences.

**Comment by DominusExult** [comment]
In System Preferences -> Language & Region -> Apps
