### ISSUE TITLE
URL with '#' character isn't copied to opened Chrome tab correctly

### ISSUE THREAD

**Issue by JohnGEyles** [MacPass/MacPass#743]
One of my sign-in URLs has a '#' character in it.  When Macpass copies the URL to the Chrome tab it opens, it replaces the '#' with "%23" (I believe 23 is hex for #).

Does Macpass have some reason to need to handle '#' specially ?

**Comment by mstarke** [comment]
The URL is escaped before it is sent  to the browser. This might be unnecessary altogether. I'll have to check if just submitting a unmodified URL works as well.

**Comment by mstarke** [comment]
I've removed the URL-escaping since it should never be necessary. The URL in the database ought to be correctly escaped. If the URL does not contain correct escaped characters MacPass will silently fail opening the URL.

**Comment by JohnGEyles** [comment]
So where does one find the version of MacPass that contains this fix ?    0.7.3 still seems to be the latest version.

**Comment by mstarke** [comment]
Continuous will be built shortly so this contains the fix. 0.8 does need some more time so waiting for an official release might take a bit too long…

**Comment by mstarke** [comment]
Continuous is done so you can grab that one.

**Comment by JohnGEyles** [comment]
Sorry, but I'm not sure what "continuous" means.   I assume it's a work in
progress until you're ready to release 0.8.   But I can't figure out where
to find it.

**Comment by mstarke** [comment]
It's a development snapshot. Unsigned and sometimes a bit more broken than the release but most of the times better since it includes more  bugfixes and more features :)

Take a look here: https://github.com/MacPass/MacPass/releases

**Comment by JohnGEyles** [comment]
Ok, I've been warned.   As long as it doesn't broadcast each decrypted
password to Facebook each time ... :-)

Thanks for getting this fixed.   I've noticed a couple of other login URLs
with '#' in them.
