### ISSUE TITLE
No Custom Fields

### ISSUE THREAD

**Issue by mattdufeu** [MacPass/MacPass#744]
I'm sure this is something I'm doing, so I'm sorry this is probably trivial.

Very simply, in the screenshot I see a "Custom" button when viewing an entry. I have version 0.7.3, "check for updates" says I'm on the latest, but I don't have a "Custom" button.

What am I missing please?

**Comment by mstarke** [comment]
The screenshot is from 0.6 and since 0.7 the custom fields have been moved into the general tab so if you want to add them just scroll down below the tags and UUID field.
