### ISSUE TITLE
Autotype focus always on primary display

### ISSUE THREAD

**Issue by btxtiger** [MacPass/MacPass#746]
**Bug:**
This might be an issue of macOS, I'm not sure.
When I am working with 2 displays, and e.g. have a Chrome window on each:

 **↓** Primary - **↓** Secondary
🖵 --------  🖵
^Chrome1  **^Chrome2**

When I am on **Chrome2** and switch to MacPass to trigger an auto-type, it switches back to **Chrome1 on the primary display**, not to the previous window.

So I guess, the implementation is something like "swich to previous application, then auto-type" and not "switch to previous window and then auto-type". 

I hope my explanation was clear :D

**Comment by mstarke** [comment]
Your explanation is correct. MacPass re-activates the last front-most app but does not direct what window to move to the front. But my understanding is that a correctly-working macOS app will re-focus the last key window regardless of the display. This might be yet another chrome specific bug. Is this behaviour reproducible with Safari or Firefox or any other browser?

**Comment by btxtiger** [comment]
Sorry for my late reply.

I have tested it on Firefox, Safari, Opera and Chrome again and now it works as expected. Don't know if the issue was a side effect of some other software or a patch was just applied on Chrome.
