### ISSUE TITLE
A simplier shortcut for autotype

### ISSUE THREAD

**Issue by gagarine** [MacPass/MacPass#747]
The perform autotype shortcut is not super easy to do:
![screen shot 2018-02-24 at 16 50 46](https://user-images.githubusercontent.com/164074/36632148-e38375de-1982-11e8-9e5b-7edc439891ba.png)

You can of course change it in MacOS settings, but perhaps we can set a better default.

Autotype is the function I'm using the most on MacPass (more than 10 times a day). A lot more in fact that creating/editing new entry for example.

**Comment by mstarke** [comment]
Some ideas about solutions:

`Cmd + A` is a system wide shortcut for `Select All` which I would strongly avoid. It's likely that someone uses it by accident and ends up automatically entering the password inside an application with catastrophic consequences (e.g. a chat application)

`Alt + A` is used in many keyboard layouts to modify the letter A. Shortcuts tend not to soly use `Alt`

`Ctrl + A` sounds good but collides with the HIG as Apple points out `Ctrl` is most of the time occupied by system wide shortcuts and Shortcuts should favour `Cmd` as the first option for a modifier.

Another way would be to use `Cmd + P` since the system default is for printing which is ok to overlay. I think an accidental `Print` is highly unlikely, at least a lot more then `Select All`

Any thoughts?

**Comment by Be8ung** [comment]
It would be indeed VERY fine to have an "autotype" button nebst to the "action" button in the title bar! Me too I am using the autotype feature a lot more than the action feature.

**Comment by mstarke** [comment]
As of #722 the button is added. The shortcut currently is set to `Cmd + T` as this relates more to the "Typing" instead of the "Performing" of the command. The font panel is not used for the app so this is ok to overlay the system default behaviour

**Comment by gagarine** [comment]
mmmh but `cmd + t` is for new tab and `cmd + T` is to reopen the last closed tab.

On my side, I end up using (l = login):
![screen shot 2018-03-13 at 23 44 59](https://user-images.githubusercontent.com/164074/37373823-91f1931a-2718-11e8-8098-daedf8faf230.png)

**Comment by mstarke** [comment]
So you use `Cmd + L` for Autotype and `Cmd + Shift + L` für Global Autotype?

`Cmd + L` is the default for locking the database so this is a conflict in your case.

And again, we're up to deciding what's ok. Locking seems quite more useful to me than creating a tab, so I would argue `Cmd + T` is the better choice. And we still got the idea of `Cmd + P` but it's a never ending game as you might have already guessed.

Which brings me to the conclusion I always favoured. Defaults should be ok for most but for those who do want different settings, there's the remapping option.

**Comment by mstarke** [comment]
Regarding your comment on `Cmd + T` and `Cmd + Shift + T` is this a change introduced in macOS 10.13 ?

**Comment by gagarine** [comment]
It's the standard Firefox shortcut:
![screen shot 2018-03-15 at 18 33 27](https://user-images.githubusercontent.com/164074/37480391-69437aba-287f-11e8-8d94-1353b96396e6.png)

**Comment by mstarke** [comment]
Well then. I give up. There's no easy way. Just customise it to your liking.

**Comment by gagarine** [comment]
Default shortcut are a nightmare.

> So you use Cmd + L for Autotype and Cmd + Shift + L für Global Autotype?

Yes. So why you don't want to use  Cmd + Shift + L for global autotype?

**Comment by mstarke** [comment]
Well, then I would have to move to Cmd + L for Autotype and have to kill Cmd + L for locking. Then locking would be Cmd + Alt + L?

**Comment by mstarke** [comment]
The shortcut for Global Autotype can be easily change by everyone but I did indeed forget to change it in the process of moving to Cmd + T

**Comment by gagarine** [comment]
Oh I see. I never used the looking feature (I close the windows instead, but I mostly keep MacPass open because I'm using global autotype). Using Cmd + Alt + L for looking is good for me.

Shortcuts can be changed for sure, but good global shortcuts hare very hard to find. It's why I think it's important to try to find the "less worst" solution.
