### ISSUE TITLE
[Feature Request] Sort manually

### ISSUE THREAD

**Issue by ad019** [MacPass/MacPass#752]
Provide ability to re-order the records manually. Today I can only sort them automatically by using options like Title/ Username/ Password etc.

**Comment by mstarke** [comment]
Manual sort is a by-product of Drag and Drop which will get updated in the future to support moving multiple entries.

**Comment by ad019** [comment]
Thank you for your response. Looking forward to this feature.

**Comment by mstarke** [comment]
Do not close this as it's not done yet :)

**Comment by Zoidpilot** [comment]
Any updates or workarounds for this? I love the app so far, this is my only request.

**Comment by mstarke** [comment]
It's working in continuous and will get published in 0.7.4
