### ISSUE TITLE
The password and/or the keyfile is wrong (1017)

### ISSUE THREAD

**Issue by bmp** [MacPass/MacPass#778]
Hello,

I am using MacPass Version 0.7.3 (17830) on a macOS High Sierra 10.13.4 (17E199).  I continuously get the following error,

> The password and/or the keyfile is wrong (1017)

I do know that the password and the keyfile are both correct for the database, please do let me know how I can resolve this. 

I have tried the following,
1. Delete the com.hicknhacksoftware.MacPass ~/Library/Caches/ mentioned in #712 as I did not want to delete the other files in the Cache.
2. I have tried clearing stored locations through the preferences pane in MacPass.

**Comment by mstarke** [comment]
Does this error occur all the time or just sometimes? If this error occurs all the time, can you open the file in another KeePass client?

**Comment by bmp** [comment]
This error occurs all the time, the file opens well in a different client.

**Comment by mstarke** [comment]
That's bad. What settings has the file for encryption and key derivation? What kind of key file do you use?

Can you try to remove the key file in another client and just use a password and see if MacPass still fails to open the file?

**Comment by bmp** [comment]
@mstarke, I'm not sure what happened, but after I re-installed MacPass, the same combination is working! It was working fine in KeeWeb from the first attempt.

Thank you for helping out though.

**Comment by mstarke** [comment]
That's on of those bugs that bugs me. No way to know why it happened. But glad you are able to open the file now.
