### ISSUE TITLE
Dublicate Attachments?

### ISSUE THREAD

**Issue by jkroepke** [MacPass/MacPass#788]
Hi,

we are using KeePass in our team. Our mac users use MacPass while other team members using KeePassX.

Since we are attached in MacPass some files to some entries. Other users are unable to open the database anymore.

They get the error "Duplicate attachment found" which I found here: https://github.com/keepassx/keepassx/blob/master/src/format/KeePass2XmlReader.cpp#L904

I have no idea if MacPass allows to generate invalid keepass files or if its a bug in keepassX because they not supported duplicate attachments.

Can you help us?

We are using the lastest version of MacPass and KeePassX

**Comment by mstarke** [comment]
I can reproduce the error. The error only occurs if mutiple items with multiple attachments are present. MacPass will silently dismiss the duplicates and thus create possible data loss. I will fix this ASAP.

**Comment by mstarke** [comment]
0.7.4 is scheduled to be released soon to fix this and another issue related to attachments

**Comment by nopivnick** [comment]
> The error only occurs if multiple items with multiple attachments are present.

a `.kdbx` with multiple entries having only **one** attachment are unaffected?

**Comment by mstarke** [comment]
Yes. Continuous already includes the fix. I'm finishing KDB synchronisation issues to get 0.7.4 finally out the door.

**Comment by rmiller-sgntr** [comment]
@mstarke Any update on 0.7.4 release?
