### ISSUE TITLE
Non .kdb or .kdbx extensions will get changed on save

### ISSUE THREAD

**Issue by mstarke** [MacPass/MacPass#790]
If a file is using an extensions different than .kdbx or .kdb MacPass will change the extension back to .kdb or .kdbx on save.

**Comment by 0rvar** [comment]
Also, if the file is named `.kdbx`, it will be renamed to `.kdbx.kdbx`

**Comment by mstarke** [comment]
I tried to dig into this but there's a world of pain associated with it. The underlying infrastructure of NSDocument tries really hard to force you to stick with pre-defined extensions ans it's getting pretty hard to persuade it to accept other extensions but stick to the underlying format.

About the double-extension, can you open another issue please and provide details on how to reproduce this behaviour?

**Comment by mstarke** [comment]
@0rvar can you elaborate on the duplicate extensions?

**Comment by 0rvar** [comment]
I renamed my kdbx file from ".kdbx" to "password.kdbx", and now it works.
So, it is not an isse for me any more, and I think it's a very unusual use-case to name the kdbx file as I did.

**Comment by veasnalkj** [comment]
I'm interested in this as well, meaning to be able to use non kdbx extensions, if it ever becomes feasible.  Great product, though.  Thanks!

**Comment by mstarke** [comment]
I've tracked this down and a solution is present in master with c0c053d4222b4664f0dec64f7862c9d7d6193135
