### ISSUE TITLE
Improve keyboard navigation

### ISSUE THREAD

**Issue by btxtiger** [MacPass/MacPass#796]
**Is your feature request related to a problem? Please describe.**
I mostly use only the keyboard to navigate between applications. 
- When I start MacPass -> Input focus is on password input ✔
- Should be in the sidebar, where I can navigate to the group ✖
- There is no option to jump in to the entry list. It always needs a mouse click to set the focus on the list. An there is also no option to set the focus back to the sidebar. ✖

**Describe the solution you'd like**
Add keyboard shortcuts to switch the focus
TAB -> Focus from sidebar to list
SHIFT+TAB -> Focus from list to sidebar

**Comment by casmarrav** [comment]
I use search a lot, and it would really help to have a logical way to navigate from the search box to the result list. Or even just be able to press Cmd+Alt+C from the search box when only one result has been found.

**Comment by mstarke** [comment]
MacPass has keyboard shortcuts to move the focus to entry ```⌘⌥E```, inspector ```⌘⌥I``` and groups ```⌘⌥G```. They are located in the ```View``` menu item. Search is started by ```⌘F```. Those work with 0.7.3.

The follwoing enhancements are currently only present int master/continuous and will get released with 0.7.4: All shortcuts to copy information from an entry work even when the search ist still active since the first hit will get used. Pressing the ```Down``` or  ```Enter``` inside the search will move the focus to the entry list where keyboard navigation works.

**Comment by mauron85** [comment]
Maybe it has been changed already in master/continuous, but what I'm personally missing is navigation from search box to search result by simple hitting TAB once. Thank you for this awesome program btw.

**Comment by mauron85** [comment]
Just compiled MacPass from source. Now it's possible to navigate quickly to search results by pressing ENTER key. That's definitely improvement. However I would prefer TAB key and leave ENTER for the search action. This will allow you to change search text without having to use mouse or CMD+F.

So it will work like this:

1. type text into search box
2. press ENTER to initialise search.
3. if you're happy with search result, you'll press TAB to navigate to the result result list
4. if you're not happy with result you can adjust search text and press ENTER again

**Comment by mstarke** [comment]
@mauron85 ```Enter``` is never necessary for a search. Search happens at the moment you type anything. The only drawback not pressing ```Enter``` is that the search term will not be added to the recent searches list. The workflow you describe works sans ```Enter```

1. ```Cmd + F```or click in the search box
1. type text in the search box
1. if you're happy with search result, use ```Enter```or use the arrow keys to in the list
1. you can use all the keyboard shortcuts without ever leaving the search box on the first entry in the results

**Comment by mauron85** [comment]
Yes, you're right. Realized how it works later on. It's almost perfect.
Still would like to see TAB in addition to ENTER to move focus to the
result list. But understand that is just my preference.

Dňa po 5. 11. 2018, 15:17 Michael Starke <notifications@github.com>
napísal(a):

**Comment by mstarke** [comment]
I'm closing this since "most" of your improvements are present in 0.7.4
