### ISSUE TITLE
continuous build of 2018/06/04 does not launch

### ISSUE THREAD

**Issue by amandamana** [MacPass/MacPass#802]
**MacPass cannot be opened because of a problem.**
Check with the developer to make sure MacPass works with this version of OS X

I hope this isn't because support for El Capitan has been dropped:

```
Process:               MacPass [5439]
Path:                  /Applications/MacPass.app/Contents/MacOS/MacPass
Identifier:            com.hicknhacksoftware.MacPass
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           MacPass [5439]

Date/Time:             2018-06-06 12:08:33.348 -0700
OS Version:            Mac OS X 10.11.6 (15G21013)
Report Version:        11

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY
```

**Comment by mstarke** [comment]
I think I made this error now at least a coupe of times. I missed adding a step to actually copy the framework so MacPass is unable to launch because it's not bundled with KissXML.framework. I'll update this right now. The new continuous should work.

**Comment by mstarke** [comment]
Current continous works again. Thanks for the bug report!
