### ISSUE TITLE
Dark Mode Support for Mojave

### ISSUE THREAD

**Issue by Ashok-Varma** [MacPass/MacPass#803]
Hi @mstarke thanks for the awesome app. I am using this from 2014, When i shifted from windows didn't found any other app to open and use my keepass file. This is the only app that's open 24/7 in my mac.

**1. It would be great if this supports dark mode.**

**2. Why don't you release this in AppStore? Any issues with apple ?**

**Comment by mstarke** [comment]
1. It would. I have the tendency to wait until the os is final and do not run betas since I lack the hardware setup to fully support this. It's not ideal, but when 10.14 is official, dark mode support is going to happen for sure.

1. There are a couple:
    1. MacPass is GPL software and thus not compatible with the MacAppStore. I cannot change the license since I do not own all the code that is GPL. **Fix:** Re-write code that is GPLed and not mine, contact all contributors and ask for permission for a licences change
    1. MacPass uses private APIs. This is used for password input. I wanted to leverage the security but needed further changes. **Fix:** re-implementing NSSecureTextField.
    1. MacPass sends keyboard events to other applications which is limited by the sandbox. **Fix:** It's possible to add exceptions but those exceptions need to be specified for each and every application that should receive those events. If I wanted to make this work (and given Apple would even let me do this) I would need to make a list of every app that should support Autotype.

**Comment by Ashok-Varma** [comment]
1. Thanks
2. Huge list of major changes. I hope AppStore gets better to support awesome apps 👍

**Comment by mstarke** [comment]
Since I haven't upgraded yet it's possible to build with color assets that support dark mode which are required for the search bar. I've updated all parts of the Ui to support dark mode so this currently only depends on my system being upgraded to 10.14.

**Comment by timkite** [comment]
Dark mode looks great in the continuous release! There is one issue with it, though: the Notes field. Once you start typing (or view previously entered notes), the notes themselves end up as black text on a dark grey background, rather than white text in dark mode. Every other element flips text colors except that, and when the field is empty the "None" placeholder is the correct light grey text on a dark grey background. Notes are still readable once highlighted.

**Comment by mstarke** [comment]
Notes are displayed correctly now. Continuous release of Macpass now fully supports dark mode.

**Comment by DominusExult** [comment]
Has there been a regression? I've downloaded the continuous build (binary is dated 19th November) and the notes are black against the dark grey background on Mojave.

**Comment by mstarke** [comment]
Did it ever work for you? I have fixed the issue but since the have found out it requires 10.14 to build correctly. Somehow building on 10.13 doesn't fix the issue. Currently Travis doesn't offer 10.14 so it'll be only fixed in the release or when 10.14 is available on Travis.

**Comment by DominusExult** [comment]
I *just* switched to Mojave and updated my old continuous version I had running. As I followed the comments somewhat I thought this was working correctly.
I'll just roll my own build via xcode then ;)

Thanks!

**Comment by bertoost** [comment]
Nice!! Should be released!!
