### ISSUE TITLE
The option to reveal password should be temporary

### ISSUE THREAD

**Issue by tpluscode** [MacPass/MacPass#806]
**Is your feature request related to a problem? Please describe.**

The feature show password is persisted once they have been shown and the setting also affects all entries.

**Describe the solution you'd like**

Passwords should go back to hiding as soon as possible

**Describe alternatives you've considered**

Here are some ideas:

- only show password of the current entry but not all at once
- hide the password when entry is changed
- hide the password when the app is closed/minimized
   - or at least when the database is locked

**Comment by mstarke** [comment]
Behaviour is as suggested and seems reasonable:

Password is hidden whenever the entry changes. This also hides the password on lock/unlock of the database.
