### ISSUE TITLE
macOS Mojave: AutoType isn't working anymore

### ISSUE THREAD

**Issue by jonny0303** [MacPass/MacPass#808]
**Describe the bug**
MacPass' AutoType in MacOS Mojave is not working anymore.

**To Reproduce**
1. Go to any input field.
2. Click on MacPass AutoType (^⌘A)
3. Nothing happens (password should be typed)

**Expected behavior**
Password should be typed.

**Screenshots**
Nope.

**Desktop (please complete the following information):**
 - macOS: macOS Mojave 10.14 Beta (18A314k)
 - MacPass Version 0.7.3 (17830)

**Additional context**
Rights in "Settings -> Security -> Privacy -> Accessibility -> MacPass" are granted.

**Temporary workaround**
Copy username and password with shortcuts is working furthermore: (⌥⌘C for password)

**Comment by mstarke** [comment]
MacPass shouldn't require accessibility features since it's sending keyboard events via system APIs. Newer releases of macOS tent to continently break Autotype

**Comment by mstarke** [comment]
Using MacPass Continous (linked to 10.13) ask for Accessibility access the first time Autotype is used. If granted everything works as expected. If access was not granted, Autotype fails sliently. I will have to update this to use the additinal APIs added in 10.14.

Nonetheless, I cannot reproduce the "does not work" aspect of you issue.

**Comment by jonny0303** [comment]
I'm on public beta 9 now and tested it again. Seems to work now, so I will close this issue now with MacPass 👍
