### ISSUE TITLE
Verify Download?

### ISSUE THREAD

**Issue by 88-percent** [MacPass/MacPass#810]
Can someone point me to a way to verify the zip download - a PGP signature or SHA checksum perhaps?

I don't have Xcode installed, so it looks like I don't have the option of compiling from source.

**Comment by mstarke** [comment]
sha1 hashes are provided for continuous builds. Official releases might get them as well.

**Comment by 88-percent** [comment]
Great to hear. It is safe to use the latest continuous build, or do you recommend waiting until for the sha hashes for the official release?

**Comment by mstarke** [comment]
The official builds are signed and check by the gatekeeper if you set your system setting to only allow for signed apps to be loaded. There is no additional security from what I understand of the process by providing sha hashes for those.

The continuous build is being used by me on a daily basis and if any bugs occur I tend to fix them ASAP so it **should** work without problems.

**Comment by mstarke** [comment]
I added sha hashes to all 0.7.x releases so you're good to go if you want to use 0.7.3

**Comment by 88-percent** [comment]
Sorry for the delay in my reply. 

Thanks so much for this. This makes me feel alot more comfortable with my decision to switch to MacPass!
