### ISSUE TITLE
auto-type: how to adjust existing window associations

### ISSUE THREAD

**Issue by FrankMittelbach** [MacPass/MacPass#817]
**Describe the bug**

Maybe not a bug but just my inability to find the correct  approach (or some missing info in the doc).
I have a db that contains many entries with several window associations to cover the use with different browsers on windows.

If I open this db in MacPass these are nicely shown in inspector, but all I seem to be able to adjust is the auto-key sequence (which should be fine) but not add or modify the possible matching lines.

It seems to work in cases where there are no window associations listed (at least in the few cases I tried) but not on those that have explicit ones.
Which kind of makes sense as they do not fit the window title in the OSX browser.

So my question or problem is: how to add a further association or change one of the existing regular expressions.

**Expected behavior**

A way to edit / add  windows assocs

**Desktop (please complete the following information):**
 - macOS: 10.13.5
 - Version 0.7.3

**Comment by mstarke** [comment]
This might be a place for better UX. You can add additional associations by clicking the little Plus button below the list of window associations. If the buttons do not show up, you can scroll the view to make them show up. Below the buttons there's a combo-box that will display the selected window associations title. Here you can type and edit the value or you can simply select a window title from the drop down list. In the list, MacPass will display all currently known window titles for easier access.

**Comment by FrankMittelbach** [comment]
arrg ... sorry for the noise then, but the plus/minus (not so little really) didn't show after installing the tool ... maybe a problem of the default window size, but for me it looked like:

<img width="324" alt="bildschirmfoto 2018-07-27 um 16 03 14" src="https://user-images.githubusercontent.com/1062981/43325423-ebb6d78a-91b6-11e8-9fc3-9237704fc1da.png">

and only with your hint I realized that I can move the split so that it showed the buttons. And even then I initially stopped once the button showed without making it even bigger so that the edit box came up too.

Maybe that should be prevented, though not sure how best (perhaps simply by telling in the documentation what you said above with the warning that based on window size they might be hidden).

**Comment by mstarke** [comment]
I'm closing this since the actual issue is solved. For UI enhancements, a new issue should be created.

**Comment by PatrickTT** [comment]
Thank you so much!
I was searching for a way to edit the associated windows. Now I found out that the field just was hidden! 
The UI is lacking a bit there IMHO because you can't see that something's hidden under the notes field.
