### ISSUE TITLE
Wrong UID Format when duplicate an entry with the action "set Password as Reference"

### ISSUE THREAD

**Issue by sudo-s** [MacPass/MacPass#825]
Hello,

while duplicate an entry with the action "set Password or Username as Reference", the uid is in wrong format:
for instance the Password field contains:
{REF:P@I:5ECB3947-D47B-CB4D-81E0-03DE8A1B72DE}
But this reference does not work, when the file will be opened in the application keepass for windows.
the reference has to be like this:
{REF:P@I:5ECB3947D47BCB4D81E003DE8A1B72DE}

macpass version is 0.7.3 (17830)

thanks for your efforts
and BR

**Comment by mstarke** [comment]
Fixed in continous.
