### ISSUE TITLE
No Global Autotype in macOS Mojave

### ISSUE THREAD

**Issue by Neo23x0** [MacPass/MacPass#830]
The global autotype doesn't work in macOS Mojave 10.14 working with MacPass 0.7.3

I tried to deactivate the checkbox exiting the settings menu and activating it again, but that doesn't work. 

Preferences > Integration > Enable Global Autotype

**Comment by Neo23x0** [comment]
Ah, I used the "continuous" version https://github.com/MacPass/MacPass/releases/tag/continuous

Restarted the App and suddenly macOS told me that it needed permissions:

<img width="482" alt="screenshot 2018-09-25 at 11 14 07" src="https://user-images.githubusercontent.com/2851492/46004923-65d67580-c0b4-11e8-96c2-320e09c7ced5.png">

That didn't happen the first time that I closed and restarted the App. 

<img width="665" alt="screenshot 2018-09-25 at 11 14 27" src="https://user-images.githubusercontent.com/2851492/46006226-4bea6200-c0b7-11e8-8d5d-9bffc4b7aeff.png">

After re-allowing the App in the Security & Privacy > Privacy > Accessibility section, the global auto-type works again as expected.

**Comment by mstarke** [comment]
Duplicate of #808
