### ISSUE TITLE
Global setting to open new files in tabs instead of windows

### ISSUE THREAD

**Issue by pmhausen** [MacPass/MacPass#834]
**Is your feature request related to a problem? Please describe.**
Just a convenience request. I moved from KeePassXC and while your application is definitely better adapted to the Mac environment there are some things I am missing.

**Describe the solution you'd like**
Opening another .kdbx file while MacPass is already running creates a new tab instead of a new window. There should be a preference setting to toggle this and the current behavior.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Kind regards,
Patrick

**Comment by mstarke** [comment]
The behaviour is system defined. MacPass prefers tabs since feedcd56aca2efb167a6a1387026e7a2c14e6fd2

**Comment by pmhausen** [comment]
MacPass will open new files in tabs if the setting in System Preferences -> Dock is set to "Always". Unfortunately I don't want all applications to use tabs by default, only particular ones. Any chance you might reconsider this?

Kind regards,
Patrick

**Comment by mstarke** [comment]
MacPass 0.7.3 prefers separate windows. If you leave your system settings on "In Full Screen Only" or on "Manually" you can get Tabs when pressing ```⌥``` while Opening a File via the menu. As stated, the upcoming 0.7.4 has the behaviour changed to prefer tabs.
You can change this manually for 0.7.3 by setting a default value via ```defaults write com.hicknhacksoftware.macpass AppleWindowTabbingMode always```

**Comment by pmhausen** [comment]
Perfect! Thanks! :)
