### ISSUE TITLE
SHA1 is used to verify the downloads

### ISSUE THREAD

**Issue by brampat** [MacPass/MacPass#836]
**Describe the bug**
SHA-1 is used on the downloads-page to let users verify their download

**To Reproduce**
1. Go to the download-page
2. Click on the download for the SHA-file
3. Click on the download for the Installation file
4. The SHA-file is a SHA-1 hash

**Expected behavior**
For verification, SHA-256 is used

**Desktop (please complete the following information):**
All

**Additional context**
For more information about issues with SHA-1 and consequences on file verification:
https://shattered.io/
https://www.coindesk.com/who-broke-the-sha1-algorithm-and-what-does-it-mean-for-bitcoin/
https://www.theverge.com/2017/2/23/14712118/google-sha1-collision-broken-web-encryption-shattered

**Comment by mstarke** [comment]
Done.

**Comment by brampat** [comment]
+1 Awesome response time

**Comment by mstarke** [comment]
Low hanging fruit. 😉
