### ISSUE TITLE
Move entries from group to subgroup

### ISSUE THREAD

**Issue by TofPlay** [MacPass/MacPass#837]
**Is your feature request related to a problem? Please describe.**
I put some entries in group and I would like to create a new subgroup for some entries but I can not move the entries with a drag/drop from the group to the subgroup

**Describe the solution you'd like**
Can drag/drop entries from a group to another group or subgroup

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by mstarke** [comment]
Drag and Drop works only for single entries. So you can move them but only one by one. Adding support for multiple selected entries is on the roadmap.

**Comment by TofPlay** [comment]
@mstarke thanks for your reply 
> Drag and Drop works only for single entries. So you can move them but only one by one. 

Ok 🙂
> Adding support for multiple selected entries is on the roadmap.

Excellent 👍 🙂

**Comment by mstarke** [comment]
The current master branch now has drag and drop for multiple entries as well as multiple groups implemented.
