### ISSUE TITLE
[Feature Request] Password generator dialog remains open

### ISSUE THREAD

**Issue by FerretDave** [MacPass/MacPass#838]
**Is your feature request related to a problem? Please describe.**
scenario - changing a password, I copy and paste my current password into another app, and then click generate password and 'use password', then copy and paste the new pw into the other apps password change dialog. If that newly generated password is not acceptable (see #831) then I have to try again, however I need to extract the previous password from MacPass, as the generate has just overwritten the pw with an invalid one.

**Describe the solution you'd like**
The 'generate password' dialog to stay open when focus moves away from MacPass.
This would then let me ensure that the new password has been accepted by the other app before clicking 'use password'.

**Describe alternatives you've considered**
Alternative is to generate password, copy it, and then past that into the other app, and then once it's accepted a valid pw, return to MacPass and paste the new password back in.
However that seems counter intuitive (telling MacPass the password *it* generated for me), and risky (the copy buffer is the only place my new password is stored temporarily).
Alternatively, what I do currently is paste the current pw into the notes field, and then generate and use a new pw. If I need to retry, the old pw is quickly available without having to go into the history.
Yes, that is only really a few more mouse clicks, but for the sake of this dialog box for generate password staying open, it saves effort.

**Additional context**
Ensuring new passwords met *minimum* requirements would reduce the need for this, however unless those minimums are known *before* changing the pw, this would still be of use.

**Comment by mstarke** [comment]
All popups in MacPass now stay open if you interact with anything outside of MacPass. Feature is added in 3f43a061b885055f7a4064e0a7146dba7b3a0fb8 and should be in Continuous ASAP
