### ISSUE TITLE
[Feature Request] - Please Add a possibility to lock an entry (READ ONLY)

### ISSUE THREAD

**Issue by swinxx** [MacPass/MacPass#841]
When creating a new entry you can generate a new password with the GENERATE BUTTON. Great! When you have created a new password, it would be great when this can be locked (read only) cause when i navigate to that entry later, it is dangerous not to hit that button by accident!

the same thing should also be implemented for the whole entry. just a lock button to make all fields read only. that would help to protect your important entries!

It would also be helpful to hide the (-) button when a newly added field is filled, and also hide the generate button when "entry lock" is turned on! 

Thank you for your effort

**Comment by mstarke** [comment]
This is a planned feature that was scrapped earlier in favour of the current way. Hiding field that aren't set in the read-only view is also considered. See #791 and #47
