### ISSUE TITLE
[Feature Request] Option for Exit-On-Close

### ISSUE THREAD

**Issue by lambdaupb** [MacPass/MacPass#843]
I don't need to keep MacPass running after closing the main window.
It starts very fast and I want by Dock clean.

It would be nice to have an option to quit MacPass when closing the main window.

**Comment by mstarke** [comment]
Is pressing ```Cmd+Q``` no option for you? I am hesitant to vent this option in the UI. I might consider adding a default that is just accessible via the command line (```defaults write```)

**Comment by mstarke** [comment]
In bfeb71585dcb2c85807bd0296a620b6688ce2678 an continuous includes a setting to enable the desired behaviour. To enable run
```
defaults write com.hicknhacksoftware.MacPass QuitOnLastWindowClose -boolean YES
```

and to disable:
```
defaults write com.hicknhacksoftware.MacPass QuitOnLastWindowClose -boolean NO
```
or
```
defaults delete com.hicknhacksoftware.MacPass QuitOnLastWindowClose
```

**Comment by lambdaupb** [comment]
Thanks! That's perfekt.
