### ISSUE TITLE
Open custom URLs

### ISSUE THREAD

**Issue by Niko-CZ** [MacPass/MacPass#844]
Hello KeepassXC team,
I have question related to opening of custom URL. My idea was to use one database for MacOS and Windows and have quick URL app opening for both. 
On Windows as you know there is standard format for applications like "cmd://<app.name> <parameters>". 
So I have created custom URL handler for Mac OS, which is checking app and redirecting parameters to chosen application. F.e. strings like "cmd://putty.exe -ssh {NOTES} -X -l {USERNAME} -pw {PASSWORD}" are redirected to iTerm with format change and password auto-type.
I found on this forum that this will not work in KeepassXC as I need to put "cmd://open" before URL, what will make it at last "cmd://open cmd://putty.exe ..." and will not work.
Is there way - how I can switch KeepassXC to consider URLs in the same way Mac OS do. So they will be opened by related handler?

**Comment by mstarke** [comment]
You might have used the wrong repository. This is the MacPass repo. Keepassxc is over there https://github.com/keepassxreboot/keepassxc

Regarding custom URL schemes and MacPass. If you use registers urls, MacPass will open them e.g. ssh:// should launch the terminal. Support for cmd:// is currently not planned but it might be useful to get the feature aligned on all platforms.

I never dived into the details about cmd:// hence no progress has been made. But I'm onto changing the Autotype system so support for cmd:// might fall off the wagon.

**Comment by Niko-CZ** [comment]
Most probably opened too much GitHub branches for Keepass)
For MacPass items with URL "cmd://" are working fine! Custom URL handler is taking the control and forwarding to related application.
Thank you for reply and sorry for disturbing.
