### ISSUE TITLE
Can not open newly created database in continuous version

### ISSUE THREAD

**Issue by miluoalbert** [MacPass/MacPass#847]
I am using the latest released MacPass continuous version on a macOS Mojave 10.14 (18A391). 

I just create a new database with a new password and keyfile. Then, when I open it with the generated keyfile and password, I continuously get the following error:

**The password and/or the keyfile is wrong (1017)**

I had tried to create a new database several times to make sure I had used the right password and the right keyfile. Even though, I still get the error message and can't open database anymore.

**Comment by mstarke** [comment]
Thanks for the catch. This is a regression in refactoring. Added more tests to cover them in the future and fixed continuous is comming up.
