### ISSUE TITLE
Can't edit Window Associations in 0.7.3

### ISSUE THREAD

**Issue by astingengo** [MacPass/MacPass#850]

**Comment by astingengo** [comment]
The + button just add the `Window Title` but I can't edit it

**Comment by mstarke** [comment]
Use the combo box below the list to edit the selected association. See #814

**Comment by mstarke** [comment]
Use the combo box below the list to edit the window title. Duplicate of #817

**Comment by astingengo** [comment]
Sorry and thank you.
