### ISSUE TITLE
Dark Mode: Notes TextBox text is black on dark grey

### ISSUE THREAD

**Issue by lambdaupb** [MacPass/MacPass#858]
In Mojave Dark Mode and version `Version 0.7.4 (20181201151215-continuous)` the content of the Notes Text Box is black on an almost black background. This is very hard to read.
If the text box is empty, the `None` shown is a light grey and readable, but actual content is black.
<img width="355" alt="notes" src="https://user-images.githubusercontent.com/1890613/49751695-5c6daa00-fcae-11e8-86bc-2e17d52bee0f.png">

The text colour should probably just use the default colours and change with the OS UI theme.

See #803.

**Comment by DominusExult** [comment]
As you referenced #803, you've read that this is a known issue ;)

**Comment by lambdaupb** [comment]
whoops, cac974a30e4ccabdc6a4681fb00671fc3caca1d6 seems to be a related change.
Just need a new continuous build release.

**Comment by mianos** [comment]
This seems to have come back, the continuous build now has black on grey again.

**Comment by mstarke** [comment]
The issue is present when building with macOS 10.13. Building on macOS 10.14 fixes this. This will get vented in 0.7.3

**Comment by mstarke** [comment]
Continous is now build with Xcode 10.2 under macOS 10.14 so it contains the fix as well.
