### ISSUE TITLE
0.7.4 release?

### ISSUE THREAD

**Issue by error401de** [MacPass/MacPass#860]
Hi,

I'm really wondering when macpass 0.7.4 will be released. There is a fix in there i'd really like to have (https://github.com/MacPass/MacPass/issues/799) and the last release has been quite a while.

Thanks!

**Comment by mstarke** [comment]
I'm on it. I'll get released. Soon. 2018 is my goal so I got at least a couple of days left :)

**Comment by takkk** [comment]
not anymore ;-)
i'm waiting for the release, too. looking forward getting the fixes. thank you!

**Comment by kevinpapst** [comment]
+1 
The last stable release is from November 2017 and 300 commits since then.
@mstarke seems you like development more than releasing MacPass?! ;-)

**Comment by carlos-sarmiento** [comment]
Any update on this? I'm having issues using my shared database because of #788 which was fixed in 0.7.4

**Comment by mstarke** [comment]
I am prepping it, waiting for a localization contribution but this shouldn't take that long. So a release in 2019 is getting quite possible :)

**Comment by pchaussalet** [comment]
@mstarke any update on that contribution?

**Comment by mstarke** [comment]
Tagged and wrapped, I'm updating the infrastructure right now so the auto updater will be able to pick 0.7.4 up.

**Comment by kevinpapst** [comment]
@mstarke Update went very smooth, I like the new dark mode.
Thanks for the release!

**Comment by mstarke** [comment]
Please do not forget to update to 0.7.5 since 0.7.4 has a serious bug when having used search…
