### ISSUE TITLE
[Question] Where is the settings file?

### ISSUE THREAD

**Issue by kud** [MacPass/MacPass#861]
Hello,

I'd like to back the macpass settings up but I don't find any file about it in `~/Library/Application Support/MacPass/`

Any idea?

Cheers.

**Comment by mstarke** [comment]
Preferences for macOS are stored by a defaults daemon. On older OS versions, the files were written to ```~/Library/Preferences/```. If you take a look, ```com.hicknhacksoftware.MacPass.plist``` is also present there. If you want to back up or modify preferences, the recomended way is to use the ```defaults``` command on the terminal. If you want to print out all defaults in XML format, use ```defaults read com.hicknhacksoftware.MacPass```. You can export them via ```defaults export``` and import them back via ```defaults import```. Take a look a the man page for ```defaults``` to get a detailed description on how to use it.

For your purpose, ```defaults export com.hicknhacksoftware.MacPass /path/to/my/export/file.plist``` and a corresponding ```defaults import com.hicknhacksoftware.MacPass /path/to/my/export/file.plist```should do the job.

You can open and edit the file via Xcode.

**Comment by mstarke** [comment]
Just to clarify: Do not use the ```.plist``` file located in ```~/Library/Preferences/```. Those files should be considered caches. Everything you want to do with preferences should be done via ```defaults```.

**Comment by kud** [comment]
Amazing. `defaults` way is the best way in my opinion to add/modify settings via a script instead of backing up a file.

Thank you for your clean explanation, it helped me a lot. :)

Have a great Christmas @mstarke 🎄
