### ISSUE TITLE
Need a record of the previous password

### ISSUE THREAD

**Issue by coolicer** [MacPass/MacPass#869]
**Is your feature request related to a problem? Please describe.**
When I change the password, I generate a new password and the old password is gone. When you go to the web page, you need to fill in the new password and the old password.

**Describe the solution you'd like**
So I need the history.

**Comment by mstarke** [comment]
The old password will get stored as a history entry. You can select an entry, then choose "Show History" from the action or context menu and a list of old records for this entry will get displayed in the entry list. There you can use your old password.

**Comment by mstarke** [comment]
This requires you to enable history support for the database in the advanced database settings.

**Comment by coolicer** [comment]
Ok, I know.Thank you. @mstarke
