### ISSUE TITLE
Icon Download should check HTML header

### ISSUE THREAD

**Issue by nalt** [MacPass/MacPass#871]
**Is your feature request related to a problem? Please describe.**
The icon download in MacPass just checks for the favicon. Many websites don't have this any more, so MacPass fails to find an icon. The "modern" standard way is to include a tag "link rel=icon" tag into the HTML header. (There are more possible tags.)

**Describe the solution you'd like**
MacPass should download the website, check for the "link rel=icon" tag and then download the given icon.

**Comment by mstarke** [comment]
I've got this idea too but the current system was reasonably easy to implement. Parsing html for icon loading is bit more cumbersome. Another idea was to rely on a favicon service to do the hard lifting.

**Comment by nalt** [comment]
@mstarke do you know of a favicon service that is dependable and has an open API?

**Comment by mstarke** [comment]
Nope. But I just stumbled over a Swift library (https://github.com/leonbreedt/FavIcon) that does a lot of heaving lifting. I might add this and use it as an excuse to finally start learning Swift and since 5.0 should ship with a stable ABI this might be a good time to jump on board.

**Comment by mstarke** [comment]
Favourite icon download was enhanced to support duckduckgo.com's web service for fetching favicons. This is an opt-in but should fix the issue although it reduced privacy since all traffic is routed through duckduckgo.com when downloading icons.

**Comment by mstarke** [comment]
feature was added via PR  #1073
