### ISSUE TITLE
Multiple URLs for a single entry

### ISSUE THREAD

**Issue by notoriousturtle** [MacPass/MacPass#879]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Allow multiple URLs for a single entry. Particularly helpful for domain credentials for example. Where those credentials are associated with multiple sites.

**Describe alternatives you've considered**
Thought about using tags, but that only matches titles, and titles can be a bit generic at times.

**Comment by mstarke** [comment]
If you use the same credentials for multiple sites you have two options right now:

1. Create multiple entires that use a single entry as reference for credentials (password/username) MacPass has no UI support for references but you can create them manually (see https://github.com/MacPass/MacPass/wiki/Field-References)
1. Create a single entry and add multiple window associations to match more than one site

**Comment by mstarke** [comment]
I'm closing this since the feature is possible with the current setup.
