### ISSUE TITLE
Autotype for Gmail and Evernote

### ISSUE THREAD

**Issue by FrankKooij** [MacPass/MacPass#882]
Some sites such as Evernote and Gmail are changing their log-in behavior from showing username and password on a single page to postponing the display of the password field until after a valid username has been entered. This is incompatible with Autotype. Not only does this prevent MacPass from logging in using Autotype, it results in your password being entered in plain text in the username field. A workaround could be to set a delay between submitting the username and the password. This should give most websites enough time to validate the password and reveal the password field.

**Comment by mstarke** [comment]
You can add a delay by using a custom Autotype sequence. I just used ```{USERNAME}{ENTER}{DELAY 2000}{PASSWORD}{ENTER}``` on the Gmail form an it works. The delay is in milliseconds so 2000ms is a 2s delay. You might have to tweak this value for your setup.

**Comment by mstarke** [comment]
About the password input being send to the wrong form fields: I have thought about adding a special "pause" modus to aks the user every time a password is going to be filled and showing exactly where but this is a rather complex feature so I wasn't sure it's doable in a reasonable timeframe.

**Comment by FrankKooij** [comment]
@mstarke, thanks. The sequence that you used for Gmail, works for Evernote also.

**Comment by mouzzi** [comment]
```
~~~~
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
