### ISSUE TITLE
Global autotype stops working after modifying integration options

### ISSUE THREAD

**Issue by notoriousturtle** [MacPass/MacPass#883]
**Describe the bug**
global autotype stops working.

**To Reproduce**
Try your global hotkey - works, tick.
Open preferences > Integration. Uncheck (or check) "Include Entry Title for matches". 
Try your global hotkey - does not work.

**Comment by mstarke** [comment]
This behaviour should have been fixed. I'll try to to investigate. Could you tell me what version of MacPass you are encountering this issue on?

**Comment by mstarke** [comment]
I was able to get the same error but could not reproduce it afterwards. This seems to be a strange bugs. I'll have to dig into this. A restart of MacPass should fix it but this is not correct.

**Comment by mstarke** [comment]
I did track this down. The issue would arise, only after the preferences window was opened a second time or the integration tab was clicked upon a second time. The view then set the hotkey internally which resulted in the deregistration of the hotkey.
