### ISSUE TITLE
Tabs not working - New databases always open in new window

### ISSUE THREAD

**Issue by georgesnow** [MacPass/MacPass#885]
**Describe the bug**
When opening a second database it always opens in a new window. even if i open 2 databases and put them into one window as tabs. I close the app and re-open only 1 database will open. And upon opening the second one (Open Recent or Open). I still get the same behavior.

I did try:
defaults write com.hicknhacksoftware.macpass AppleWindowTabbingMode always
 (i did a default read and this option doesn't seems exist)
"The domain/default pair of (com.hicknhacksoftware.macpass, AppleWindowTabbingMode) does not exist"

**Expected behavior**
When opening a second database after modifying the preferences new databases would open in new tab (instead of a new window). And if 2 or more databases are open and put in tab mode and MacPass is closed upon reopening both would open and be in a tabbed window.
**Desktop (please complete the following information):**
 - macOS: 10.14.3
 - Version 0.7.3

**Comment by mstarke** [comment]
using ```defaults write com.hicknhacksoftware.macpass "AppleWindowTabbingMode" "always"
``` should work!

**Comment by georgesnow** [comment]
awesome that did work! the only i did notice though. even if you have 2 or more databases open it only defaults to opening one of them not multiple databases on relaunching MacPass.
is the intended the behavior?

**Comment by mstarke** [comment]
If state restoration is working correctly, this should not happen but there might be regression with 10.13 and 10.14 so I'll have to investigate. Do you have the same undesired behaviour with the continuous build?

**Comment by georgesnow** [comment]
not sure, i will have to try download and try the continuous and check. i will try and  get back to tomorrow.

**Comment by georgesnow** [comment]
i haven't used the continuous build in long time. I thought i read somewhere you have to uninstall standard release build before using the continuous. is that true and is anything else to flip between the two?

**Comment by georgesnow** [comment]
tested on the continuous build. same behavior. I opened to 2 databases using tabs. first, both locked. quit MacPass re-opened only the first opened database displayed. Tried with both databases unlocked. Quit and re-opened same thing. Only the first open databased loads.

**Comment by georgesnow** [comment]
i just tested on 0.7.4 same thing. it only re-open the left most tabbed database (or it might be the first)

**Comment by mstarke** [comment]
I tried to reproduce this an on my system every tab is restored. I have to dig into this a bit more…

**Comment by georgesnow** [comment]
ok no worries. let know if there is something you want me to test. i can send you my settings as well if that would be helpful. 

i did confirm after upgrading that the setting is set to "always"

>defaults read com.hicknhacksoftware.macpass "AppleWindowTabbingMode"
always

**Comment by georgesnow** [comment]
I have small update to this. I had to “Force quit” macpass yesterday with 2 databases open with tabs. I re-opened macpass and both databaes olened in tab view. However, this is the only way I have gotten it to work. 

I am wondering if there is a OS setting I have changed that is effecting seeing as it works for you. I haven’t tested it on my other 2 macs, but I will do that to try narrow down the issue.

**Comment by mstarke** [comment]
Can you try an delete the defaults key? 
```defaults delete com.hicknhacksoftware.macpass "AppleWindowTabbingMode"```

MacPass 0.7.4 has the tabbing mode set to preferred on the window so this should work out of the box without any additional settings.

**Comment by georgesnow** [comment]
hmm...not change. and I have also tried on my other Mac running 10.14.3 and MP 0.7.6. same issue.

**Comment by georgesnow** [comment]
another note so I opened the plist in Xcode. and just out of curiousness I watched after I ran the defaults write command. saw it add the tab mode. but not long after it with no intervention I would see the entry get deleted.

**Comment by georgesnow** [comment]
Old stale issue. Closing.
