### ISSUE TITLE
Tags are not searchable

### ISSUE THREAD

**Issue by monatsend** [MacPass/MacPass#886]
### Description
When you search for Tags they don't show up in the search result.

### How to reproduce:
1. Add a Tag to an entry
2. Search for it in the searchbar
2. The entry doesn't appear

### Versions
 - macOS: 10.13.6
 - MacPass 0.7.3

**Comment by mstarke** [comment]
You can search for them in 0.7.4 but no partial matches are supported right now.

**Comment by evensteven01** [comment]
I have version 0.7.9 and even searching for the exact tag isn't locating the entries.

**Comment by mstarke** [comment]
@evensteven01 I cannot reproduce this behaviour. MacPass is getting results for exact tag matches.
