### ISSUE TITLE
Empty column in 0.7.4 in list view - minor UI glitch?

### ISSUE THREAD

**Issue by kevinpapst** [MacPass/MacPass#888]
**Describe the bug**
I just updated to 0.7.4 and there is an empty column in the list view, see screenshot.
And it can't be hidden through the context menu.

Is that an intended behavior? I am pretty sure it wasn't there before.

**Screenshots**
<img width="1164" alt="Bildschirmfoto 2019-03-19 um 12 04 19" src="https://user-images.githubusercontent.com/533162/54601658-e06ac700-4a3f-11e9-9f50-3bd7f5981d24.png">

**Desktop (please complete the following information):**
 - macOS: 10.14.3
 - Version: 0.7.4

**Comment by mstarke** [comment]
This is intended behaviour. This column for the manual sort option. Clicking on lists entries in the internal order which you can change by reordering them via drag and drop. You can resize it to be a bit smaller so the arrow doesn't show.

**Comment by kevinpapst** [comment]
Weird feature ;-) but thanks for the info and sorry for the noise.
