### ISSUE TITLE
Double clicking file: URLs stopped working in 0.7.4

### ISSUE THREAD

**Issue by pmhausen** [MacPass/MacPass#889]
**Describe the bug**
Double clicking the URL part of an entry that looks like this:

file:///Users/pmh/Nextcloud Firma/punkt.de Allgemein/Passwörter/server-pw.kdbx

stopped opening the file when I upgraded from 0.7.3 to 0.7.4

Preferences are set to open URLs in Finder.

**To Reproduce**
Create entry, double-click URL part.

**Expected behavior**
The file should be opened

**Screenshots**

**Desktop (please complete the following information):**
 - macOS: [e.g. 10.14.3]
 - Version [e.g. 0.7.4]

**Additional context**

**Comment by mstarke** [comment]
I am unable to reproduce this behaviour. I used "Default" for browser and added a file url and it worked on double-click. I also selected Finder and open again and the KDBX file was opened in MacPass. Can you double click the file in the Finder and see what happens?

**Comment by pmhausen** [comment]
It works if none of the intermediate directory names contains spaces. It doesn't in 0.7.4 but did in 0.7.3 when there are spaces in the names.

Kind regards, blazingly fast reaction! ;)
Patrick

**Comment by mstarke** [comment]
Ahhh. Yes. I removed escaping since it screwed up urls. But this now breaks spaces. Arg.

**Comment by pmhausen** [comment]
I would be perfectly happy if inserting %20 manually into the URL in MacPass would work ... IIRC KeepassXC needed this, too. If this helps to simplify your code?

**Comment by mstarke** [comment]
Inserting %20 works.

**Comment by pmhausen** [comment]
Not quite - at least here:
file:///Users/pmh/Nextcloud%20Firma/punkt.de%20Allgemein/Passwörter/server-pw.kdbx

Doesn't work for me. "Links öffnen" set to "Default Browser" - which is Safari for me. Anything wrong with my syntax? Additional quotes needed or so?

Kind regards
Patrick

**Comment by mstarke** [comment]
you need to escape the ö as well. Using this ```Users/pmh/Nextcloud%20Firma/punkt.de%20Allgemein/Passw%C3%B6rter/server-pw.kdbx``` should work. The main problem with the code is to decide whether url escaping is needed or not. If I escape by default, already escaped URLs will get double-escaped. I have to take some time to make this code work better but currently, leaving the encoding to the user is the simplest solution.

**Comment by pmhausen** [comment]
Works! Thank you - I'd say you can turn this into a documentation improvement request ;-)

I had to set my "open URLs" to the Finder, though. Leaving it at "Default Browser" the double-click opens an empty Safari window which in turn opens a Finder window with the file selected, but does not open it. And since the finder will throw regular http:// URLs at Safari just fine, that's a perfect solution for me.

Thanks again and kind regards,
Patrick
