### ISSUE TITLE
Edited state is no longer visible in 0.7.4

### ISSUE THREAD

**Issue by sanderaarts** [MacPass/MacPass#890]
**Describe the bug**
In previous versions when the db was changed 'Edited' was shown in the title bar (on macOs at least) until the changes were saved. That's no longer the case.

**To Reproduce**
1. Add new entry, but do not save yet.
2. There's no indication the db was changed (on macOs it used to show 'Edited' right after the db name in the title bar).

**Expected behavior**
A visible indication that there are unsaved changed.

**Desktop (please complete the following information):**
 - macOS: 10.14.3
 - Version 0.7.4

**Comment by mstarke** [comment]
I am unable to reproduce this error. For me the behaviour is exactly as expected. See attached file.

![EditedState](https://user-images.githubusercontent.com/58428/54611871-14ea7d00-4a58-11e9-9e54-82a99597e0ae.gif)

**Comment by georgesnow** [comment]
i tested as well on 0.7.4 macOS 10.14.3. and i am seeing edited


![Screen Shot 2019-03-19 at 9 53 36 AM](https://user-images.githubusercontent.com/12751441/54611190-dee3d380-4a2c-11e9-82c6-dd4c30462ef7.png)

**Comment by sanderaarts** [comment]
I just noticed it works on some dbs but not all. I have two dbs, both on the same server. I have full access one that does show the 'edited' string and read/write access on the one that doesn't.

As far as I  remember it used to work on both. And I would expect that read/write access should be enough for this feature to work.

**Comment by mstarke** [comment]
Can you specify your setup a bit more so I might be able to pin this down?

**Comment by sanderaarts** [comment]
macOS: 10.14.3
Version 0.7.4
2 dbs on same server, connected over smb:
db1.kdbx (read/write access, unlocking with keyfile): no edited state is shown
db2.kdbx (full access, db created by myself, unlocking with password): edited state is shown

I've also created another db on the same server to test whether the type of unlocking makes a difference, but that doesn't seem to be the case:
test.kdbx (full access, unlocking with same keyfile): edited state is shown

**Comment by mstarke** [comment]
Can you try to create the same setup with text files with TextEdit and see what happens? If the same behaviour is present this might be an macOS bug.

**Comment by mstarke** [comment]
This issue seems to be related to search! See 0.7.5. release notes

**Comment by mstarke** [comment]
@sanderaarts can you try out 0.7.5 and see if the release fixes the issue?

**Comment by sanderaarts** [comment]
@mstarke It seems to work for both dbs again in 0.7.5. Thx!

**Comment by mstarke** [comment]
awesom!
