### ISSUE TITLE
Global Autotype is not available - but works

### ISSUE THREAD

**Issue by georgesnow** [MacPass/MacPass#891]
**Describe the bug**

MacPass is saying Autotype is not available, but works with no issue
i finally just clicked the box to say ignore and said open preferences as a workaround.

**Screenshots**
![Screen Shot 2019-03-19 at 10 20 35 AM](https://user-images.githubusercontent.com/12751441/54613165-a3e39f00-4a30-11e9-874f-5531ee1d84b3.png)

![Screen Shot 2019-03-19 at 8 32 04 AM](https://user-images.githubusercontent.com/12751441/54613221-b8279c00-4a30-11e9-9eab-cf34a54210ff.png)

**Desktop (please complete the following information):**
 - macOS: 10.14.3
 - Version 0.7.4

**Comment by mstarke** [comment]
The whole privacy setup on macOS 10.14 is a mess. Can you try to remove MacPass from the list and re-add it? This happens on my dev system a lot and removing and re-adding MacPass fixes this most of the time.

**Comment by georgesnow** [comment]
yup i did that and it seems to have resolved. one note: i also checked off previously "don't show the message again" and it seemed to have surpassed the dialog even though global auto type worked. and i hadn't removed it from the list in privacy settings yet.

**Comment by georgesnow** [comment]
i am also getting an issue where the Perform AutoType is greyed out. 

i have down arrow or select another entry before the button becomes available again. 

normally you can just hit Enter with the first match highlighted.

![Screen Shot 2019-03-19 at 4 17 43 PM](https://user-images.githubusercontent.com/12751441/54638919-8e876880-4a62-11e9-9b24-98c9dfa2246e.png)

**Comment by mstarke** [comment]
@georgesnow I've created a new issue for this bug (#892)

**Comment by georgesnow** [comment]
closing this. cause this doesn't appear to be an issue anymore.
