### ISSUE TITLE
references no longer work

### ISSUE THREAD

**Issue by Sec42** [MacPass/MacPass#897]
**Describe the bug**
After the upgrade to 0.7.6 references in the password field fail to work.

**To Reproduce**
Have two entries in the database
1. "Active Directory" with user and password
2. "system" with password set to "{REF:P@T:Active Directory}"
3. Copy password on the "system" entry
4. Paste password in cleartext somewhere. Result will be "{REF:P@T:Active Directory}"

**Expected behavior**
Previous versions correctly pasted the password of the referenced entry.

**Desktop (please complete the following information):**
 - macOS: 10.14.3
 - Version 0.7.6

**Comment by mstarke** [comment]
Thank you. References with title based search are something I never quite understood. For a quick-fix you could use UUID based references (REF:P@I:<uuid>) which should work. I'll try to fix this ASAP and extend the test coverage to prevent such regressions.

**Comment by mstarke** [comment]
Behaviour is fixed. Will get released in 0.7.7

**Comment by Sec42** [comment]
Just got the update, and it works fine again, thanks.
