### ISSUE TITLE
[Enchancement]Global keyboard shortcut to show MacPass land focus in search field

### ISSUE THREAD

**Issue by georgesnow** [MacPass/MacPass#899]
I believe there is other requests, but i couldn't find them...
but after some testing and using 1P. this feature really would be so helpful.

Feature: User configurable keyboard shortcut "Show MacPass" and land focus in the search field. (while running like Global Auto-type)

Attempts to work around:
I built a Service though the OS keyboard shortcuts. however, this fails in various apps and in particular NetAuth screen for finder connecting to a server. (Global Autotype also can't recognize this window). Fail....

Why:
This also allows for the user to find the proper credential by landing in the search field. Rather than Global Auto-type which security wise if you click in the wrong field, but get a match to loose parameters or otherwise can't find a match. Wihen GAT fails usually thinking did it type it somewhere else? What happen? And then i have to open MacPass and start searching the proper credential anyway.

**Comment by mstarke** [comment]
I think this is a nice solution without the need for additional UI (e.g. a mini-search-popup comparable to 1Password mini).

I would consider two options:

1. Set the mode for Global Autotype (e.g. search and fill or autofill)
2. Add another Hotkey to differentiate the two systems.

**Comment by georgesnow** [comment]
Oh cool well my gut says adding another hot key at least initially. It makes so Macpass always invokable. And the user then searches proper entry and copies the field they want and hide the app or whatever their work flow is. 

That being said  Option 2 sounds interesting. I am curious to see what you mean and  I would have to see try it or see it in action.

**Comment by georgesnow** [comment]
@mstarke I am still interested in this feature as native feature, but I built an AppleScript in the meantime until you weigh the options. I decided to build something and found I use it a lot.


https://github.com/georgesnow/MacPassShowMe

**Comment by georgesnow** [comment]
made a plugin with menubar and global keyboard shortcut (some caveats check Readme.md):

https://github.com/georgesnow/MacPassRevealer

**Comment by georgesnow** [comment]
menubar plugin issue 
duplicate the other issue
Duplicate of #941
