### ISSUE TITLE
Item menu not visible in menu bar

### ISSUE THREAD

**Issue by FrankKooij** [MacPass/MacPass#902]
The **Item** menu is not visible in the menu bar, but the Item is functional. This appears to be an issue in the Dutch translation of versions 0.7.5, 0.7.6, 0.7.7 and perhaps 0.7.4.

![menu-bar-nl](https://user-images.githubusercontent.com/11964893/55138184-248e5380-5133-11e9-8e1b-ae289ec245aa.png)

![menu-bar-nl2](https://user-images.githubusercontent.com/11964893/55139724-b481cc80-5136-11e9-9e8d-d32e60ecd119.png)

The attached [nl.xliff](https://github.com/MacPass/MacPass/files/3016707/nl.xliff.zip) should fix this omission.

**Comment by mstarke** [comment]
I'll try to merge this in. I will attach a current export for you to include additional changes

**Comment by mstarke** [comment]
Fixed in 9a721c0a1f776a82de4ac9425a4d9f5cabaf4b56

**Comment by mstarke** [comment]
Export of xliff of commit 9a721c0a1f776a82de4ac9425a4d9f5cabaf4b56 [nl.xliff.zip](https://github.com/MacPass/MacPass/files/3016814/nl.xliff.zip)
