### ISSUE TITLE
"Create from Template" suggestion

### ISSUE THREAD

**Issue by Niko-CZ** [MacPass/MacPass#904]
Hello Michael,
I have suggestion for "Create from Template" feature. 
At the moment I believe there is extra string "Create Entry with Template" which has no sense:
![CreateFromTemplate](https://user-images.githubusercontent.com/44586336/55223144-fa1dc280-5226-11e9-90d9-c5ab2f0a0bab.png)
When we are clicking on "create from Template" we already understand that it will be used and no need to specify it in the beginning of each line.
Instead could be better to have icons from templates in the beginning of each line, similar to KeePass for WIN:
![CreateFromTemplate_WIN](https://user-images.githubusercontent.com/44586336/55223150-0013a380-5227-11e9-80ab-79385c0353ea.png)
This is especially useful when several templates created with same name, but different URLs and difference is obvious based on icon.

Regards,
Nikolay

**Comment by mstarke** [comment]
The idea to prefix the task is to make it clear what's happening. I strongly would keep at least the template prefix. Adding the icons is a good idea.

**Comment by Niko-CZ** [comment]
I agree "Template:" instead of "Create Entry with Template" would be already much better. 40% less space will be saved.
