### ISSUE TITLE
Auto-Hide option when copying username/password

### ISSUE THREAD

**Issue by Niko-CZ** [MacPass/MacPass#906]
Hello Michael,
I would suggest global option in application settings called "Hide on copy".
In case user copies username or password either by hotkey or double-click MacPass shall hide to tray. 
Actually this is what users I believe doing always - hiding or switching application after copy done, so such option will save a lot of time for those who are performing a lot of such operations per day.  
Similar option is implemented in Auto-Type (auto-hide before typing), but in some cases it is only required to copy one of the attributes.

Regards,
Nikolay

**Comment by mstarke** [comment]
A different idea: Add an additional shortcut and menu item that does what you describe

As an example for Passwords:

1. Copy Password (Cmd + Alt + C)
2. Copy Password and Hide (Cmd + Alt + Shift + C)

The shortcuts aren't the best ones and they should be changed since they are common point for criticism.

**Comment by Niko-CZ** [comment]
A little bit more complicated than global option... In this case user need to:
- remember another hotkey with 4 characters
*not so comfortable to click long combinations, no? 
- make 2 click actions to choose from menu
*will have no sense as minimizing after copy has same number of actions to be done

KeepasXC has it in form of option (in form of not comfortable "minimize" but still).
Keepass WIN as well.

**Comment by georgesnow** [comment]
just a thought what about Holding option and double clicking hides the window?

**Comment by mstarke** [comment]
I've added a setting to the workflow tab to hide MacPass on every copy-to-clipboard action that the user has issued. I first just added it to the double-click action but it's been move to a general behaviour. I am still not sure this is the right way to do it so this might change again in the future.

**Comment by georgesnow** [comment]
I will give it try as well but I did something similar with an applescript and made for a strange workflow. That’s why I mentioned if user holds the option key while triggering a copy, show copy (and hide)in the menu bar, or double click to copy. 

Seems more Native other apps when when holding the option key display extended options to a function in menus

**Comment by georgesnow** [comment]
Just realized that you ivuse the option command and c to copy a password... muscle memory didn’t even remember. 
Hmm limited buttons to use. I forgot how many keyboard short cuts there are

**Comment by mstarke** [comment]
Duplicate of #648
