### ISSUE TITLE
Hide does not work correctly

### ISSUE THREAD

**Issue by tiiiecherle** [MacPass/MacPass#908]
When opening a database by double clicking on it, the database opens and the startup window opens in its background. When hiding the database window (cmd+h) the startup window stays visible. It should also hide.

Clicking on the startup window afterwards brings the database back to the front but does not activate macpass. macOS still shows another app as active.

Additionally the startup window becomes unresponsive and can not be clicked but is still there.

I think both is not intentional. Thanks for a fix in advance. Would be nice to see a new release afterwards because I always open the database and leave it hidden in the background while using the needed login and you can't get a clear view on the desktop like this. 

Thanks

**Comment by mstarke** [comment]
By statup-window do you mean the welcome window with the file selection? This is a bug and should not happen. My setup is re-open the last database so this window practically never shows up for me so this misbehaviour might have slipped my attention.

**Comment by mstarke** [comment]
I just tried you setup and it seems there's a second database window that lingers around.

**Comment by tiiiecherle** [comment]
Yes, by startup-window I meant the welcome window.

**Comment by tiiiecherle** [comment]
> I just tried you setup and it seems there's a second database window that lingers around.

Does this implement a question or a need for checking something or did you find the cause of the issue? ;)

**Comment by georgesnow** [comment]
@tiiiecherle as a work around in the meantime for safari you could use my AppleScript with FastScripts(let’s you set global keyboard shortcuts for scripts) to better auotfill safari

Code is here:
https://github.com/georgesnow/MPSafariAF/blob/master/README.md

I have another applescript I will post soon that hides and shows Macpass Landing focus on the search field. Again using FastScripts to set a global keyboard shortcut

**Comment by georgesnow** [comment]
FastScripts is also free for the first 10 global shortcuts

**Comment by tiiiecherle** [comment]
@georgesnow: Thanks a lot for the script and the suggestion. But I would like to see the "solution" implemented in Macpass itself better. Hope the issue can be resolved soon.

**Comment by georgesnow** [comment]
Totally agree. The scripts came out of personal preference and customization. Which I wasn’t sure how quickly or if enough others thought the same. Also I really wanted to match on URL for safari. So I made a home baked solution. And decided others may find useful for this or bother places That and love to tinker.

**Comment by tiiiecherle** [comment]
Yes, I got that from the way you were writing and offering the script ;) Thanks a lot again for your effort and for sharing.

**Comment by georgesnow** [comment]
As side note I just realized I responded on the wrong thread ....I thought this was the one where person was having an issue with Autotype and safari matching...ugh🥴. When kids keep me up I should forgo commenting. sorry

**Comment by mstarke** [comment]
Found the issue. It was a wrong order in which MacPass determined if it needed to show the welcome window. Fix is in 2beb1bbceb6ad4c6009a28364bfca6669c1c584c and will get published in 0.7.10
