### ISSUE TITLE
How does auto-type work

### ISSUE THREAD

**Issue by jonasdiemer** [MacPass/MacPass#91]
From the wiki, it looks like autotype is available. How do I enable/use it?

**Comment by christophfroehlich** [comment]
Sorry if the question is too dumb, but how do I use the autotype function, especially for websites? :)
I'm using Chrome and MacPass 0.5.1, and no matter what title I give the entry, autotype doesn't work with the global shortcut!
How does MacPass search for the entries and how do I have to set up the entries?

**Comment by mstarke** [comment]
There's a lengthy discussion here #279. In 0.5.1 window associations aren't usable. They'll work on master though. So it'll work in 0.5.2.

**Comment by christophfroehlich** [comment]
Sorry, I didn't find the other Issue before. Now it works, actually I just didn't specify the windows title in the right way. Thanks for your reply!
