### ISSUE TITLE
Ok button translation issue in French

### ISSUE THREAD

**Issue by BHuck74** [MacPass/MacPass#916]
**Describe the bug**
This happens when choosing a key at database opening. The ok button label is CHOOSE_FILE_BUTTON_TITLE whereas it should be Ok.

**To Reproduce**
Select a database to be opened.
Choose a key => on this dialog box, the Ok button is not translated.

**Expected behavior**
The ok button should appears with 'Ok'

**Screenshots**

**Desktop (please complete the following information):**
 - macOS: 10.14.3
 - Version 0.7.9

![Capture d’écran 2019-04-01 à 10 54 28](https://user-images.githubusercontent.com/45630426/55315791-540fc980-546d-11e9-9515-f411020b8d3f.png)

**Comment by mstarke** [comment]
Not all localizations contain all the keys so this is a know issue since some of them were created a long time ago and I am unable to update all of them since I am only able to speak German and English.

**Comment by BHuck74** [comment]
MacPass is really a great tool, and I would be glad helping you with translating it in French. Just let me know!

**Comment by mstarke** [comment]
If you feel up to it use the attached .xliff file and update it. I'll be more than happy to integrate the changes back into MacPass.
[fr.xliff.zip](https://github.com/MacPass/MacPass/files/3048133/fr.xliff.zip)

**Comment by mstarke** [comment]
ping @BHuck74

**Comment by BHuck74** [comment]
Hello ! I downloaded the file thanks. I just need to find a time slot to do the job, but it's on my todo by end of this week at the latest 😊

**Comment by mstarke** [comment]
Nice. I'm looking forward to include this in the upcoming release.

**Comment by BHuck74** [comment]
Fine ! I'm almost finished, should be ok in a few days.

**Comment by BHuck74** [comment]
Hi there !

I'm finished with translating the file. What is the best way to send you the new file ?

**Comment by mstarke** [comment]
Awesome! Just zip the .xliff and attach it to this issue.

**Comment by BHuck74** [comment]
Here you go with the file.
There was just some items not translated into English, so I didn't touch them, since I didn't know what they are referring to.

[fr.xliff.zip](https://github.com/MacPass/MacPass/files/3093206/fr.xliff.zip)

**Comment by mstarke** [comment]
There are a lot of string in Localizeable.strings that should be understandable from the comments. If you find time to take a look at those it would be awesome if you could add more translations. I'm a bit hesitant to translate everything into english that is missing but leaving the placeholders is rather ugly and unusable :-/

**Comment by BHuck74** [comment]
I must admit you lost me at that point :-) What is Localizeable.strings ? I'm not that much familiar with development and translation. Is that another file ?

**Comment by BHuck74** [comment]
Never mind, I got it. I've found the file in the source code. It is the file under fr.lproj directory you are referring to? Because I only see 2 macros that are not translated. But perhaps I didn't understood everything.

**Comment by mstarke** [comment]
Taking a look at the source files (e.g. Localizabel.strings) does not show you all keys but onyl the ones that are already in that file. If a translation is empty those tend to be not in the file.

I just merged your changes into the source which makes a huge difference.

Do you use Xcode or did you just use a XLIFF tool to update the translations?
I can upload the current fr.xliff so you can update it even more and if you have questions regarding the context, just ask. I admit, this workflow is suboptimal but I have not come to terms with something like lokalize to work correctly in my setup.

**Comment by BHuck74** [comment]
I did use a text editor to edit the file directly, which I must admit is not optimal but again I'm not that much familiar with translation :-) Anyway, if you upload the xliff file, I can make a round again, that's not a problem. I will use a xliff tool, I think it will be more convenient!

**Comment by mstarke** [comment]
I'm closing this and we can open a new issue or a PR for updated french translations. Your changes are merged in 8cc701af5f5ed0875c9a87d0f1a60ddcc5fea458
