### ISSUE TITLE
MacPassHTTP plugin 0.3.1 not compatible with MacPass 0.7.7

### ISSUE THREAD

**Issue by ssdowd** [MacPass/MacPass#917]
**Describe the bug**
Updated to 0.7.7 (as in a bug fix version, not a major or minor version) and my MacPassHTTP (0.3.1) plugin is now tagged as "not compatible".  As this is the *only* plugin in the repository and MacPass is far less useful without it, why did a bug fix version break an API?

**To Reproduce**
1. Take the current update
2. Start MacPass
3. Watch it tell you that MacPassHTTP version 0.3.1 (90): "The plugin is not compatible with this version of MacPass"

**Expected behavior**
A bugfix update (X.Y.n to X.Y.nn) should not break an API.

**Screenshots**

**Desktop (please complete the following information):**
 - macOS: 10.14.4
 - Version 0.7.7

**Additional context**

**Comment by mstarke** [comment]
MacPass is quite capable with global Autotype and without MacPassHTTP. But aside from that 0.7.7 does or course not change any API so the plugin should work. There is no major version limit only a minimum (0.7.4) for 0.3.1 so it should not be marked as incompatible. Can you check  https://macpassapp.org/data/plugins.json and see if there is no mahout version limit on 0.3.1 for you? I did change that so you might have outdated data.

**Comment by ssdowd** [comment]
I had an issue getting 0.7.9 earlier.  When I installed that, the plugin started working again.  I'll take a look at global autotype as that would probably be more useful overall.  Closing and thanks.
