### ISSUE TITLE
Is it possible to build with XCode 5 without a paid dev account?

### ISSUE THREAD

**Issue by tsimmons** [MacPass/MacPass#92]
Sorry for the simple question; I do not have a $99/year Mac Developer account and was trying to build with XCode 5 on Mountain Lion and it errors with:

```
No matching codesigning identity found: No codesigning identities (i.e. certificate and private key pairs) matching “Mac Developer” were found.
```

Is that required for building Macpass?

Thanks &
Cheers,

Toby

**Comment by mstarke** [comment]
If you build via the command line, code signing can also be disabled there:
    
    xcodebuild -scheme MacPass -target MacPass -configuration Release CODE_SIGNING_REQUIRED=NO

**Comment by ijoseph** [comment]
As of XCode 10, [these](https://stackoverflow.com/a/54296008/588437) instructions must be followed (in short, selecting "Other…" for "Code Signing Identity" and then deleting all text in the popup box).

**Comment by Nes-si** [comment]
What I should do in the actual XCode version? I've got the error:
> error: No profiles for 'com.hicknhacksoftware.MacPass' were found: Xcode couldn't find any Mac App Development provisioning profiles matching 'com.hicknhacksoftware.MacPass'.
