### ISSUE TITLE
[Question] view multiple entries same time

### ISSUE THREAD

**Issue by georgesnow** [MacPass/MacPass#921]
maybe I am missing this, but is it possible to view multiple entries at the same time? I discovered I have 3 entries  that are the same (from importing CSV file) but they have different URLs I want to keep. ie I would like to combine them in a single entry. 

Is there a way to open 2 inspectors for each entry so I can view them side by side and copy the URL and notes from one to other?

**Comment by mstarke** [comment]
There is currently no multi-edit system in place. This is a feature that would surely be great but currently nothing is planned as to when or how to implement it.

**Comment by georgesnow** [comment]
going to close this
