### ISSUE TITLE
Question - notarization 

### ISSUE THREAD

**Issue by georgesnow** [MacPass/MacPass#925]
https://www.macrumors.com/2019/04/08/mac-apps-notarization-macos-10-14-5/

just curious does this anyway effect the deployment of MacPass on future macOS releases? Or is MacPass already getting notarized?

**Comment by mstarke** [comment]
It does not change anything at the moment since I'm not new to distributing via Developer ID. I will however use notarization in the future when I figured out how to correctly enable the hardend runtime for Sparkle since this is currently preventing me from notarizing MacPass.

**Comment by georgesnow** [comment]
awesome makes sense. just wanted to ask.
