### ISSUE TITLE
[Question] Building plug-ins

### ISSUE THREAD

**Issue by georgesnow** [MacPass/MacPass#930]
@mstarke I have been interesting in building plug-ins for MacPass. I had built some AppleScripts for improving workflow (might only particular to me). However, I was trying to determine from you MacPassHTTP plug-in how i might go about this. I am curious is there a list of hooks that are available? Do you care if plug-ins are built with Swift or prefer Obj-C? 

For reference I was attempting to building a plug that when Global AutoType is triggered if the previous app it was triggered for is Safari trigger my AppleScript and return the value from the script as the window title name instead of the window name. 
If this is something that really isn't possible then I won't pursue further, but I had some other ideas or plug-ins. So just seeking some feedback.

**Comment by mstarke** [comment]
Plugins do not need to be written in Obj-C but they need to call into MacPass (and KeePassKit most of the time) so Obj-C interoperability is required. Currently also weak linking is needed. As to what is currently possible: KeePassHTTP does not need a lot of hooks, other plugins might need a lot more (see for example KeeShare or TOTP) and my strategy was to implement a plugin and add the APIs on the go since there is no real benefit in fleshing out a public API and then nothing uses it and MacPass has to support it but without gaining anything in return.

**Comment by mstarke** [comment]
It surely is possible to integrate an API to allow "window-title-retrieval"

**Comment by mstarke** [comment]
I've just thrown in some thoughts and came up with a simple API to integrate plugins for this purpose. I think the easies way is then to run the apple script via the terminal e.g. ```osascript -e 'tell application "Safari" to get URL of front document'``` and then use this value to process the autotype further. I can set up the plugin for you and you can fine-tune it if you like or you can go the whole distance alone an create the plugin from the start after I've added the APIs

**Comment by georgesnow** [comment]
I agree. I had looked at triggering AppleScripts that are contained within a app bundle, but for this triggering via terminal makes more sense. Currently, I have an AppleScript that does parsing and some other stuff etc...but won't be needed if it incorporates to the Global Autotype framework. And i would like to incorporate the parsing into the plug-in natively using Obj-c or Swift anyway.

That would be great if you could set up the plug-in! thank you. I got buried trying to the get the plug-in setup correctly, which never happened. For this if i have something as a known good. it will speed up the time to getting a refined plug-in.

**Comment by mstarke** [comment]
I've created a branch of MacPass to extend the plugin API and added a very minimal implementation to enable your apple script setup here: https://github.com/MacPass/AutotypeURL

**Comment by georgesnow** [comment]
Awesome thanks! That was my plan for the parsing to be done inside the plug in. 
For building the actual plugin I can just follow the same directions for MacpassHttp correct?

Funny I had same thought about settings and customization. But At first I am going to try keep it focused so I can get refined. Then test my mileage on extending the customization. I am going for a little victory before I get ahead myself.

**Comment by georgesnow** [comment]
@mstarke I have my initial commit. You will see some notes. 
Only one issue is MacPass kept saying "incompatible plugin". I built from the source as noted on the readme page for the Autotype plugin and tried completing removing the repo on  my machine and uninstalling MacPass to get a clean enviro and install. No change. 

But in my test NSLogs are showing the correct values are getting generated.

**Comment by georgesnow** [comment]
![NSLog-screenshotof test](https://user-images.githubusercontent.com/12751441/57397748-5a474300-719b-11e9-9a76-393e68efb471.png)

**Comment by mstarke** [comment]
You should check "Force load incompatible plugins" and it should work fine. I tried using apple scripts in an XPC service to eliminate the need to support AppleEvents in MacPass just to let plugins make use of it but it seems apple script is not usable this way. I will try a different route by using a full helper app and using something other than XPC to communicate with it.

**Comment by georgesnow** [comment]
i did do that which is how i got the NSLog info to work. I just realized i didn't do the pull request. so you should see me notes now.

**Comment by georgesnow** [comment]
@mstarke one thing i noticed in testing AutoType with the plugin. it is limited to _only_ the main URL item in an entry. I have an entry that has a URL item, but also Custom Fields: URL-1,URL-2,URL-3. It only match on the first one. The other 3 are not possible matches. Not sure if that should be part of the plug-in or MacPass (main app) should have an option for matching on custom fields for Autotype.

**Comment by georgesnow** [comment]
@mstarke so question I built another plugin ...(still working on figuring out the view controller preferences thing on the ATURL plugin). 
this other plugin is based on my other AppleScript, which is global hotkey to unhide/active MacPass with global keyboard shortcut and hide MacPass if it's the active app. 
its crude, no customization yet, but it works  (eventually maybe I will add menu bar icon). 
However, my reason for posting is  I ran into issue when I enable Global AutoType my keyboard shortcut even though different will trigger Global AutoType. any thoughts on why? I haven't put the code on GitHub, which I can do.

**Comment by mstarke** [comment]
I have no idea why the Autotype is triggerd. You need to debug it to see how this could happen. Also - think it's unwise to use Plugins for your purpose. It seems better to use a system wide service with a keyboard shortcut to get your script to work. The main reason the other plugin uses Apple Script is to control other applications. If you use AppleScript to control MacPass itselft I would suggest to identify hooks for native code extensions.

**Comment by georgesnow** [comment]
Sorry should have been clearer. I was curious about the implementation of the DDhotkey with global autotype. I noticed their some customization and if there specifics about the conditions for when Mac pass is made active.

And I guess I should just clarify i built an native objective c (mplugin). No AppleScript. I am attempting to use the native code extensions. And whenever the plugin detects MacPass is the active app and the global hot key is pressed it hides MacPass. 

Anyway I will keep debugging

**Comment by georgesnow** [comment]
And what is strange  it works flawlessly as long as global auto type isn’t enabdled

**Comment by georgesnow** [comment]
@mstarke think i figured it out...it was cause i was using keys 2 buttons right next to each other causing accidentally trigging of Global Autotype.  ..😳

Also I wasn't sure about the licensing since I am using the "mplugin". So I left the license for BSD in there. And I wasn't if there was anything else I should include. Want to give proper credit and license for building the plugins.

Anyway code is below if interested:

https://github.com/georgesnow/MacPassRevealer

**Comment by georgesnow** [comment]
@mstarke just wondering did the autotype url branch get merged into the master?

**Comment by mstarke** [comment]
Yup. Was merged.

**Comment by georgesnow** [comment]
@mstarke closing this for now. since there are individual threads for each of the 2 plugins.
