### ISSUE TITLE
Connecting to macpassapp.org at startup... Reason?

### ISSUE THREAD

**Issue by wuehrer** [MacPass/MacPass#938]
Hello!

I'm really excited about MacPass. I have been using KeePass or KeePassXC for the last few years and found MacPass a few days ago. 
Since I'm only working on the Mac, it's wonderful for me to have a native app for passwords. I also looked at the code a bit, but I don't know anything about it. 
But I noticed some things: When starting MacPass a connection to macpassapp.org is established. If I understood it correctly, it is used to synchronize PlugIn version or something similar. 
Of course any external "connection" to a password management software is questionable and I would like to have it "gone". Is there a way to disable this connection?

Thanks again for the nice application. 

Greetings Robert

**Comment by georgesnow** [comment]
My understanding is that’s for the “sparkle” updater. I believe there is an option to turn off auto check for updates to stop that.

**Comment by wuehrer** [comment]
Thanks, I'm not a network expert, just recorded the traffic on the Macbook with Little Snitch. Only a https connection detected, unfortunately not the content evaluable. 
The update setting is off. If I switch on automatic update, then an access to "github.com" takes place. 
In the source I found the macpassapp.org address with https only in connection with PluginRepository, hence my guess on Plugin checking.

**Comment by mstarke** [comment]
MacPass only uses two outbound connections. The first is the app cast to look or updates which can be turned off in the update settings as you already have done. The second connection is for the plugin repository. This is used to check installed plugins for compatibility and also as a way to download more plugins via MacPass. Currently there is no way of disabling this behavior. But your point is valid so I will add an option to disable the online repository or to actually ask the user for permission. The problem with not connection is that I then have to ship MacPass with a copy of the plugin repository which then can only be updated when a new version is published. But it’s a drawback worth considering.

**Comment by wuehrer** [comment]
Many thanks for the quick feedback and constructive explanation to the outgoing connections. 
Yes, an option to check the plugin repository online would be a great solution. With it every user can actively control his security requirements. A central question for an app for managing sensitive data. 

Another question: The option to display files is referred to as a security risk because the file is placed in a temporary directory to be displayed. Would it be possible to display graphic files - most often - from the app itself?

Thanks again for your effort to develop this wonderful app and I hope it will be maintained and further developed for a long time.

**Comment by wuehrer** [comment]
Many thanks for the quick feedback and constructive explanation to the outgoing connections. 
Yes, an option to check the plugin repository online would be a great solution. With it every user can actively control his security requirements. A central question for an app for managing sensitive data. 

Another question: The option to display files is referred to as a security risk because the file is placed in a temporary directory to be displayed. Would it be possible to display graphic files - most often - from the app itself?

Thanks again for your effort to develop this wonderful app and I hope it will be maintained and further developed for a long time.

**Comment by wuehrer** [comment]
Many thanks for the quick feedback and constructive explanation to the outgoing connections. 
Yes, an option to check the plugin repository online would be a great solution. With it every user can actively control his security requirements. A central question for an app for managing sensitive data. 

Another question: The option to display files is referred to as a security risk because the file is placed in a temporary directory to be displayed. Would it be possible to display graphic files - most often - from the app itself?

Thanks again for your effort to develop this wonderful app and I hope it will be maintained and further developed for a long time.

**Comment by mstarke** [comment]
I'm closing this in favour of the actual feature request

**Comment by mstarke** [comment]
Feature is added to master ans will be included in todays continous release. @wuehrer If you wish to check if this is how you expect it to work use continous build. If you have any objections please speak up!
