### ISSUE TITLE
Does not lock when password field selected

### ISSUE THREAD

**Issue by CoderJason123** [MacPass/MacPass#940]
Hello MacPass! 

I'm on version 0.7.9.  The system does not go into auto lock mode when I clicked on a password field and hit copy.  I'm not sure if the copy has any impact in this behavior but worth mentioning.  If I go back in 10 minutes, MacPass is still open, unlocked.

If I am just browsing thru the list of password, I don't ever have a lock issue.  Not sure if focus is obtained and causes some issue.
____

Appreciate the software, you and the contributors have done a great job.

**Comment by georgesnow** [comment]
I believe I have experienced this issue. I noticed my database wasn’t locking after long periods of time with auto lock turned on.

**Comment by mstarke** [comment]
I tried to reproduce this but so far no luck

**Comment by CoderJason123** [comment]
I'm going to play around with the auto lock config values.  I had just done a fresh install, perhaps I don't have something checked that I did before.  Basically though i just copy (in my case i am literally just hitting cmd-c.  Not sure if this will make a difference.  As a side note, when I am in MacPass, i sometimes have to click close in order to get my mac to sleep.  That's not a topic for this thread but it makes me wonder about a focus thing.  i will try to find better re-createable conditions so you have more to go on.

**Comment by CoderJason123** [comment]
My lock when idle was set to never on a fresh install maybe?  Maybe this is the source of my issue, and thus not a real issue after all?

**Comment by CoderJason123** [comment]
I have not had this since changing the setting above, I feel like this is on me.
