### ISSUE TITLE
Plugin Compatibility with KeePass

### ISSUE THREAD

**Issue by haydenk** [MacPass/MacPass#950]
Is it possible to make it to be able to use plugins from the KeepPass Plugins page (https://keepass.info/plugins.html)?

This seems like it may resolve a lot of other requests as well.

Currently MacPass plugins are `.mpplugin` while KeePass plugins are `.plgx`. I tried renaming the extension on the plugin and while MacPass did not complain, it did not show up in the plugin list either.

**Comment by mstarke** [comment]
It is not possible to simply make keepass plugins work as is in MacPass. Both applications are using different languages. If you need full compatibility you probably should run KeePass with Mono on macOS.
