### ISSUE TITLE
[Feature] Global Autotype provide prompt on any match option

### ISSUE THREAD

**Issue by georgesnow** [MacPass/MacPass#954]
The ability to be prompted on any match when triggering global Autotype would be nice. I have sometimes entries that match that I am not expecting and if it’s the only one I have to go back to the database to figure the wrong entry.

One further extension to this would if no match is found. You get prompted with the option to be asked if you want to create a new entry

**Comment by georgesnow** [comment]
I re-read this and I realized it’s not very clear. I meant for a preference/option to allow the user to be prompted even if there is only 1 match not just when there 2 or more.

**Comment by mstarke** [comment]
That’s exactly how I read it.

**Comment by georgesnow** [comment]
@mstarke i think this implemented so I can close this issue correct?

**Comment by mstarke** [comment]
The current master has a setting to always ask before performing a match so this solves the issue if this is an ok solution

**Comment by georgesnow** [comment]
@mstarke works just as I expected thanks!
