### ISSUE TITLE
Macpass Icon Outdated ?

### ISSUE THREAD

**Issue by zibelian** [MacPass/MacPass#955]
Without stepping anyone on the toes, i really love the macpass app, but the macpass icon feels kind of outdated, would be nice if you could put some effort in updating the icon.

I am using a custom made icon, [see preview here](http://oi63.tinypic.com/14khzqs.jpg), feel free to use it if you like. Would be awesome if the designer at macpass could update the design. 

Cheers

**Comment by mstarke** [comment]
I played with a flatter version two years ago (see here: https://twitter.com/MacPassApp/status/860175717895733248) and didn’t go through with it since I’m now convinced we are about to leave flat icon land and get back to a bit more depth and detail. I will however eventually modernize the current icon a bit.

**Comment by zibelian** [comment]
> I played with a flatter version two years ago (see here: https://twitter.com/MacPassApp/status/860175717895733248) and didn’t go through with it since I’m now convinced we are about to leave flat icon land and get back to a bit more depth and detail. I will however eventually modernize the current icon a bit.

Nice icon, like it! I also believe that flat design has is reaching the end, the trend is going towards more depth and detail again, would be nice if you could give the MacPass a new fresh look.

**Comment by kud** [comment]
I don't get it about "download icon", it's disabled here: 
<img width="452" alt="image" src="https://user-images.githubusercontent.com/655838/61701060-d1718980-ad3d-11e9-8a0d-b6404b8c3473.png">

**Comment by kud** [comment]
(oh, sorry you spoke about the icon of macpass itself, not the icon pack :x)

**Comment by mstarke** [comment]
It’s disabled if no url is present.

**Comment by cipnt** [comment]
> It’s disabled if no url is present.
How cool is that!?
I've been using MacPass for so long and never know this!
Couldn't this this be the default behaviour? ie. as soon as you add or change the url the favicon is downloaded and updated
I'm going through my db now and updating every entry :)

**Comment by cipnt** [comment]
I love it! My db is now colourful 😄 
Unfortunately some ave very low resolution
Also, it seems this doesn't work if the URL redirects to another domain (ie an old link which redirects).

There are a few URLs which, for some strange reason, refuse to work.
Here are some, in case someone can debug this
https://appleid.apple.com/#!&page=signin
https://monzo.com/
https://mail.protonmail.com/login
http://vimeo.com/log_in
https://www.myunidays.com/GB/en-GB/account/log-in
https://www.vodafone.co.uk/myvodafone/

**Comment by cipnt** [comment]
Responding to the initial query

>  the macpass icon feels kind of outdated

I personally think the icon looks rather nice and in line with other modern apps
<img width="268" alt="Screenshot 2019-10-07 at 22 30 48" src="https://user-images.githubusercontent.com/1532455/66350173-89ccc800-e952-11e9-9a2a-6f73eeeec7f8.png">

**Comment by kud** [comment]
Me too I think the icon is really cool. :)

**Comment by veraverto** [comment]
One more voice to say that the current icon is beautiful and I'd say a flatter version isn't necessary at all!

**Comment by ryanthara** [comment]
Flatter is not even better. 

> It’s disabled if no url is present.

This is a thing, most users will find out some day or never. I think, it could be described better. Maybe with an info box, or a tip when you add a url to the field?

**Comment by mstarke** [comment]
I‘m closing this for now since there are no plans to change the icon anytime soon.
