### ISSUE TITLE
Duplicate group

### ISSUE THREAD

**Issue by That-Dude** [MacPass/MacPass#957]
Being able to right-click on a group and duplicate it.

Use case: I have a group perfectly configured for all of the devices on a network, I'd like to be able to duplicate entire group and entries so that I can just change the passwords for the next network I set up.

**Comment by mstarke** [comment]
Currentyl MacPass offers the ability to duplicate a group via drag and drop.

1. Drag the group
2. Press ```Alt``` on the keyboard to copy instead of move the group.

It's a good idea to add this feature to the context menu

**Comment by mstarke** [comment]
Closed in favour of a more precise issue #963
