### ISSUE TITLE
[Bug] Global Autotype MacPass doesn't rehide window after w/ multiple entries

### ISSUE THREAD

**Issue by georgesnow** [MacPass/MacPass#964]
Hide MacPass
trigger global auto type
multiple entries window shows AND database
perform autotype 
MacPass stays the front most app

not sure if this intended behavior, but i thought if you selected an entry and performed autotype it would re-hide MacPass. but maybe not?

macOS: 10.14.6
MacPass: 0.7.9

**Comment by mstarke** [comment]
MacPass will not re-hide if it was hidden when auto-type was run. Also, un-hiding for the entry selection window to show up also will show any other windows since I cannot only show a single window. It might be a good idea to re-hide if MacPass was hidden.

**Comment by georgesnow** [comment]
ok thought that was the case. not insanely important. it would be nice enhancement.

**Comment by mstarke** [comment]
MacPass now re-hides itself if it was un-hidden when performing Autotype

**Comment by georgesnow** [comment]
@mstarke this is a small simple user feature that has made a huge difference for me. wanted to say thanks for adding this.
