### ISSUE TITLE
Creation Date is not same with keepass

### ISSUE THREAD

**Issue by kaich** [MacPass/MacPass#966]
**Describe the bug**
when create a file with keepassxc. I open it with macpass, I found the creation date is not same with keepassxc. The macpass show "2019-8-19 3: 11: 59". but keepassxc show "2019-8-21 3: 11: 59". I have test it with keepass and keeweb. They are same with keepassxc. 

**To Reproduce**
1. create a kdbx with keepassxc
2. open with macpass
3. look at the creation date. They are different.

**Expected behavior**
I think the creation date should be same with all other keepass client.

**Comment by mstarke** [comment]
Fixed in master
