### ISSUE TITLE
Status Icon is not informative

### ISSUE THREAD

**Issue by justinphelps** [MacPass/MacPass#967]
**Describe the bug**
The Finder status menu is not indicative of what process it represents. 
There is an icon for macpass in the Finder menu, but it does not say anywhere who it belongs to, it just says "Server OK!". This is not helpful to anyone that doesn't know exactly what the macpass icon represents. 
It would be better if it said "MacPass Server OK!" (Or not OK etc.)
It took me a lot of trial and error to figure out what this status icon represented. 

**To Reproduce**
1. Start Macpass
2. Look on menu bar. 
3. Click macpass icon. 
4. It says "Server OK!".. not which server, what process, etc. 

**Expected behavior**
Clicking on the Macpass finder icon should tell you that it represents the status of Macpass. Not just the status of an unknown process. 

**Screenshots**
![image](https://user-images.githubusercontent.com/2535057/63692536-307d5f00-c812-11e9-9820-24c17fa4f9e4.png)

**Desktop (please complete the following information):**
 - macOS: 10.14.6
 - Version  0.7.9 (21570)

**Additional context**

**Comment by mstarke** [comment]
This is related to MacPassHTTP so this shoud be moved to the appropriate repository. Moved to https://github.com/MacPass/MacPassHTTP/issues/59
