### ISSUE TITLE
One time passwords / 2 Factor Authentication

### ISSUE THREAD

**Issue by cipnt** [MacPass/MacPass#977]
Hi all,

Loving MacPass and using it everyday. 
One thing that I miss is the ability to generate one time passwords / 2 factor authentication codes for apps and websites.
Two step authentication is very common these days and it would be great to have that option built into MacPass instead of having to rely on a different app (eg Google Authenticator)

There is a KeePass placeholder [{HMACOTP}](https://keepass.info/help/base/placeholders.html#hmacotp) that can generate OTP/2FA codes but I can't get it to work in MacPass. 
Also, for added security, it would be nice if these were time-based OTPs.

Since [Google Authenticator is open source](https://github.com/google/google-authenticator), would it be difficult to implement?

1Password has a very nice implementation of this.

Thanks!

**Comment by georgesnow** [comment]
#895 you can take a look at that issue. my understanding in the short version it is still a work in progress for MacPass.

**Comment by mstarke** [comment]
HMACOTP as well as OTP (and the steam variant) are more or less completely supported by KeePassKit. MacPass "only" needs UI to get everything going which is currently the biggest hurdle .

**Comment by defcon8** [comment]
I agree.. Google Authenticator support is a must have! Having only one password to secure your MacPass wallet is not secure.

**Comment by ypicard** [comment]
Just checking in to see if there are any updates on this?

**Comment by mstarke** [comment]
It‘s done and will get pushed out with 0.8 which should get released soon.

**Comment by Oll0w4in** [comment]
Hey there,
is there any documentation for adding OTP in MacPass? In detail I mean, how can you add the OTP Key which you get at the beginning of the 2FA. I have acces to my 'otpauth://totp/' Links and could insert them into my Entries. 
But I can not find the function to add them to MacPass and thats why I search for a Documentation (The Wiki here on GitHub is not helpfull for this) or another hint how to insert them.

But, I am a huge Fan of KeePass and MacPass or the kbdx in general. Great Work and lovely program. 
Good luck furthermore with it!

**Comment by mstarke** [comment]
0.7.2 has no support for TOTP only HMACOTP. If you want to use TOTP you can try the continous build or wait for 0.8 to get released. If you want to add TOTP in MacPass you can use the opt custom field or you can use the wizzard in MacPass which you can access by opening it via the drop down besides the "add custom field" button.

<img width="709" alt="Screenshot 2022-02-04 at 13 56 51" src="https://user-images.githubusercontent.com/58428/152532943-d3a86212-8438-4216-a767-69bc962e88a4.png">

The a wizzard pops up and you can add you URL there

<img width="1056" alt="Screenshot 2022-02-04 at 13 57 09" src="https://user-images.githubusercontent.com/58428/152532956-22e86c77-6d93-4221-8733-2acaa876615b.png">

**Comment by Oll0w4in** [comment]
Okay maybe I try 0.8 but nice to know that in the near future there will be an update to support this.
Thank you very much for you documentation.
Again, very nice Programm!

**Comment by jkroepke** [comment]
I have MacPass 0.8.1, but I can't see this menu (on existing databases)

**Comment by ThHirsch** [comment]
How do I use the Token in the Autotype sequence then? Is that even possible in current v0.8.1

**Comment by Oll0w4in** [comment]
Yes it is possible. Just type {TOTP} and the current code will be used. Am 29.09.2023 um 12:38 schrieb THirsch ***@***.***>:﻿
How do I use the Token in the Autotype sequence then? Is that even possible in current v0.8.1
