### ISSUE TITLE
Autotype settings.

### ISSUE THREAD

**Issue by valueff** [MacPass/MacPass#978]
Hey. I can not configure Autotype. I want to enter bank card details in the form. Name, Number, Expiration Date, CVV. Name, Number are entered normally. Expiration date and CVV are not entered.

I set up the fields like this: {PASSWORD}{TAB}{EXPDATE}{TAB}{USERNAME}{TAB}{VVV}{ENTER}

Result in pic:

![autotype1](https://user-images.githubusercontent.com/14850058/65935742-9ec9c880-e433-11e9-8de6-d6566cfa8cf0.png)

Then I tried changing the settings. I clicked on the gear. Dragged possible fields to Autotype Sequence. I do not understand, how i can save it.

<img width="446" alt="Снимок экрана 2019-10-01 в 9 56 49" src="https://user-images.githubusercontent.com/14850058/65935572-f3207880-e432-11e9-9fea-6972bab3df5a.png">

 - macOS: [e.g. 10.14.16]
 - MAC PASS 0.7.9 (21570)

Please help, if possible. Thank.

**Comment by mstarke** [comment]
The Autotype builder is currently not working. You can use the sequence and paste it manually into the Autotype field.

**Comment by valueff** [comment]
Wow! Thank you so much. It works now.
