### ISSUE TITLE
New entry should have a key icon by default (instead of folder)

### ISSUE THREAD

**Issue by tkafka** [MacPass/MacPass#979]
**Is your feature request related to a problem? Please describe.**
When I create a new entry, it currently gets a folder icon by default - and when I don't like my entries to look like groups, I have to manually change it. I would prefer the defaults to be a folder icon for a new group, and a key icon for a new entry.

Is it possible that this is an effect of https://github.com/MacPass/MacPass/issues/298 ? Yes, when my group has a credit card icon, I can see that I'd like to have new entries there have a credit card icon too, but default folder icon should be an exception in my opinion.

**Describe the solution you'd like**
If a group has a default folder icon, new entries created there will have a key icon.

**Describe alternatives you've considered**
Keep the existing system?

**Additional context**
This is what is happening today:
<img width="245" alt="Screenshot 2019-10-02 10 42 03" src="https://user-images.githubusercontent.com/876717/66030551-e9b21180-e501-11e9-82fb-183d65d77934.png">
<img width="252" alt="Screenshot 2019-10-02 10 42 17" src="https://user-images.githubusercontent.com/876717/66030553-e9b21180-e501-11e9-892f-3b190113c55c.png">

This is what I'd like to happen:
<img width="245" alt="Screenshot 2019-10-02 10 42 03" src="https://user-images.githubusercontent.com/876717/66030615-064e4980-e502-11e9-9c59-1706dd102955.png">
<img width="251" alt="Screenshot 2019-10-02 10 47 19" src="https://user-images.githubusercontent.com/876717/66030616-06e6e000-e502-11e9-988c-05421074a8c2.png">

**Comment by cipnt** [comment]
Mine defaults to the key icon 😕

**Comment by tkafka** [comment]
@cipnt Aha! Now I see what was happening - I have accidentally changed a group icon from 'closed folder' (default one) to an 'open folder' (a custom one), and then all new entries in that group started inheriting it. I only now noticed it's a different icon and that other groups behave ok. 

Thanks for noticing, I'm closing this issue.

<img width="111" alt="Screenshot 2019-10-08 10 16 00" src="https://user-images.githubusercontent.com/876717/66378923-c6c9a680-e9b4-11e9-9bd5-9bd8ed1540c5.png">
