### ISSUE TITLE
Focus on Search After Unlock

### ISSUE THREAD

**Issue by dotjersh** [MacPass/MacPass#980]
**Is your feature request related to a problem? Please describe.**
When I open MacPass via spotlight, the unlock password input is already selected. When I unlock the database, I have to click the search box to search for an entry. 

**Describe the solution you'd like**
The ideal would be that the search-box is already selected.

**Describe alternatives you've considered**
I've looked for a shortcut to select the search box, and tried tab to select the search-box and neither options are available. 

**Additional context**
This is the only road block to inputing a password from macPass completely mouse free.

**Comment by georgesnow** [comment]
my plugin provides that functionally - hoping to work @mstarke how to port the code into the core code base..

https://github.com/georgesnow/MacPassRevealer

Check out:

#941

**Comment by georgesnow** [comment]
@dotjersh did you ever give the updated build a try?

**Comment by dotjersh** [comment]
Hey! Yeah, gave it a try, no luck either. Same process. Any ideas?

**Comment by georgesnow** [comment]
@dotjersh saw your other post. I am also working on the ability to add your master password to your keychain (as convenance feature) as well as Touch ID. #514 if you are interested.

**Comment by georgesnow** [comment]
in regards to your completely mouse free efforts

**Comment by mstarke** [comment]
You can use ```Cmd + F``` to start the search. Also available under Edit -> Find

**Comment by ryanthara** [comment]
> **Describe the solution you'd like**
> The ideal would be that the search-box is already selected.

Otherwise an option will be to select the first entry of the database - here in the German version 'Allgemein' from which a keyboard based navigation is possible.

> **Additional context**
> This is the only road block to inputing a password from macPass completely mouse free.

Full by your side.

**Comment by dotjersh** [comment]
> You can use `Cmd + F` to start the search. Also available under Edit -> Find

Holy crap, this is exactly what I was looking for.

**Comment by iparr** [comment]
Unfortunately @georgesnow plugin no-longer seems to work.

Autofocus upon unlock without a plugin would be a really wonderful option to have.

**Comment by georgesnow** [comment]
@iparr oh really? did you check the console for errors? is it not loading the plugin?

and your second point. if I actually get chunk of time I will tackle this. all my side dev stuff has had to take backseat.  😕

**Comment by iparr** [comment]
![Screenshot 2020-09-22 at 19 05 20](https://user-images.githubusercontent.com/497635/93920219-c67e0480-fd06-11ea-9ce6-fa43c6dbe1ea.png)

This is all I'm going off. I'm unable to find the console - sorry.

Such is life! Thank you.

**Comment by mstarke** [comment]
This might be a side-effect of notarization. The error message is produced when MacPass tries to load the plugin bundle and this one is early on so I suspect some gatekeeper issue.

**Comment by DominusExult** [comment]
So it might need some entitlements (entitlements.plist) that needs to be pointed at when you codesign.
