### ISSUE TITLE
[Bug] Catalina copied notifier is over saturated

### ISSUE THREAD

**Issue by georgesnow** [MacPass/MacPass#982]
it seems apple up the color saturation. and the copy notifier is too dark. attached picture.

<img width="161" alt="Screen Shot 2019-10-10 at 12 25 59 PM" src="https://user-images.githubusercontent.com/12751441/66587903-5b6d0980-eb59-11e9-8f57-c75a071c36b2.png">

**Comment by mstarke** [comment]
The window is also not correctly displayed in 10.14. The rounded corners aren't rendered correctly.
