### ISSUE TITLE
Firewall

### ISSUE THREAD

**Issue by mbrucco** [MacPass/MacPass#983]
I added to firewall settings, but it is still appear.

Do you want the application “MacPass.app” to accept incoming network connections?

Any suggestion?

**Comment by mstarke** [comment]
Not really, can you elaborate what connection MacPass wants to open?

**Comment by georgesnow** [comment]
My immediate though is when you say incoming to MacPass is the HTTP plugin. Which listens in the loop back for connections. Are you using the macoasshttp plugin?

**Comment by mbrucco** [comment]
Yes I do 

Inviato da iPhone

**Comment by mstarke** [comment]
@mbrucco  I'll close this since it seem to be resolved.
