### ISSUE TITLE
macOS Catalina: Can't save database if it is on a network volume (WebDav)

### ISSUE THREAD

**Issue by maltokyo** [MacPass/MacPass#986]
If the DB is on WebDav, my mac can no longer save it.  I think it is due to the hardened permissions of the new macOS Catalina.

This is the same dav dir I have always used, and I can save files and folders into there from the Finder, and edit them as well, so I know that is not the issue.

Now, when I make a change in a DB (add new entry etc) I get this.
![image](https://user-images.githubusercontent.com/1388507/67150100-a8688280-f2b3-11e9-866d-7b0bf1862d86.png)

I tried looking in Settings "Security and Privacy" section if there is any way I can add it in there, but cannot find anything.

As an example, if there was some way to add Macpass and check "Network Volumes" here, I am sure it would work, but the app doesn't propose this, and I cannot add it manually.

![image](https://user-images.githubusercontent.com/1388507/67150142-0b5a1980-f2b4-11e9-8b1c-0b9d60fea0b8.png)

I just confirmed this, with BBEdit, I tried to save a blank text file on the Dav directory, and BBEdit asked this:
![image](https://user-images.githubusercontent.com/1388507/67150340-90463280-f2b6-11e9-84f9-3eff3db78a3f.png)
It then was added in the Security preferences above like this.
![image](https://user-images.githubusercontent.com/1388507/67150348-b66bd280-f2b6-11e9-8e77-c4d2b210ac50.png)

MacPass needs to ask for the same permissions - no way to add it manually.

**Comment by mstarke** [comment]
Nice find. I think I will need to link to the 10.15 SDK to get this to work flawlessly. A workaround for you might be to open the file in the finder, then MacPass should have access to the file.

**Comment by mstarke** [comment]
@maltokyo can you confirm that opening the file via the Finder will fix the issue? Otherwise there I need to add keys to the info.plist to allow MacPass to get access to network storage.

**Comment by maltokyo** [comment]
Apologies I’m away from my Mac until the weekend. I could confirm then.

**Comment by dnavre** [comment]
Also having this issue with Google Drive File Stream.

**Comment by georgesnow** [comment]
when you are opening your database are opening from Finder or from Macpass by selecting File=>Open and navatigsting in the Open file panel to your database?

**Comment by maltokyo** [comment]
I upgraded to the latest version in which the release notes mention this
issue.
The same error occurs (I can open the DB but not save changes) even after
selecting the DB through the File -> Open menu.
So this does not solve the problem

**Comment by mstarke** [comment]
That’s a rather sad decision on apples side to break old applications that way. I’m going to get a 10.15 setup running on the upcoming week and will be able to test a release to fix this and a couple of the other  issues with 10.15. I have to say MacPass did transition to a lot of OS releases from its beginning on 10.7 but the upgrade to 10.15 is by far the roughest in so far.

**Comment by maltokyo** [comment]
Indeed. It’s causing many issues on other apps that I compile from source
too.
Thank you for taking a look at it. When you need testing done please let me
know.

**Comment by maltokyo** [comment]
I just tried now to double click the db file icon in the finder webdav dir
to open the program that way. And it worked! I can now edit. Really
strange.

**Comment by mstarke** [comment]
I've tried a smb volume which yielded no errors. I could open the database, save it, even duplicate it.
This leaves WebDAV and some other protocols open for testing.

**Comment by mstarke** [comment]
Related to #991

**Comment by maltokyo** [comment]
I still can only edit DB entries on a WebDav volume after double-clicking the file in finder to open.  Unable to edit when the DB is opened without a finder double click.

**Comment by maltokyo** [comment]
@mstarke I do not know why, but it becomes unbearable for me.  Even when I double click on the file in the WebDav share, it cannot be saved after an edit.  As Webdav is the only way I can open it at work on windows, I am stuck.  Would you have any ideas for resolution here?

**Comment by haf-tech** [comment]
same here with 0.7.12 and shared volume/webdav, opening from Finder did also not solved the issue.
Closing the database getting also the additional error message

```
The document “...” is on a volume that does not support permanent version storage.
```

**Comment by jbkkd** [comment]
Google drive recently changed their implementation to use a network drive, and I can't save files on it - getting the same "could not be saved" error

**Comment by mstarke** [comment]
I‘ll try to investigate on the issue.

**Comment by matangover** [comment]
Confirm I'm getting the same error with the new Google Drive client.

**Comment by zelazowy** [comment]
> Confirm I'm getting the same error with the new Google Drive client.

yeah, me too. Any update on this?

**Comment by mstarke** [comment]
Nope. But will take a look at it asap.

**Comment by mstarke** [comment]
The error message that pops up (when closing the file) is this one:
![Screenshot 2021-11-03 at 11 16 40](https://user-images.githubusercontent.com/58428/140043137-5f56e8a9-06aa-44c3-bee1-65c286422256.png)

Simply checking the box "don't ask again" and hitting Ok fixes the issue. The file gets saved properly (as mentioned in the error message) but no versioning takes place.

You might get additional error in the log but those simply state that no versions can be stored but the database file is correctly saved.

**Comment by mstarke** [comment]
This issue will also arise with any other app that tries to store versioned files on a file system that does not support those features.

You can test this out by simply creating a file with Textedit and save it in Google Drive. Open the file again, change it and close Textedit. The same error message pops up.

**Comment by zelazowy** [comment]
Ok, it seems that it required also restart of Google Drive and MacPass, I also created a copy of the original file and now it works. Thanks for the information! 💃

**Comment by jbkkd** [comment]
I installed Monterey 12.0.1 and it solved the saving problem, without having to check "Don't ask again" 🤷
