### ISSUE TITLE
double click link to copy to clipboard resets after app restart

### ISSUE THREAD

**Issue by joh-klein** [MacPass/MacPass#989]
**Describe the bug**
When the setting "workflow -> double click on link" is changed from the default "open link" to "copy link" it only works till the app is closed (cmd+q). After opening it again the setting is back to the default

**To Reproduce**
1. Go to Settings
2. Click on Workflow
3. Change "double click on link" to "copy link"
3a. Make sure it works (Double click on a address of an entry should not open a browser but give a modal "link copied"
4. Close App (CMD+Q)
5. Open App
6. Double click on an address of an entry
7. The browser should open instead of the link being copied to the clipboard

**Expected behavior**
The setting is remembered

**Desktop (please complete the following information):**
 - macOS: 10.14.6
 - MacPass Version: 0.7.10 (22740)

**Comment by mstarke** [comment]
Nice find, this issue is present since 2b1de3d63bc26fd341eaa8100e497bac1404dac2 which is sort of forever. Fixed in 3817bf503f39771faf3cdc8ad774db3ea01bc1f4.
