### ISSUE TITLE
Missing Screen recording permission are detected even if they are present

### ISSUE THREAD

**Issue by mstarke** [MacPass/MacPass#993]
**Describe the bug**
MacPass will report missing screen recording permissions for certain cases even if the permissions are correctly granted

**To Reproduce**
The behaviour get's triggered when an application does not provide a window title in the API. This is a weak check for screen recording permissions

**Expected behavior**
Missing permissions are only reported when they actually are missing

**Desktop (please complete the following information):**
 - macOS: 10.15.x
 - Version 0.7.10

**Comment by georgesnow** [comment]
I am seeing the same thing you describe. I tried the shortcut seen in the picture didn't do anything. I had changed the hotkey to something else (⌃⌥M), it started working. I then changed it back again (⌃⌥\). still works but still shows Doctor button

![Screen Shot 2019-11-01 at 4 13 50 PM](https://user-images.githubusercontent.com/12751441/68053653-dfcb2c00-fcc2-11e9-8a64-10061af00ec0.png)
![Screen Shot 2019-11-01 at 4 13 23 PM](https://user-images.githubusercontent.com/12751441/68053659-e22d8600-fcc2-11e9-97c5-e3534434e984.png)

**Comment by mstarke** [comment]
The test is reduced to only yield any issues when no window title at all was found. This is still not the ideal solution but should fix most if not all of the false positive hits (fixed in f10735f96fb11428cf714e11c90ce64cfdf73e07)

**Comment by mstarke** [comment]
Related to #992

**Comment by ericmoret** [comment]
I am seeing this problem as well, running 0.7.11 on MacOS 10.15.3. I found out I can fix it by uninstalling MacPass (deleting it from the Applications folder) then reinstalling it. It works this way for sometime before facing the same issue again: not finding a match on Autotype and having the Autotype Doctor showing that MacPass is missing screen recording permission.
