### ISSUE TITLE
10.15.1 Accessibility list won't let you uncheck MacPass

### ISSUE THREAD

**Issue by georgesnow** [MacPass/MacPass#994]
I had to manually remove and re-add. And now I can uncheck. However, global auto type still isn't working.

![image](https://user-images.githubusercontent.com/12751441/67977501-9ad5c580-fbee-11e9-8487-f0fd3bf180bf.png)

**Comment by mstarke** [comment]
Is this still present when running only a single instance of MacPass? Or does this have to do with some issue regarding multiple instances of MacPass being installed on the system?

**Comment by georgesnow** [comment]
@matarke I haven’t encountered this again. I am going to chalk it up to building/running/removing  multiple copies of macpass.
