### ISSUE TITLE
With macOS 10.15 the first view has scaling whitespace

### ISSUE THREAD

**Issue by xor-gate** [MacPass/MacPass#996]
**Describe the bug**
I just installed macOS 10.15 and saw weird scaling of the "home/splash screen". On the right there is an empty space.

**To Reproduce**
1. Start fresh installed MacPass
4. See whitespace in "the splashscreen"

**Expected behavior**
No whitespace

**Screenshots**
<img width="675" alt="Screenshot 2019-11-01 at 21 59 53" src="https://user-images.githubusercontent.com/1050166/68058024-1b341d80-fcf8-11e9-820e-624853aca93b.png">

**Desktop (please complete the following information):**
 - macOS: 10.15.2 (dark mode)
 - Version 0.7.10

**Comment by mstarke** [comment]
The white space you describe is the place where the recent files will be displayed. This space is always visible even when no files are present.

**Comment by xor-gate** [comment]
At least I would expect a section text like: "Recent opened databases" - "No recent databases" or similar. Which is a better UX than a blank tile.

**Comment by mstarke** [comment]
Agreed. Will update this in an upcoming release.

**Comment by xor-gate** [comment]
Great 👍

**Comment by xor-gate** [comment]
Great!
