### ISSUE TITLE
⌘+⌥+ U won't open url's in Chrome / Mojave

### ISSUE THREAD

**Issue by mlindhout** [MacPass/MacPass#997]
Hi,

I used to use ⌘+⌥+ U to open URL's associated with password entries and it worked for a long time. But now, nothing happens anymore. Chrome is set as my default browser, no other apps (like OSX keyboard shortcuts or Alfred) uses the key combinations. I also enabled 'double click on URL's to open', but that also doesn't work.

Chrome 78.0.3904.87
macOS Mojave
MacPass 0.7.10

**Comment by mstarke** [comment]
I just tried to reproduce this without any luck. Does MacPass open the URL in Safari if it's set as the default browser?

**Comment by mstarke** [comment]
Can you check whether MacPass is listed in the following privacy settings?
- Automation
- Accessibility

**Comment by mlindhout** [comment]
It doesn't work with Safari either. To be clear, ⌘+ U to copy the URL does work. MacPass is listed and checked in Accessibility. In Automation it is not listed at all.

**Comment by mlindhout** [comment]
It stopped working one update ago. I thought it to be a bug that would be fixed quickly, but in the last update it still didn't work. May be it's my system. I don't know.

**Comment by mstarke** [comment]
There was only a bug that did not store the workflow preferences on what to do on double-clicking the URL. I have a freshly installed 10.15.1 system and MacPass does open URLs just fine.
Does the open only not work when using the shortcut or also when invoking it via the context menu?

**Comment by mlindhout** [comment]
The context menu doesn't work either.

**Comment by mstarke** [comment]
Can you go to the terminal an type "open https://apple.com" and see what happens?

**Comment by mstarke** [comment]
In MacPass you can set what application to use when opening an URL, can you check them as well?

**Comment by mlindhout** [comment]
Terminal command works, opens Chrome. See https://pasteboard.co/IFgaTxa.png for settings.

**Comment by mlindhout** [comment]
I installed choose Chrome Canary as app to open URL's and it works! Seems to be my Chrome installation.

**Comment by mstarke** [comment]
This might be an issue with MacPass. MacPass just uses fixed bundle identifiers so this might not work correctly. But it should fall back to the default if the application isn't found that was choosen by the setting.

But I'm glad the issue did get resolved!

**Comment by mlindhout** [comment]
Yeah, it must be something like that. I just tested Safari and Chrome again and they both work...
